#*****************************************************************************************
# Vivado (TM) v2024.2 (64-bit)
#
# ov2311_c2c-export.tcl: Tcl script for re-creating project 'ov2311_c2c'
#
# Generated by Vivado on Fri Mar 06 16:16:59 EET 2026
# IP Build 5239520 on Sun Nov 10 16:12:51 MST 2024
#
# This file contains the Vivado Tcl commands for re-creating the project to the state*
# when this script was generated. In order to re-create the project, please source this
# file in the Vivado Tcl Shell.
#
# * Note that the runs in the created project will be configured the same way as the
#   original project, however they will not be launched automatically. To regenerate the
#   run results please launch the synthesis/implementation runs as needed.
#
#*****************************************************************************************
# NOTE: In order to use this script for source control purposes, please make sure that the
#       following files are added to the source control system:-
#
# 1. This project restoration tcl script (ov2311_c2c-export.tcl) that was generated.
#
# 2. The following source(s) files that were local or imported into the original project.
#    (Please see the '$orig_proj_dir' and '$origin_dir' variable setting below at the start of the script)
#
#    <none>
#
# 3. The following remote source files that were added to the original project:-
#
#    "/home/uif04883/isolde/c2c_resizer/mipi-vcu118/board/constr_mipi_cam0.xdc"
#
#*****************************************************************************************

# Check file required for this script exists
proc checkRequiredFiles { origin_dir} {
  set status true
  set files [list \
 "[file normalize "$origin_dir/board/constr_mipi_cam0.xdc"]"\
  ]
  foreach ifile $files {
    if { ![file isfile $ifile] } {
      puts " Could not find remote file $ifile "
      set status false
    }
  }

  set paths [list \
 "[file normalize "$origin_dir/[file normalize "$origin_dir/../vivado-ip/vcu118"]"]"\
 "[file normalize "$origin_dir/[file normalize "$origin_dir/../../new_resizer/vivado-ip/vcu118/int_enable"]"]"\
  ]
  foreach ipath $paths {
    if { ![file isdirectory $ipath] } {
      puts " Could not access $ipath "
      set status false
    }
  }

  return $status
}
# Set the reference directory for source file relative paths (by default the value is script directory path)
set origin_dir "."

# Use origin directory path location variable, if specified in the tcl shell
if { [info exists ::origin_dir_loc] } {
  set origin_dir $::origin_dir_loc
}

# Set the project name
set _xil_proj_name_ "ov2311_c2c"

# Use project name variable, if specified in the tcl shell
if { [info exists ::user_project_name] } {
  set _xil_proj_name_ $::user_project_name
}

variable script_file
set script_file "ov2311_c2c-export.tcl"

# Help information for this script
proc print_help {} {
  variable script_file
  puts "\nDescription:"
  puts "Recreate a Vivado project from this script. The created project will be"
  puts "functionally equivalent to the original project for which this script was"
  puts "generated. The script contains commands for creating a project, filesets,"
  puts "runs, adding/importing sources and setting properties on various objects.\n"
  puts "Syntax:"
  puts "$script_file"
  puts "$script_file -tclargs \[--origin_dir <path>\]"
  puts "$script_file -tclargs \[--project_name <name>\]"
  puts "$script_file -tclargs \[--help\]\n"
  puts "Usage:"
  puts "Name                   Description"
  puts "-------------------------------------------------------------------------"
  puts "\[--origin_dir <path>\]  Determine source file paths wrt this path. Default"
  puts "                       origin_dir path value is \".\", otherwise, the value"
  puts "                       that was set with the \"-paths_relative_to\" switch"
  puts "                       when this script was generated.\n"
  puts "\[--project_name <name>\] Create project with the specified name. Default"
  puts "                       name is the name of the project from where this"
  puts "                       script was generated.\n"
  puts "\[--help\]               Print help information for this script"
  puts "-------------------------------------------------------------------------\n"
  exit 0
}

if { $::argc > 0 } {
  for {set i 0} {$i < $::argc} {incr i} {
    set option [string trim [lindex $::argv $i]]
    switch -regexp -- $option {
      "--origin_dir"   { incr i; set origin_dir [lindex $::argv $i] }
      "--project_name" { incr i; set _xil_proj_name_ [lindex $::argv $i] }
      "--help"         { print_help }
      default {
        if { [regexp {^-} $option] } {
          puts "ERROR: Unknown option '$option' specified, please type '$script_file -tclargs --help' for usage info.\n"
          return 1
        }
      }
    }
  }
}

# Set the directory path for the original project from where this script was exported
set orig_proj_dir "[file normalize "$origin_dir/vivado/ov2311_c2c"]"

# Check for paths and files needed for project creation
set validate_required 0
if { $validate_required } {
  if { [checkRequiredFiles $origin_dir] } {
    puts "Tcl file $script_file is valid. All files required for project creation is accesable. "
  } else {
    puts "Tcl file $script_file is not valid. Not all files required for project creation is accesable. "
    return
  }
}

# Create project
create_project ${_xil_proj_name_} "/home/uif04883/isolde/c2c_resizer/mipi-vcu118/vivado/ov2311_c2c" -part xcvu9p-flga2104-2L-e

# Set the directory path for the new project
set proj_dir [get_property directory [current_project]]

# Reconstruct message rules
set_msg_config  -id {[BD 41-1306]}  -suppress  -ruleid {5}  -source 2
set_msg_config  -id {[BD 41-1271]}  -suppress  -ruleid {6}  -source 2


# Set project properties
set obj [current_project]
set_property -name "board_part" -value "xilinx.com:vcu118:part0:2.4" -objects $obj
set_property -name "default_lib" -value "xil_defaultlib" -objects $obj
set_property -name "enable_resource_estimation" -value "0" -objects $obj
set_property -name "enable_vhdl_2008" -value "1" -objects $obj
set_property -name "ip_cache_permissions" -value "read write" -objects $obj
set_property -name "ip_output_repo" -value "$proj_dir/${_xil_proj_name_}.cache/ip" -objects $obj
set_property -name "mem.enable_memory_map_generation" -value "1" -objects $obj
set_property -name "platform.board_id" -value "vcu118" -objects $obj
set_property -name "platform.name" -value "vcu118_mipi_uart_115200" -objects $obj
set_property -name "revised_directory_structure" -value "1" -objects $obj
set_property -name "sim.central_dir" -value "$proj_dir/${_xil_proj_name_}.ip_user_files" -objects $obj
set_property -name "sim.ip.auto_export_scripts" -value "1" -objects $obj
set_property -name "simulator_language" -value "Mixed" -objects $obj
set_property -name "sim_compile_state" -value "1" -objects $obj
set_property -name "use_inline_hdl_ip" -value "1" -objects $obj
set_property -name "xpm_libraries" -value "XPM_CDC XPM_FIFO XPM_MEMORY" -objects $obj

# Create 'sources_1' fileset (if not found)
if {[string equal [get_filesets -quiet sources_1] ""]} {
  create_fileset -srcset sources_1
}

# Set IP repository paths
set obj [get_filesets sources_1]
if { $obj != {} } {
   set_property "ip_repo_paths" "[file normalize "$origin_dir/../vivado-ip/vcu118"] [file normalize "$origin_dir/../../new_resizer/vivado-ip/vcu118/int_enable"]" $obj

   # Rebuild user ip_repo's index before adding any source files
   update_ip_catalog -rebuild
}

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset properties
set obj [get_filesets sources_1]
set_property -name "dataflow_viewer_settings" -value "min_width=16" -objects $obj
set_property -name "top" -value "ov2311_c2c_wrapper" -objects $obj

# Create 'constrs_1' fileset (if not found)
if {[string equal [get_filesets -quiet constrs_1] ""]} {
  create_fileset -constrset constrs_1
}

# Set 'constrs_1' fileset object
set obj [get_filesets constrs_1]

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/board/constr_mipi_cam0.xdc"]"
set file_added [add_files -norecurse -fileset $obj [list $file]]
set file "$origin_dir/board/constr_mipi_cam0.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property -name "file_type" -value "XDC" -objects $file_obj

# Set 'constrs_1' fileset properties
set obj [get_filesets constrs_1]

# Create 'sim_1' fileset (if not found)
if {[string equal [get_filesets -quiet sim_1] ""]} {
  create_fileset -simset sim_1
}

# Set 'sim_1' fileset object
set obj [get_filesets sim_1]
# Empty (no sources present)

# Set 'sim_1' fileset properties
set obj [get_filesets sim_1]
set_property -name "sim_wrapper_top" -value "1" -objects $obj
set_property -name "top" -value "ov2311_c2c_wrapper" -objects $obj
set_property -name "top_lib" -value "xil_defaultlib" -objects $obj

# Set 'utils_1' fileset object
set obj [get_filesets utils_1]
# Empty (no sources present)

# Set 'utils_1' fileset properties
set obj [get_filesets utils_1]


# Adding sources referenced in BDs, if not already added


# Proc to create BD ov2311_c2c
proc cr_bd_ov2311_c2c { parentCell } {

  # CHANGE DESIGN NAME HERE
  set design_name ov2311_c2c

  common::send_gid_msg -ssname BD::TCL -id 2010 -severity "INFO" "Currently there is no design <$design_name> in project, so creating one..."

  create_bd_design $design_name

  set bCheckIPsPassed 1
  ##################################################################
  # CHECK IPs
  ##################################################################
  set bCheckIPs 1
  if { $bCheckIPs == 1 } {
     set list_check_ips "\ 
  xilinx.com:ip:axi_chip2chip:5.0\
  xilinx.com:ip:axi_protocol_converter:2.1\
  xilinx.com:ip:vio:3.0\
  xilinx.com:ip:axi_gpio:2.0\
  xilinx.com:ip:axi_uartlite:2.0\
  xilinx.com:ip:ddr4:2.2\
  xilinx.com:ip:mdm:3.2\
  xilinx.com:ip:microblaze:11.0\
  xilinx.com:ip:axi_intc:4.1\
  xilinx.com:ip:xlconcat:2.1\
  xilinx.com:ip:axi_vdma:6.3\
  xilinx.com:hls:img2axis_v4:1.0\
  xilinx.com:hls:isolde_resizer_v5:1.0\
  xilinx.com:ip:clk_wiz:6.0\
  xilinx.com:ip:proc_sys_reset:5.0\
  xilinx.com:ip:axi_iic:2.1\
  xilinx.com:ip:mipi_csi2_rx_subsystem:6.0\
  user.org:user:int_enable:2.0\
  xilinx.com:ip:lmb_bram_if_cntlr:4.0\
  xilinx.com:ip:lmb_v10:3.0\
  xilinx.com:ip:blk_mem_gen:8.4\
  "

   set list_ips_missing ""
   common::send_gid_msg -ssname BD::TCL -id 2011 -severity "INFO" "Checking if the following IPs exist in the project's IP catalog: $list_check_ips ."

   foreach ip_vlnv $list_check_ips {
      set ip_obj [get_ipdefs -all $ip_vlnv]
      if { $ip_obj eq "" } {
         lappend list_ips_missing $ip_vlnv
      }
   }

   if { $list_ips_missing ne "" } {
      catch {common::send_gid_msg -ssname BD::TCL -id 2012 -severity "ERROR" "The following IPs are not found in the IP Catalog:\n  $list_ips_missing\n\nResolution: Please add the repository containing the IP(s) to the project." }
      set bCheckIPsPassed 0
   }

  }

  if { $bCheckIPsPassed != 1 } {
    common::send_gid_msg -ssname BD::TCL -id 2023 -severity "WARNING" "Will not continue with creation of design due to the error(s) above."
    return 3
  }

  
# Hierarchical cell: microblaze_0_local_memory
proc create_hier_cell_microblaze_0_local_memory { parentCell nameHier } {

  variable script_folder

  if { $parentCell eq "" || $nameHier eq "" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2092 -severity "ERROR" "create_hier_cell_microblaze_0_local_memory() - Empty argument(s)!"}
     return
  }

  # Get object for parentCell
  set parentObj [get_bd_cells $parentCell]
  if { $parentObj == "" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2090 -severity "ERROR" "Unable to find parent cell <$parentCell>!"}
     return
  }

  # Make sure parentObj is hier blk
  set parentType [get_property TYPE $parentObj]
  if { $parentType ne "hier" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2091 -severity "ERROR" "Parent <$parentObj> has TYPE = <$parentType>. Expected to be <hier>."}
     return
  }

  # Save current instance; Restore later
  set oldCurInst [current_bd_instance .]

  # Set parent object as current
  current_bd_instance $parentObj

  # Create cell and set as current instance
  set hier_obj [create_bd_cell -type hier $nameHier]
  current_bd_instance $hier_obj

  # Create interface pins
  create_bd_intf_pin -mode MirroredMaster -vlnv xilinx.com:interface:lmb_rtl:1.0 DLMB

  create_bd_intf_pin -mode MirroredMaster -vlnv xilinx.com:interface:lmb_rtl:1.0 ILMB


  # Create pins
  create_bd_pin -dir I -type clk LMB_Clk
  create_bd_pin -dir I -type rst SYS_Rst

  # Create instance: dlmb_bram_if_cntlr, and set properties
  set dlmb_bram_if_cntlr [ create_bd_cell -type ip -vlnv xilinx.com:ip:lmb_bram_if_cntlr:4.0 dlmb_bram_if_cntlr ]
  set_property CONFIG.C_ECC {0} $dlmb_bram_if_cntlr


  # Create instance: dlmb_v10, and set properties
  set dlmb_v10 [ create_bd_cell -type ip -vlnv xilinx.com:ip:lmb_v10:3.0 dlmb_v10 ]

  # Create instance: ilmb_bram_if_cntlr, and set properties
  set ilmb_bram_if_cntlr [ create_bd_cell -type ip -vlnv xilinx.com:ip:lmb_bram_if_cntlr:4.0 ilmb_bram_if_cntlr ]
  set_property CONFIG.C_ECC {0} $ilmb_bram_if_cntlr


  # Create instance: ilmb_v10, and set properties
  set ilmb_v10 [ create_bd_cell -type ip -vlnv xilinx.com:ip:lmb_v10:3.0 ilmb_v10 ]

  # Create instance: lmb_bram, and set properties
  set lmb_bram [ create_bd_cell -type ip -vlnv xilinx.com:ip:blk_mem_gen:8.4 lmb_bram ]
  set_property -dict [list \
    CONFIG.Memory_Type {True_Dual_Port_RAM} \
    CONFIG.use_bram_block {BRAM_Controller} \
  ] $lmb_bram


  # Create interface connections
  connect_bd_intf_net -intf_net microblaze_0_dlmb [get_bd_intf_pins DLMB] [get_bd_intf_pins dlmb_v10/LMB_M]
  connect_bd_intf_net -intf_net microblaze_0_dlmb_bus [get_bd_intf_pins dlmb_bram_if_cntlr/SLMB] [get_bd_intf_pins dlmb_v10/LMB_Sl_0]
  connect_bd_intf_net -intf_net microblaze_0_dlmb_cntlr [get_bd_intf_pins dlmb_bram_if_cntlr/BRAM_PORT] [get_bd_intf_pins lmb_bram/BRAM_PORTA]
  connect_bd_intf_net -intf_net microblaze_0_ilmb [get_bd_intf_pins ILMB] [get_bd_intf_pins ilmb_v10/LMB_M]
  connect_bd_intf_net -intf_net microblaze_0_ilmb_bus [get_bd_intf_pins ilmb_bram_if_cntlr/SLMB] [get_bd_intf_pins ilmb_v10/LMB_Sl_0]
  connect_bd_intf_net -intf_net microblaze_0_ilmb_cntlr [get_bd_intf_pins ilmb_bram_if_cntlr/BRAM_PORT] [get_bd_intf_pins lmb_bram/BRAM_PORTB]

  # Create port connections
  connect_bd_net -net SYS_Rst_1  [get_bd_pins SYS_Rst] \
  [get_bd_pins dlmb_bram_if_cntlr/LMB_Rst] \
  [get_bd_pins dlmb_v10/SYS_Rst] \
  [get_bd_pins ilmb_bram_if_cntlr/LMB_Rst] \
  [get_bd_pins ilmb_v10/SYS_Rst]
  connect_bd_net -net microblaze_0_Clk  [get_bd_pins LMB_Clk] \
  [get_bd_pins dlmb_bram_if_cntlr/LMB_Clk] \
  [get_bd_pins dlmb_v10/LMB_Clk] \
  [get_bd_pins ilmb_bram_if_cntlr/LMB_Clk] \
  [get_bd_pins ilmb_v10/LMB_Clk]

  # Restore current instance
  current_bd_instance $oldCurInst
}
  
# Hierarchical cell: MIPI_Pipeline
proc create_hier_cell_MIPI_Pipeline { parentCell nameHier } {

  variable script_folder

  if { $parentCell eq "" || $nameHier eq "" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2092 -severity "ERROR" "create_hier_cell_MIPI_Pipeline() - Empty argument(s)!"}
     return
  }

  # Get object for parentCell
  set parentObj [get_bd_cells $parentCell]
  if { $parentObj == "" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2090 -severity "ERROR" "Unable to find parent cell <$parentCell>!"}
     return
  }

  # Make sure parentObj is hier blk
  set parentType [get_property TYPE $parentObj]
  if { $parentType ne "hier" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2091 -severity "ERROR" "Parent <$parentObj> has TYPE = <$parentType>. Expected to be <hier>."}
     return
  }

  # Save current instance; Restore later
  set oldCurInst [current_bd_instance .]

  # Set parent object as current
  current_bd_instance $parentObj

  # Create cell and set as current instance
  set hier_obj [create_bd_cell -type hier $nameHier]
  current_bd_instance $hier_obj

  # Create interface pins
  create_bd_intf_pin -mode Master -vlnv xilinx.com:interface:gpio_rtl:1.0 GPIO_rsvd

  create_bd_intf_pin -mode Master -vlnv xilinx.com:interface:iic_rtl:1.0 IIC_sensor

  create_bd_intf_pin -mode Master -vlnv xilinx.com:interface:aximm_rtl:1.0 M_AXI_S2MM

  create_bd_intf_pin -mode Slave -vlnv xilinx.com:interface:aximm_rtl:1.0 S_AXI

  create_bd_intf_pin -mode Slave -vlnv xilinx.com:interface:aximm_rtl:1.0 S_AXI1

  create_bd_intf_pin -mode Slave -vlnv xilinx.com:interface:aximm_rtl:1.0 S_AXI2

  create_bd_intf_pin -mode Slave -vlnv xilinx.com:interface:aximm_rtl:1.0 S_AXI_LITE

  create_bd_intf_pin -mode Slave -vlnv xilinx.com:interface:aximm_rtl:1.0 csirxss_s_axi

  create_bd_intf_pin -mode Slave -vlnv xilinx.com:interface:mipi_phy_rtl:1.0 mipi_phy_if_0

  create_bd_intf_pin -mode Slave -vlnv xilinx.com:interface:aximm_rtl:1.0 s_axi_CTRL


  # Create pins
  create_bd_pin -dir I bg0_pin0_nc_0
  create_bd_pin -dir I bg2_pin0_nc_0
  create_bd_pin -dir I -type clk dphy_clk_200M
  create_bd_pin -dir O -type intr iic2intc_irpt
  create_bd_pin -dir I -type clk s_axi_aclk
  create_bd_pin -dir I -type rst s_axi_aresetn
  create_bd_pin -dir O int_o

  # Create instance: axi_gpio_2, and set properties
  set axi_gpio_2 [ create_bd_cell -type ip -vlnv xilinx.com:ip:axi_gpio:2.0 axi_gpio_2 ]
  set_property -dict [list \
    CONFIG.C_ALL_OUTPUTS {1} \
    CONFIG.C_GPIO_WIDTH {4} \
  ] $axi_gpio_2


  # Create instance: axi_iic_0, and set properties
  set axi_iic_0 [ create_bd_cell -type ip -vlnv xilinx.com:ip:axi_iic:2.1 axi_iic_0 ]
  set_property CONFIG.IIC_FREQ_KHZ {400} $axi_iic_0


  # Create instance: axi_vdma_0, and set properties
  set axi_vdma_0 [ create_bd_cell -type ip -vlnv xilinx.com:ip:axi_vdma:6.3 axi_vdma_0 ]
  set_property -dict [list \
    CONFIG.c_include_mm2s {0} \
    CONFIG.c_include_s2mm_dre {1} \
    CONFIG.c_m_axi_s2mm_data_width {32} \
    CONFIG.c_s2mm_max_burst_length {32} \
  ] $axi_vdma_0


  # Create instance: mipi_csi2_rx_subsyst_0, and set properties
  set mipi_csi2_rx_subsyst_0 [ create_bd_cell -type ip -vlnv xilinx.com:ip:mipi_csi2_rx_subsystem:6.0 mipi_csi2_rx_subsyst_0 ]
  set_property -dict [list \
    CONFIG.CLK_LANE_IO_LOC {AL35} \
    CONFIG.CMN_NUM_LANES {2} \
    CONFIG.CMN_NUM_PIXELS {2} \
    CONFIG.CMN_PXL_FORMAT {RAW8} \
    CONFIG.CSI_BUF_DEPTH {1024} \
    CONFIG.C_CLK_LANE_IO_POSITION {13} \
    CONFIG.C_CSI_FILTER_USERDATATYPE {false} \
    CONFIG.C_DATA_LANE1_IO_POSITION {28} \
    CONFIG.C_DPHY_LANES {2} \
    CONFIG.C_EN_BG0_PIN0 {true} \
    CONFIG.C_EN_BG2_PIN0 {true} \
    CONFIG.C_HS_LINE_RATE {900} \
    CONFIG.C_HS_SETTLE_NS {146} \
    CONFIG.DATA_LANE0_IO_LOC {AT35} \
    CONFIG.DATA_LANE1_IO_LOC {AJ32} \
    CONFIG.DPY_EN_REG_IF {true} \
    CONFIG.DPY_LINE_RATE {900} \
    CONFIG.HP_IO_BANK_SELECTION {43} \
    CONFIG.SupportLevel {1} \
    CONFIG.VFB_TU_WIDTH {1} \
  ] $mipi_csi2_rx_subsyst_0


  # Create instance: int_enable_0, and set properties
  set int_enable_0 [ create_bd_cell -type ip -vlnv user.org:user:int_enable:2.0 int_enable_0 ]

  # Create instance: axi_gpio_0, and set properties
  set axi_gpio_0 [ create_bd_cell -type ip -vlnv xilinx.com:ip:axi_gpio:2.0 axi_gpio_0 ]
  set_property -dict [list \
    CONFIG.C_ALL_OUTPUTS {1} \
    CONFIG.C_GPIO_WIDTH {1} \
  ] $axi_gpio_0


  # Create interface connections
  connect_bd_intf_net -intf_net S_AXI2_1 [get_bd_intf_pins S_AXI2] [get_bd_intf_pins axi_gpio_0/S_AXI]
  connect_bd_intf_net -intf_net axi_gpio_2_GPIO [get_bd_intf_pins GPIO_rsvd] [get_bd_intf_pins axi_gpio_2/GPIO]
  connect_bd_intf_net -intf_net axi_iic_0_IIC [get_bd_intf_pins IIC_sensor] [get_bd_intf_pins axi_iic_0/IIC]
  connect_bd_intf_net -intf_net axi_vdma_0_M_AXI_S2MM [get_bd_intf_pins M_AXI_S2MM] [get_bd_intf_pins axi_vdma_0/M_AXI_S2MM]
  connect_bd_intf_net -intf_net microblaze_0_axi_periph_M03_AXI [get_bd_intf_pins S_AXI1] [get_bd_intf_pins axi_gpio_2/S_AXI]
  connect_bd_intf_net -intf_net microblaze_0_axi_periph_M04_AXI [get_bd_intf_pins S_AXI] [get_bd_intf_pins axi_iic_0/S_AXI]
  connect_bd_intf_net -intf_net microblaze_0_axi_periph_M07_AXI [get_bd_intf_pins S_AXI_LITE] [get_bd_intf_pins axi_vdma_0/S_AXI_LITE]
  connect_bd_intf_net -intf_net microblaze_0_axi_periph_M08_AXI [get_bd_intf_pins csirxss_s_axi] [get_bd_intf_pins mipi_csi2_rx_subsyst_0/csirxss_s_axi]
  connect_bd_intf_net -intf_net mipi_phy_if_0_1 [get_bd_intf_pins mipi_phy_if_0] [get_bd_intf_pins mipi_csi2_rx_subsyst_0/mipi_phy_if]

  # Create port connections
  connect_bd_net -net axi_gpio_0_gpio_io_o  [get_bd_pins axi_gpio_0/gpio_io_o] \
  [get_bd_pins int_enable_0/def_value_i]
  connect_bd_net -net axi_iic_0_iic2intc_irpt  [get_bd_pins axi_iic_0/iic2intc_irpt] \
  [get_bd_pins iic2intc_irpt]
  connect_bd_net -net axi_vdma_0_s_axis_s2mm_tready  [get_bd_pins axi_vdma_0/s_axis_s2mm_tready] \
  [get_bd_pins mipi_csi2_rx_subsyst_0/video_out_tready]
  connect_bd_net -net bg0_pin0_nc_0_1  [get_bd_pins bg0_pin0_nc_0] \
  [get_bd_pins mipi_csi2_rx_subsyst_0/bg0_pin0_nc]
  connect_bd_net -net bg2_pin0_nc_0_1  [get_bd_pins bg2_pin0_nc_0] \
  [get_bd_pins mipi_csi2_rx_subsyst_0/bg2_pin0_nc]
  connect_bd_net -net clk_wiz_1_clk_out2  [get_bd_pins dphy_clk_200M] \
  [get_bd_pins mipi_csi2_rx_subsyst_0/dphy_clk_200M]
  connect_bd_net -net int_enable_0_int_o  [get_bd_pins int_enable_0/int_o] \
  [get_bd_pins int_o]
  connect_bd_net -net int_enable_0_t_user_o  [get_bd_pins int_enable_0/t_user_o] \
  [get_bd_pins axi_vdma_0/s_axis_s2mm_tuser]
  connect_bd_net -net microblaze_0_Clk  [get_bd_pins s_axi_aclk] \
  [get_bd_pins axi_gpio_2/s_axi_aclk] \
  [get_bd_pins axi_iic_0/s_axi_aclk] \
  [get_bd_pins axi_vdma_0/m_axi_s2mm_aclk] \
  [get_bd_pins axi_vdma_0/s_axi_lite_aclk] \
  [get_bd_pins axi_vdma_0/s_axis_s2mm_aclk] \
  [get_bd_pins mipi_csi2_rx_subsyst_0/lite_aclk] \
  [get_bd_pins mipi_csi2_rx_subsyst_0/video_aclk] \
  [get_bd_pins axi_gpio_0/s_axi_aclk]
  connect_bd_net -net mipi_csi2_rx_subsyst_0_video_out_tdata  [get_bd_pins mipi_csi2_rx_subsyst_0/video_out_tdata] \
  [get_bd_pins axi_vdma_0/s_axis_s2mm_tdata]
  connect_bd_net -net mipi_csi2_rx_subsyst_0_video_out_tlast  [get_bd_pins mipi_csi2_rx_subsyst_0/video_out_tlast] \
  [get_bd_pins axi_vdma_0/s_axis_s2mm_tlast]
  connect_bd_net -net mipi_csi2_rx_subsyst_0_video_out_tuser  [get_bd_pins mipi_csi2_rx_subsyst_0/video_out_tuser] \
  [get_bd_pins int_enable_0/t_user_i]
  connect_bd_net -net mipi_csi2_rx_subsyst_0_video_out_tvalid  [get_bd_pins mipi_csi2_rx_subsyst_0/video_out_tvalid] \
  [get_bd_pins axi_vdma_0/s_axis_s2mm_tvalid]
  connect_bd_net -net rst_clk_wiz_1_100M_peripheral_aresetn  [get_bd_pins s_axi_aresetn] \
  [get_bd_pins axi_gpio_2/s_axi_aresetn] \
  [get_bd_pins axi_iic_0/s_axi_aresetn] \
  [get_bd_pins axi_vdma_0/axi_resetn] \
  [get_bd_pins mipi_csi2_rx_subsyst_0/lite_aresetn] \
  [get_bd_pins mipi_csi2_rx_subsyst_0/video_aresetn] \
  [get_bd_pins axi_gpio_0/s_axi_aresetn]

  # Perform GUI Layout
  regenerate_bd_layout -hierarchy [get_bd_cells /CAM_Subsystem/MIPI_Pipeline] -layout_string {
   "ActiveEmotionalView":"Default View",
   "Default View_ScaleFactor":"0.764571",
   "Default View_TopLeft":"-373,3",
   "ExpandedHierarchyInLayout":"",
   "guistr":"# # String gsaved with Nlview 7.8.0 2024-04-26 e1825d835c VDI=44 GEI=38 GUI=JA:21.0 TLS
#  -string -flagsOSRD
preplace port GPIO_rsvd -pg 1 -lvl 4 -x 1140 -y 420 -defaultsOSRD
preplace port IIC_sensor -pg 1 -lvl 4 -x 1140 -y 780 -defaultsOSRD
preplace port M_AXI_S2MM -pg 1 -lvl 4 -x 1140 -y 160 -defaultsOSRD
preplace port S_AXI -pg 1 -lvl 0 -x 0 -y 780 -defaultsOSRD
preplace port S_AXI1 -pg 1 -lvl 0 -x 0 -y 400 -defaultsOSRD
preplace port S_AXI2 -pg 1 -lvl 0 -x 0 -y 150 -defaultsOSRD
preplace port S_AXI_LITE -pg 1 -lvl 0 -x 0 -y 60 -defaultsOSRD
preplace port csirxss_s_axi -pg 1 -lvl 0 -x 0 -y 530 -defaultsOSRD
preplace port mipi_phy_if_0 -pg 1 -lvl 0 -x 0 -y 510 -defaultsOSRD
preplace port s_axi_CTRL -pg 1 -lvl 0 -x 0 -y 20 -defaultsOSRD
preplace port port-id_bg0_pin0_nc_0 -pg 1 -lvl 0 -x 0 -y 610 -defaultsOSRD
preplace port port-id_bg2_pin0_nc_0 -pg 1 -lvl 0 -x 0 -y 630 -defaultsOSRD
preplace port port-id_dphy_clk_200M -pg 1 -lvl 0 -x 0 -y 590 -defaultsOSRD
preplace port port-id_iic2intc_irpt -pg 1 -lvl 4 -x 1140 -y 800 -defaultsOSRD
preplace port port-id_s_axi_aclk -pg 1 -lvl 0 -x 0 -y 550 -defaultsOSRD
preplace port port-id_s_axi_aresetn -pg 1 -lvl 0 -x 0 -y 190 -defaultsOSRD
preplace inst axi_gpio_2 -pg 1 -lvl 3 -x 900 -y 420 -defaultsOSRD
preplace inst axi_iic_0 -pg 1 -lvl 3 -x 900 -y 800 -defaultsOSRD
preplace inst axi_vdma_0 -pg 1 -lvl 3 -x 900 -y 180 -defaultsOSRD
preplace inst mipi_csi2_rx_subsyst_0 -pg 1 -lvl 1 -x 200 -y 590 -defaultsOSRD
preplace inst int_enable_0 -pg 1 -lvl 2 -x 520 -y 170 -defaultsOSRD
preplace inst axi_gpio_0 -pg 1 -lvl 1 -x 200 -y 170 -defaultsOSRD
preplace netloc axi_iic_0_iic2intc_irpt 1 3 1 NJ 800
preplace netloc bg0_pin0_nc_0_1 1 0 1 NJ 610
preplace netloc bg2_pin0_nc_0_1 1 0 1 NJ 630
preplace netloc clk_wiz_1_clk_out2 1 0 1 NJ 590
preplace netloc microblaze_0_Clk 1 0 3 30 410 NJ 410 670
preplace netloc rst_clk_wiz_1_100M_peripheral_aresetn 1 0 3 20 770 NJ 770 680
preplace netloc mipi_csi2_rx_subsyst_0_video_out_tdata 1 1 2 370 240 630J
preplace netloc mipi_csi2_rx_subsyst_0_video_out_tuser 1 1 1 380 160n
preplace netloc axi_vdma_0_s_axis_s2mm_tready 1 1 2 400 260 650J
preplace netloc mipi_csi2_rx_subsyst_0_video_out_tlast 1 1 2 390 250 640J
preplace netloc mipi_csi2_rx_subsyst_0_video_out_tvalid 1 1 2 410 270 660J
preplace netloc int_enable_0_t_user_o 1 2 1 N 180
preplace netloc axi_gpio_0_gpio_io_o 1 1 1 N 180
preplace netloc axi_gpio_2_GPIO 1 3 1 NJ 420
preplace netloc axi_iic_0_IIC 1 3 1 NJ 780
preplace netloc axi_vdma_0_M_AXI_S2MM 1 3 1 NJ 160
preplace netloc microblaze_0_axi_periph_M03_AXI 1 0 3 NJ 400 NJ 400 NJ
preplace netloc microblaze_0_axi_periph_M04_AXI 1 0 3 NJ 780 NJ 780 NJ
preplace netloc microblaze_0_axi_periph_M07_AXI 1 0 3 NJ 60 NJ 60 NJ
preplace netloc microblaze_0_axi_periph_M08_AXI 1 0 1 NJ 530
preplace netloc mipi_phy_if_0_1 1 0 1 NJ 510
preplace netloc S_AXI2_1 1 0 1 NJ 150
levelinfo -pg 1 0 200 520 900 1140
pagesize -pg 1 -db -bbox -sgen -160 0 1290 880
"
}

  # Restore current instance
  current_bd_instance $oldCurInst
}
  
# Hierarchical cell: Clock_Reset
proc create_hier_cell_Clock_Reset { parentCell nameHier } {

  variable script_folder

  if { $parentCell eq "" || $nameHier eq "" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2092 -severity "ERROR" "create_hier_cell_Clock_Reset() - Empty argument(s)!"}
     return
  }

  # Get object for parentCell
  set parentObj [get_bd_cells $parentCell]
  if { $parentObj == "" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2090 -severity "ERROR" "Unable to find parent cell <$parentCell>!"}
     return
  }

  # Make sure parentObj is hier blk
  set parentType [get_property TYPE $parentObj]
  if { $parentType ne "hier" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2091 -severity "ERROR" "Parent <$parentObj> has TYPE = <$parentType>. Expected to be <hier>."}
     return
  }

  # Save current instance; Restore later
  set oldCurInst [current_bd_instance .]

  # Set parent object as current
  current_bd_instance $parentObj

  # Create cell and set as current instance
  set hier_obj [create_bd_cell -type hier $nameHier]
  current_bd_instance $hier_obj

  # Create interface pins

  # Create pins
  create_bd_pin -dir O -from 0 -to 0 -type rst bus_struct_reset
  create_bd_pin -dir O -type clk clk_out2
  create_bd_pin -dir I -type rst ext_reset_in
  create_bd_pin -dir I -type rst mb_debug_sys_rst
  create_bd_pin -dir O -type rst mb_reset
  create_bd_pin -dir O -from 0 -to 0 -type rst peripheral_aresetn
  create_bd_pin -dir O -from 0 -to 0 -type rst peripheral_aresetn1
  create_bd_pin -dir I -type rst reset
  create_bd_pin -dir I -type clk slowest_sync_clk
  create_bd_pin -dir O -type clk slowest_sync_clk1

  # Create instance: clk_wiz_1, and set properties
  set clk_wiz_1 [ create_bd_cell -type ip -vlnv xilinx.com:ip:clk_wiz:6.0 clk_wiz_1 ]
  set_property -dict [list \
    CONFIG.CLKOUT2_JITTER {88.577} \
    CONFIG.CLKOUT2_PHASE_ERROR {77.836} \
    CONFIG.CLKOUT2_REQUESTED_OUT_FREQ {200} \
    CONFIG.CLKOUT2_USED {true} \
    CONFIG.CLK_IN1_BOARD_INTERFACE {Custom} \
    CONFIG.MMCM_CLKOUT1_DIVIDE {6} \
    CONFIG.NUM_OUT_CLKS {2} \
    CONFIG.PRIM_SOURCE {Single_ended_clock_capable_pin} \
    CONFIG.RESET_BOARD_INTERFACE {reset} \
    CONFIG.USE_BOARD_FLOW {true} \
  ] $clk_wiz_1


  # Create instance: rst_clk_wiz_1_100M, and set properties
  set rst_clk_wiz_1_100M [ create_bd_cell -type ip -vlnv xilinx.com:ip:proc_sys_reset:5.0 rst_clk_wiz_1_100M ]
  set_property -dict [list \
    CONFIG.RESET_BOARD_INTERFACE {reset} \
    CONFIG.USE_BOARD_FLOW {true} \
  ] $rst_clk_wiz_1_100M


  # Create instance: rst_ddr4_0_300M, and set properties
  set rst_ddr4_0_300M [ create_bd_cell -type ip -vlnv xilinx.com:ip:proc_sys_reset:5.0 rst_ddr4_0_300M ]

  # Create port connections
  connect_bd_net -net clk_wiz_1_clk_out2  [get_bd_pins clk_wiz_1/clk_out2] \
  [get_bd_pins clk_out2]
  connect_bd_net -net clk_wiz_1_locked  [get_bd_pins clk_wiz_1/locked] \
  [get_bd_pins rst_clk_wiz_1_100M/dcm_locked]
  connect_bd_net -net ddr4_0_c0_ddr4_ui_clk  [get_bd_pins slowest_sync_clk] \
  [get_bd_pins clk_wiz_1/clk_in1] \
  [get_bd_pins rst_ddr4_0_300M/slowest_sync_clk]
  connect_bd_net -net ddr4_0_c0_ddr4_ui_clk_sync_rst  [get_bd_pins ext_reset_in] \
  [get_bd_pins rst_ddr4_0_300M/ext_reset_in]
  connect_bd_net -net mdm_1_debug_sys_rst  [get_bd_pins mb_debug_sys_rst] \
  [get_bd_pins rst_clk_wiz_1_100M/mb_debug_sys_rst]
  connect_bd_net -net microblaze_0_Clk  [get_bd_pins clk_wiz_1/clk_out1] \
  [get_bd_pins slowest_sync_clk1] \
  [get_bd_pins rst_clk_wiz_1_100M/slowest_sync_clk]
  connect_bd_net -net reset_1  [get_bd_pins reset] \
  [get_bd_pins clk_wiz_1/reset] \
  [get_bd_pins rst_clk_wiz_1_100M/ext_reset_in]
  connect_bd_net -net rst_clk_wiz_1_100M_bus_struct_reset  [get_bd_pins rst_clk_wiz_1_100M/bus_struct_reset] \
  [get_bd_pins bus_struct_reset]
  connect_bd_net -net rst_clk_wiz_1_100M_mb_reset  [get_bd_pins rst_clk_wiz_1_100M/mb_reset] \
  [get_bd_pins mb_reset]
  connect_bd_net -net rst_clk_wiz_1_100M_peripheral_aresetn  [get_bd_pins rst_clk_wiz_1_100M/peripheral_aresetn] \
  [get_bd_pins peripheral_aresetn]
  connect_bd_net -net rst_ddr4_0_300M_peripheral_aresetn  [get_bd_pins rst_ddr4_0_300M/peripheral_aresetn] \
  [get_bd_pins peripheral_aresetn1]

  # Restore current instance
  current_bd_instance $oldCurInst
}
  
# Hierarchical cell: Resizer_BD
proc create_hier_cell_Resizer_BD { parentCell nameHier } {

  variable script_folder

  if { $parentCell eq "" || $nameHier eq "" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2092 -severity "ERROR" "create_hier_cell_Resizer_BD() - Empty argument(s)!"}
     return
  }

  # Get object for parentCell
  set parentObj [get_bd_cells $parentCell]
  if { $parentObj == "" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2090 -severity "ERROR" "Unable to find parent cell <$parentCell>!"}
     return
  }

  # Make sure parentObj is hier blk
  set parentType [get_property TYPE $parentObj]
  if { $parentType ne "hier" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2091 -severity "ERROR" "Parent <$parentObj> has TYPE = <$parentType>. Expected to be <hier>."}
     return
  }

  # Save current instance; Restore later
  set oldCurInst [current_bd_instance .]

  # Set parent object as current
  current_bd_instance $parentObj

  # Create cell and set as current instance
  set hier_obj [create_bd_cell -type hier $nameHier]
  current_bd_instance $hier_obj

  # Create interface pins
  create_bd_intf_pin -mode Master -vlnv xilinx.com:interface:aximm_rtl:1.0 M_AXI_S2MM

  create_bd_intf_pin -mode Slave -vlnv xilinx.com:interface:aximm_rtl:1.0 S_AXI_LITE

  create_bd_intf_pin -mode Master -vlnv xilinx.com:interface:aximm_rtl:1.0 m_axi_data_mem

  create_bd_intf_pin -mode Slave -vlnv xilinx.com:interface:aximm_rtl:1.0 s_axi_cfg_port


  # Create pins
  create_bd_pin -dir I -type rst axi_resetn
  create_bd_pin -dir I -type clk m_axi_s2mm_aclk

  # Create instance: axi_vdma_1, and set properties
  set axi_vdma_1 [ create_bd_cell -type ip -vlnv xilinx.com:ip:axi_vdma:6.3 axi_vdma_1 ]
  set_property -dict [list \
    CONFIG.c_include_mm2s {0} \
    CONFIG.c_m_axi_s2mm_data_width {32} \
    CONFIG.c_num_fstores {2} \
    CONFIG.c_s2mm_linebuffer_depth {2048} \
  ] $axi_vdma_1


  # Create instance: img2axis_v4_0, and set properties
  set img2axis_v4_0 [ create_bd_cell -type ip -vlnv xilinx.com:hls:img2axis_v4:1.0 img2axis_v4_0 ]

  # Create instance: isolde_resizer_v5_0, and set properties
  set isolde_resizer_v5_0 [ create_bd_cell -type ip -vlnv xilinx.com:hls:isolde_resizer_v5:1.0 isolde_resizer_v5_0 ]

  # Create interface connections
  connect_bd_intf_net -intf_net Conn1 [get_bd_intf_pins M_AXI_S2MM] [get_bd_intf_pins axi_vdma_1/M_AXI_S2MM]
  connect_bd_intf_net -intf_net Conn2 [get_bd_intf_pins S_AXI_LITE] [get_bd_intf_pins axi_vdma_1/S_AXI_LITE]
  connect_bd_intf_net -intf_net Conn3 [get_bd_intf_pins s_axi_cfg_port] [get_bd_intf_pins img2axis_v4_0/s_axi_cfg_port]
  connect_bd_intf_net -intf_net img2axis_v4_0_m_axi_data_mem [get_bd_intf_pins m_axi_data_mem] [get_bd_intf_pins img2axis_v4_0/m_axi_data_mem]
  connect_bd_intf_net -intf_net img2axis_v4_0_stream_o [get_bd_intf_pins img2axis_v4_0/stream_o] [get_bd_intf_pins isolde_resizer_v5_0/stream_i]
  connect_bd_intf_net -intf_net isolde_resizer_v5_0_stream_o [get_bd_intf_pins axi_vdma_1/S_AXIS_S2MM] [get_bd_intf_pins isolde_resizer_v5_0/stream_o]

  # Create port connections
  connect_bd_net -net microblaze_0_Clk  [get_bd_pins m_axi_s2mm_aclk] \
  [get_bd_pins axi_vdma_1/m_axi_s2mm_aclk] \
  [get_bd_pins axi_vdma_1/s_axi_lite_aclk] \
  [get_bd_pins axi_vdma_1/s_axis_s2mm_aclk] \
  [get_bd_pins img2axis_v4_0/ap_clk] \
  [get_bd_pins isolde_resizer_v5_0/ap_clk]
  connect_bd_net -net rst_clk_wiz_1_100M_peripheral_aresetn  [get_bd_pins axi_resetn] \
  [get_bd_pins axi_vdma_1/axi_resetn] \
  [get_bd_pins img2axis_v4_0/ap_rst_n] \
  [get_bd_pins isolde_resizer_v5_0/ap_rst_n]

  # Restore current instance
  current_bd_instance $oldCurInst
}
  
# Hierarchical cell: CAM_Subsystem
proc create_hier_cell_CAM_Subsystem { parentCell nameHier } {

  variable script_folder

  if { $parentCell eq "" || $nameHier eq "" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2092 -severity "ERROR" "create_hier_cell_CAM_Subsystem() - Empty argument(s)!"}
     return
  }

  # Get object for parentCell
  set parentObj [get_bd_cells $parentCell]
  if { $parentObj == "" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2090 -severity "ERROR" "Unable to find parent cell <$parentCell>!"}
     return
  }

  # Make sure parentObj is hier blk
  set parentType [get_property TYPE $parentObj]
  if { $parentType ne "hier" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2091 -severity "ERROR" "Parent <$parentObj> has TYPE = <$parentType>. Expected to be <hier>."}
     return
  }

  # Save current instance; Restore later
  set oldCurInst [current_bd_instance .]

  # Set parent object as current
  current_bd_instance $parentObj

  # Create cell and set as current instance
  set hier_obj [create_bd_cell -type hier $nameHier]
  current_bd_instance $hier_obj

  # Create interface pins
  create_bd_intf_pin -mode Master -vlnv xilinx.com:interface:gpio_rtl:1.0 GPIO_rsvd

  create_bd_intf_pin -mode Master -vlnv xilinx.com:interface:gpio_rtl:1.0 GPIO_sensor

  create_bd_intf_pin -mode Master -vlnv xilinx.com:interface:iic_rtl:1.0 IIC_sensor

  create_bd_intf_pin -mode Master -vlnv xilinx.com:interface:aximm_rtl:1.0 M10_AXI

  create_bd_intf_pin -mode Slave -vlnv xilinx.com:interface:aximm_rtl:1.0 S04_AXI

  create_bd_intf_pin -mode Master -vlnv xilinx.com:interface:ddr4_rtl:1.0 ddr4_sdram_c1_062

  create_bd_intf_pin -mode Slave -vlnv xilinx.com:interface:diff_clock_rtl:1.0 default_250mhz_clk1_0

  create_bd_intf_pin -mode Master -vlnv xilinx.com:interface:gpio_rtl:1.0 led_8bits

  create_bd_intf_pin -mode Slave -vlnv xilinx.com:interface:mipi_phy_rtl:1.0 mipi_phy_if_0

  create_bd_intf_pin -mode Master -vlnv xilinx.com:interface:uart_rtl:1.0 rs232_uart


  # Create pins
  create_bd_pin -dir I bg0_pin0_nc_0
  create_bd_pin -dir I bg2_pin0_nc_0
  create_bd_pin -dir O -type clk clk_out2
  create_bd_pin -dir O -from 0 -to 0 -type rst peripheral_aresetn
  create_bd_pin -dir I -type rst reset
  create_bd_pin -dir O -type clk slowest_sync_clk1
  create_bd_pin -dir I -from 0 -to 0 In3

  # Create instance: Clock_Reset
  create_hier_cell_Clock_Reset $hier_obj Clock_Reset

  # Create instance: MIPI_Pipeline
  create_hier_cell_MIPI_Pipeline $hier_obj MIPI_Pipeline

  # Create instance: axi_gpio_0, and set properties
  set axi_gpio_0 [ create_bd_cell -type ip -vlnv xilinx.com:ip:axi_gpio:2.0 axi_gpio_0 ]
  set_property -dict [list \
    CONFIG.GPIO_BOARD_INTERFACE {led_8bits} \
    CONFIG.USE_BOARD_FLOW {true} \
  ] $axi_gpio_0


  # Create instance: axi_uartlite_0, and set properties
  set axi_uartlite_0 [ create_bd_cell -type ip -vlnv xilinx.com:ip:axi_uartlite:2.0 axi_uartlite_0 ]
  set_property -dict [list \
    CONFIG.C_BAUDRATE {115200} \
    CONFIG.UARTLITE_BOARD_INTERFACE {rs232_uart} \
    CONFIG.USE_BOARD_FLOW {true} \
  ] $axi_uartlite_0


  # Create instance: ddr4_0, and set properties
  set ddr4_0 [ create_bd_cell -type ip -vlnv xilinx.com:ip:ddr4:2.2 ddr4_0 ]
  set_property -dict [list \
    CONFIG.C0_CLOCK_BOARD_INTERFACE {default_250mhz_clk1} \
    CONFIG.C0_DDR4_BOARD_INTERFACE {ddr4_sdram_c1_062} \
    CONFIG.RESET_BOARD_INTERFACE {reset} \
  ] $ddr4_0


  # Create instance: mdm_1, and set properties
  set mdm_1 [ create_bd_cell -type ip -vlnv xilinx.com:ip:mdm:3.2 mdm_1 ]

  # Create instance: microblaze_0, and set properties
  set microblaze_0 [ create_bd_cell -type ip -vlnv xilinx.com:ip:microblaze:11.0 microblaze_0 ]
  set_property -dict [list \
    CONFIG.C_ADDR_TAG_BITS {15} \
    CONFIG.C_CACHE_BYTE_SIZE {65536} \
    CONFIG.C_DCACHE_ADDR_TAG {15} \
    CONFIG.C_DCACHE_BYTE_SIZE {65536} \
    CONFIG.C_DEBUG_ENABLED {1} \
    CONFIG.C_D_AXI {1} \
    CONFIG.C_D_LMB {1} \
    CONFIG.C_ENABLE_CONVERSION {0} \
    CONFIG.C_I_LMB {1} \
    CONFIG.C_USE_DCACHE {1} \
    CONFIG.C_USE_ICACHE {1} \
  ] $microblaze_0


  # Create instance: microblaze_0_axi_intc, and set properties
  set microblaze_0_axi_intc [ create_bd_cell -type ip -vlnv xilinx.com:ip:axi_intc:4.1 microblaze_0_axi_intc ]
  set_property CONFIG.C_HAS_FAST {1} $microblaze_0_axi_intc


  # Create instance: microblaze_0_axi_periph, and set properties
  set microblaze_0_axi_periph [ create_bd_cell -type ip -vlnv xilinx.com:ip:axi_interconnect:2.1 microblaze_0_axi_periph ]
  set_property -dict [list \
    CONFIG.NUM_MI {11} \
    CONFIG.NUM_SI {5} \
  ] $microblaze_0_axi_periph


  # Create instance: microblaze_0_local_memory
  create_hier_cell_microblaze_0_local_memory $hier_obj microblaze_0_local_memory

  # Create instance: microblaze_0_xlconcat, and set properties
  set microblaze_0_xlconcat [ create_bd_cell -type ip -vlnv xilinx.com:ip:xlconcat:2.1 microblaze_0_xlconcat ]
  set_property CONFIG.NUM_PORTS {4} $microblaze_0_xlconcat


  # Create interface connections
  connect_bd_intf_net -intf_net Conn1 [get_bd_intf_pins M10_AXI] [get_bd_intf_pins microblaze_0_axi_periph/M10_AXI]
  connect_bd_intf_net -intf_net S04_AXI_1 [get_bd_intf_pins S04_AXI] [get_bd_intf_pins microblaze_0_axi_periph/S04_AXI]
  connect_bd_intf_net -intf_net axi_gpio_0_GPIO [get_bd_intf_pins led_8bits] [get_bd_intf_pins axi_gpio_0/GPIO]
  connect_bd_intf_net -intf_net axi_gpio_2_GPIO [get_bd_intf_pins GPIO_rsvd] [get_bd_intf_pins MIPI_Pipeline/GPIO_rsvd]
  connect_bd_intf_net -intf_net axi_iic_0_IIC [get_bd_intf_pins IIC_sensor] [get_bd_intf_pins MIPI_Pipeline/IIC_sensor]
  connect_bd_intf_net -intf_net axi_uartlite_0_UART [get_bd_intf_pins rs232_uart] [get_bd_intf_pins axi_uartlite_0/UART]
  connect_bd_intf_net -intf_net axi_vdma_0_M_AXI_S2MM [get_bd_intf_pins MIPI_Pipeline/M_AXI_S2MM] [get_bd_intf_pins microblaze_0_axi_periph/S03_AXI]
  connect_bd_intf_net -intf_net ddr4_0_C0_DDR4 [get_bd_intf_pins ddr4_sdram_c1_062] [get_bd_intf_pins ddr4_0/C0_DDR4]
  connect_bd_intf_net -intf_net default_250mhz_clk1_0_1 [get_bd_intf_pins default_250mhz_clk1_0] [get_bd_intf_pins ddr4_0/C0_SYS_CLK]
  connect_bd_intf_net -intf_net microblaze_0_M_AXI_DC [get_bd_intf_pins microblaze_0/M_AXI_DC] [get_bd_intf_pins microblaze_0_axi_periph/S01_AXI]
  connect_bd_intf_net -intf_net microblaze_0_M_AXI_DP [get_bd_intf_pins microblaze_0/M_AXI_DP] [get_bd_intf_pins microblaze_0_axi_periph/S00_AXI]
  connect_bd_intf_net -intf_net microblaze_0_M_AXI_IC [get_bd_intf_pins microblaze_0/M_AXI_IC] [get_bd_intf_pins microblaze_0_axi_periph/S02_AXI]
  connect_bd_intf_net -intf_net microblaze_0_axi_periph_M01_AXI [get_bd_intf_pins axi_gpio_0/S_AXI] [get_bd_intf_pins microblaze_0_axi_periph/M01_AXI]
  connect_bd_intf_net -intf_net microblaze_0_axi_periph_M02_AXI [get_bd_intf_pins MIPI_Pipeline/S_AXI2] [get_bd_intf_pins microblaze_0_axi_periph/M02_AXI]
  connect_bd_intf_net -intf_net microblaze_0_axi_periph_M03_AXI [get_bd_intf_pins MIPI_Pipeline/S_AXI1] [get_bd_intf_pins microblaze_0_axi_periph/M03_AXI]
  connect_bd_intf_net -intf_net microblaze_0_axi_periph_M04_AXI [get_bd_intf_pins MIPI_Pipeline/S_AXI] [get_bd_intf_pins microblaze_0_axi_periph/M04_AXI]
  connect_bd_intf_net -intf_net microblaze_0_axi_periph_M05_AXI [get_bd_intf_pins axi_uartlite_0/S_AXI] [get_bd_intf_pins microblaze_0_axi_periph/M05_AXI]
  connect_bd_intf_net -intf_net microblaze_0_axi_periph_M06_AXI [get_bd_intf_pins ddr4_0/C0_DDR4_S_AXI] [get_bd_intf_pins microblaze_0_axi_periph/M06_AXI]
  connect_bd_intf_net -intf_net microblaze_0_axi_periph_M07_AXI [get_bd_intf_pins MIPI_Pipeline/S_AXI_LITE] [get_bd_intf_pins microblaze_0_axi_periph/M07_AXI]
  connect_bd_intf_net -intf_net microblaze_0_axi_periph_M08_AXI [get_bd_intf_pins MIPI_Pipeline/csirxss_s_axi] [get_bd_intf_pins microblaze_0_axi_periph/M08_AXI]
  connect_bd_intf_net -intf_net microblaze_0_axi_periph_M09_AXI [get_bd_intf_pins MIPI_Pipeline/s_axi_CTRL] [get_bd_intf_pins microblaze_0_axi_periph/M09_AXI]
  connect_bd_intf_net -intf_net microblaze_0_debug [get_bd_intf_pins mdm_1/MBDEBUG_0] [get_bd_intf_pins microblaze_0/DEBUG]
  connect_bd_intf_net -intf_net microblaze_0_dlmb_1 [get_bd_intf_pins microblaze_0/DLMB] [get_bd_intf_pins microblaze_0_local_memory/DLMB]
  connect_bd_intf_net -intf_net microblaze_0_ilmb_1 [get_bd_intf_pins microblaze_0/ILMB] [get_bd_intf_pins microblaze_0_local_memory/ILMB]
  connect_bd_intf_net -intf_net microblaze_0_intc_axi [get_bd_intf_pins microblaze_0_axi_intc/s_axi] [get_bd_intf_pins microblaze_0_axi_periph/M00_AXI]
  connect_bd_intf_net -intf_net microblaze_0_interrupt [get_bd_intf_pins microblaze_0/INTERRUPT] [get_bd_intf_pins microblaze_0_axi_intc/interrupt]
  connect_bd_intf_net -intf_net mipi_phy_if_0_1 [get_bd_intf_pins mipi_phy_if_0] [get_bd_intf_pins MIPI_Pipeline/mipi_phy_if_0]

  # Create port connections
  connect_bd_net -net In3_1  [get_bd_pins In3] \
  [get_bd_pins microblaze_0_xlconcat/In3]
  connect_bd_net -net MIPI_Pipeline_int_o  [get_bd_pins MIPI_Pipeline/int_o] \
  [get_bd_pins microblaze_0_xlconcat/In2]
  connect_bd_net -net axi_iic_0_iic2intc_irpt  [get_bd_pins MIPI_Pipeline/iic2intc_irpt] \
  [get_bd_pins microblaze_0_xlconcat/In1]
  connect_bd_net -net axi_uartlite_0_interrupt  [get_bd_pins axi_uartlite_0/interrupt] \
  [get_bd_pins microblaze_0_xlconcat/In0]
  connect_bd_net -net bg0_pin0_nc_0_1  [get_bd_pins bg0_pin0_nc_0] \
  [get_bd_pins MIPI_Pipeline/bg0_pin0_nc_0]
  connect_bd_net -net bg2_pin0_nc_0_1  [get_bd_pins bg2_pin0_nc_0] \
  [get_bd_pins MIPI_Pipeline/bg2_pin0_nc_0]
  connect_bd_net -net clk_wiz_1_clk_out2  [get_bd_pins Clock_Reset/clk_out2] \
  [get_bd_pins clk_out2] \
  [get_bd_pins MIPI_Pipeline/dphy_clk_200M]
  connect_bd_net -net ddr4_0_c0_ddr4_ui_clk  [get_bd_pins ddr4_0/c0_ddr4_ui_clk] \
  [get_bd_pins Clock_Reset/slowest_sync_clk] \
  [get_bd_pins microblaze_0_axi_periph/M06_ACLK]
  connect_bd_net -net ddr4_0_c0_ddr4_ui_clk_sync_rst  [get_bd_pins ddr4_0/c0_ddr4_ui_clk_sync_rst] \
  [get_bd_pins Clock_Reset/ext_reset_in]
  connect_bd_net -net mdm_1_debug_sys_rst  [get_bd_pins mdm_1/Debug_SYS_Rst] \
  [get_bd_pins Clock_Reset/mb_debug_sys_rst]
  connect_bd_net -net microblaze_0_Clk  [get_bd_pins Clock_Reset/slowest_sync_clk1] \
  [get_bd_pins slowest_sync_clk1] \
  [get_bd_pins MIPI_Pipeline/s_axi_aclk] \
  [get_bd_pins axi_gpio_0/s_axi_aclk] \
  [get_bd_pins axi_uartlite_0/s_axi_aclk] \
  [get_bd_pins microblaze_0/Clk] \
  [get_bd_pins microblaze_0_axi_intc/processor_clk] \
  [get_bd_pins microblaze_0_axi_intc/s_axi_aclk] \
  [get_bd_pins microblaze_0_axi_periph/ACLK] \
  [get_bd_pins microblaze_0_axi_periph/M00_ACLK] \
  [get_bd_pins microblaze_0_axi_periph/M01_ACLK] \
  [get_bd_pins microblaze_0_axi_periph/M02_ACLK] \
  [get_bd_pins microblaze_0_axi_periph/M03_ACLK] \
  [get_bd_pins microblaze_0_axi_periph/M04_ACLK] \
  [get_bd_pins microblaze_0_axi_periph/M05_ACLK] \
  [get_bd_pins microblaze_0_axi_periph/M07_ACLK] \
  [get_bd_pins microblaze_0_axi_periph/M08_ACLK] \
  [get_bd_pins microblaze_0_axi_periph/M09_ACLK] \
  [get_bd_pins microblaze_0_axi_periph/M10_ACLK] \
  [get_bd_pins microblaze_0_axi_periph/S00_ACLK] \
  [get_bd_pins microblaze_0_axi_periph/S01_ACLK] \
  [get_bd_pins microblaze_0_axi_periph/S02_ACLK] \
  [get_bd_pins microblaze_0_axi_periph/S03_ACLK] \
  [get_bd_pins microblaze_0_axi_periph/S04_ACLK] \
  [get_bd_pins microblaze_0_local_memory/LMB_Clk]
  connect_bd_net -net microblaze_0_intr  [get_bd_pins microblaze_0_xlconcat/dout] \
  [get_bd_pins microblaze_0_axi_intc/intr]
  connect_bd_net -net reset_1  [get_bd_pins reset] \
  [get_bd_pins Clock_Reset/reset] \
  [get_bd_pins ddr4_0/sys_rst]
  connect_bd_net -net rst_clk_wiz_1_100M_bus_struct_reset  [get_bd_pins Clock_Reset/bus_struct_reset] \
  [get_bd_pins microblaze_0_local_memory/SYS_Rst]
  connect_bd_net -net rst_clk_wiz_1_100M_mb_reset  [get_bd_pins Clock_Reset/mb_reset] \
  [get_bd_pins microblaze_0/Reset] \
  [get_bd_pins microblaze_0_axi_intc/processor_rst]
  connect_bd_net -net rst_clk_wiz_1_100M_peripheral_aresetn  [get_bd_pins Clock_Reset/peripheral_aresetn] \
  [get_bd_pins peripheral_aresetn] \
  [get_bd_pins MIPI_Pipeline/s_axi_aresetn] \
  [get_bd_pins axi_gpio_0/s_axi_aresetn] \
  [get_bd_pins axi_uartlite_0/s_axi_aresetn] \
  [get_bd_pins microblaze_0_axi_intc/s_axi_aresetn] \
  [get_bd_pins microblaze_0_axi_periph/ARESETN] \
  [get_bd_pins microblaze_0_axi_periph/M00_ARESETN] \
  [get_bd_pins microblaze_0_axi_periph/M01_ARESETN] \
  [get_bd_pins microblaze_0_axi_periph/M02_ARESETN] \
  [get_bd_pins microblaze_0_axi_periph/M03_ARESETN] \
  [get_bd_pins microblaze_0_axi_periph/M04_ARESETN] \
  [get_bd_pins microblaze_0_axi_periph/M05_ARESETN] \
  [get_bd_pins microblaze_0_axi_periph/M07_ARESETN] \
  [get_bd_pins microblaze_0_axi_periph/M08_ARESETN] \
  [get_bd_pins microblaze_0_axi_periph/M09_ARESETN] \
  [get_bd_pins microblaze_0_axi_periph/M10_ARESETN] \
  [get_bd_pins microblaze_0_axi_periph/S00_ARESETN] \
  [get_bd_pins microblaze_0_axi_periph/S01_ARESETN] \
  [get_bd_pins microblaze_0_axi_periph/S02_ARESETN] \
  [get_bd_pins microblaze_0_axi_periph/S03_ARESETN] \
  [get_bd_pins microblaze_0_axi_periph/S04_ARESETN]
  connect_bd_net -net rst_ddr4_0_300M_peripheral_aresetn  [get_bd_pins Clock_Reset/peripheral_aresetn1] \
  [get_bd_pins ddr4_0/c0_ddr4_aresetn] \
  [get_bd_pins microblaze_0_axi_periph/M06_ARESETN]

  # Restore current instance
  current_bd_instance $oldCurInst
}
  variable script_folder

  if { $parentCell eq "" } {
     set parentCell [get_bd_cells /]
  }

  # Get object for parentCell
  set parentObj [get_bd_cells $parentCell]
  if { $parentObj == "" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2090 -severity "ERROR" "Unable to find parent cell <$parentCell>!"}
     return
  }

  # Make sure parentObj is hier blk
  set parentType [get_property TYPE $parentObj]
  if { $parentType ne "hier" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2091 -severity "ERROR" "Parent <$parentObj> has TYPE = <$parentType>. Expected to be <hier>."}
     return
  }

  # Save current instance; Restore later
  set oldCurInst [current_bd_instance .]

  # Set parent object as current
  current_bd_instance $parentObj


  # Create interface ports
  set GPIO_rsvd [ create_bd_intf_port -mode Master -vlnv xilinx.com:interface:gpio_rtl:1.0 GPIO_rsvd ]

  set GPIO_sensor [ create_bd_intf_port -mode Master -vlnv xilinx.com:interface:gpio_rtl:1.0 GPIO_sensor ]

  set IIC_sensor [ create_bd_intf_port -mode Master -vlnv xilinx.com:interface:iic_rtl:1.0 IIC_sensor ]

  set ddr4_sdram_c1_062 [ create_bd_intf_port -mode Master -vlnv xilinx.com:interface:ddr4_rtl:1.0 ddr4_sdram_c1_062 ]

  set default_250mhz_clk1_0 [ create_bd_intf_port -mode Slave -vlnv xilinx.com:interface:diff_clock_rtl:1.0 default_250mhz_clk1_0 ]
  set_property -dict [ list \
   CONFIG.FREQ_HZ {250000000} \
   ] $default_250mhz_clk1_0

  set led_8bits [ create_bd_intf_port -mode Master -vlnv xilinx.com:interface:gpio_rtl:1.0 led_8bits ]

  set mipi_phy_if_0 [ create_bd_intf_port -mode Slave -vlnv xilinx.com:interface:mipi_phy_rtl:1.0 mipi_phy_if_0 ]

  set rs232_uart [ create_bd_intf_port -mode Master -vlnv xilinx.com:interface:uart_rtl:1.0 rs232_uart ]


  # Create ports
  set axi_c2c_selio_rx_data_in_0 [ create_bd_port -dir I -from 14 -to 0 axi_c2c_selio_rx_data_in_0 ]
  set axi_c2c_selio_rx_diff_clk_in_n_0 [ create_bd_port -dir I -type clk axi_c2c_selio_rx_diff_clk_in_n_0 ]
  set axi_c2c_selio_rx_diff_clk_in_p_0 [ create_bd_port -dir I -type clk axi_c2c_selio_rx_diff_clk_in_p_0 ]
  set axi_c2c_selio_tx_data_out_0 [ create_bd_port -dir O -from 14 -to 0 axi_c2c_selio_tx_data_out_0 ]
  set axi_c2c_selio_tx_diff_clk_out_n_0 [ create_bd_port -dir O -type clk axi_c2c_selio_tx_diff_clk_out_n_0 ]
  set axi_c2c_selio_tx_diff_clk_out_p_0 [ create_bd_port -dir O -type clk axi_c2c_selio_tx_diff_clk_out_p_0 ]
  set bg0_pin0_nc_0 [ create_bd_port -dir I bg0_pin0_nc_0 ]
  set bg2_pin0_nc_0 [ create_bd_port -dir I bg2_pin0_nc_0 ]
  set reset [ create_bd_port -dir I -type rst reset ]
  set_property -dict [ list \
   CONFIG.POLARITY {ACTIVE_HIGH} \
 ] $reset

  # Create instance: CAM_Subsystem
  create_hier_cell_CAM_Subsystem [current_bd_instance .] CAM_Subsystem

  # Create instance: Resizer_BD
  create_hier_cell_Resizer_BD [current_bd_instance .] Resizer_BD

  # Create instance: axi_chip2chip_0, and set properties
  set axi_chip2chip_0 [ create_bd_cell -type ip -vlnv xilinx.com:ip:axi_chip2chip:5.0 axi_chip2chip_0 ]
  set_property -dict [list \
    CONFIG.C_INCLUDE_AXILITE {1} \
    CONFIG.C_INTERFACE_MODE {1} \
    CONFIG.C_MASTER_FPGA {0} \
    CONFIG.C_M_AXI_ID_WIDTH {0} \
    CONFIG.C_M_AXI_WUSER_WIDTH {0} \
    CONFIG.C_USE_DIFF_CLK {true} \
  ] $axi_chip2chip_0


  # Create instance: axi_interconnect_0, and set properties
  set axi_interconnect_0 [ create_bd_cell -type ip -vlnv xilinx.com:ip:axi_interconnect:2.1 axi_interconnect_0 ]
  set_property -dict [list \
    CONFIG.NUM_MI {2} \
    CONFIG.NUM_SI {2} \
  ] $axi_interconnect_0


  # Create instance: axi_protocol_convert_0, and set properties
  set axi_protocol_convert_0 [ create_bd_cell -type ip -vlnv xilinx.com:ip:axi_protocol_converter:2.1 axi_protocol_convert_0 ]
  set_property -dict [list \
    CONFIG.ADDR_WIDTH {32} \
    CONFIG.DATA_WIDTH {32} \
    CONFIG.ID_WIDTH {0} \
    CONFIG.MI_PROTOCOL {AXI4LITE} \
    CONFIG.READ_WRITE_MODE {WRITE_ONLY} \
    CONFIG.SI_PROTOCOL {AXI4} \
  ] $axi_protocol_convert_0


  # Create instance: vio_0, and set properties
  set vio_0 [ create_bd_cell -type ip -vlnv xilinx.com:ip:vio:3.0 vio_0 ]
  set_property CONFIG.C_NUM_PROBE_IN {0} $vio_0


  # Create interface connections
  connect_bd_intf_net -intf_net Resizer_BD_M_AXI_S2MM [get_bd_intf_pins Resizer_BD/M_AXI_S2MM] [get_bd_intf_pins axi_protocol_convert_0/S_AXI]
  connect_bd_intf_net -intf_net S01_AXI_1 [get_bd_intf_pins CAM_Subsystem/M10_AXI] [get_bd_intf_pins axi_interconnect_0/S01_AXI]
  connect_bd_intf_net -intf_net S04_AXI_1 [get_bd_intf_pins CAM_Subsystem/S04_AXI] [get_bd_intf_pins Resizer_BD/m_axi_data_mem]
  connect_bd_intf_net -intf_net axi_chip2chip_0_m_axi [get_bd_intf_pins axi_chip2chip_0/m_axi] [get_bd_intf_pins axi_interconnect_0/S00_AXI]
  connect_bd_intf_net -intf_net axi_gpio_0_GPIO [get_bd_intf_ports led_8bits] [get_bd_intf_pins CAM_Subsystem/led_8bits]
  connect_bd_intf_net -intf_net axi_gpio_1_GPIO [get_bd_intf_ports GPIO_sensor] [get_bd_intf_pins CAM_Subsystem/GPIO_sensor]
  connect_bd_intf_net -intf_net axi_gpio_2_GPIO [get_bd_intf_ports GPIO_rsvd] [get_bd_intf_pins CAM_Subsystem/GPIO_rsvd]
  connect_bd_intf_net -intf_net axi_iic_0_IIC [get_bd_intf_ports IIC_sensor] [get_bd_intf_pins CAM_Subsystem/IIC_sensor]
  connect_bd_intf_net -intf_net axi_interconnect_0_M00_AXI [get_bd_intf_pins Resizer_BD/S_AXI_LITE] [get_bd_intf_pins axi_interconnect_0/M00_AXI]
  connect_bd_intf_net -intf_net axi_interconnect_0_M01_AXI [get_bd_intf_pins Resizer_BD/s_axi_cfg_port] [get_bd_intf_pins axi_interconnect_0/M01_AXI]
  connect_bd_intf_net -intf_net axi_protocol_convert_0_M_AXI [get_bd_intf_pins axi_chip2chip_0/s_axi_lite] [get_bd_intf_pins axi_protocol_convert_0/M_AXI]
  connect_bd_intf_net -intf_net axi_uartlite_0_UART [get_bd_intf_ports rs232_uart] [get_bd_intf_pins CAM_Subsystem/rs232_uart]
  connect_bd_intf_net -intf_net ddr4_0_C0_DDR4 [get_bd_intf_ports ddr4_sdram_c1_062] [get_bd_intf_pins CAM_Subsystem/ddr4_sdram_c1_062]
  connect_bd_intf_net -intf_net default_250mhz_clk1_0_1 [get_bd_intf_ports default_250mhz_clk1_0] [get_bd_intf_pins CAM_Subsystem/default_250mhz_clk1_0]
  connect_bd_intf_net -intf_net mipi_phy_if_0_1 [get_bd_intf_ports mipi_phy_if_0] [get_bd_intf_pins CAM_Subsystem/mipi_phy_if_0]

  # Create port connections
  connect_bd_net -net CAM_Subsystem_clk_out2  [get_bd_pins CAM_Subsystem/clk_out2] \
  [get_bd_pins axi_chip2chip_0/idelay_ref_clk]
  connect_bd_net -net axi_c2c_selio_rx_data_in_0_1  [get_bd_ports axi_c2c_selio_rx_data_in_0] \
  [get_bd_pins axi_chip2chip_0/axi_c2c_selio_rx_data_in]
  connect_bd_net -net axi_c2c_selio_rx_diff_clk_in_n_0_1  [get_bd_ports axi_c2c_selio_rx_diff_clk_in_n_0] \
  [get_bd_pins axi_chip2chip_0/axi_c2c_selio_rx_diff_clk_in_n]
  connect_bd_net -net axi_c2c_selio_rx_diff_clk_in_p_0_1  [get_bd_ports axi_c2c_selio_rx_diff_clk_in_p_0] \
  [get_bd_pins axi_chip2chip_0/axi_c2c_selio_rx_diff_clk_in_p]
  connect_bd_net -net axi_chip2chip_0_axi_c2c_selio_tx_data_out  [get_bd_pins axi_chip2chip_0/axi_c2c_selio_tx_data_out] \
  [get_bd_ports axi_c2c_selio_tx_data_out_0]
  connect_bd_net -net axi_chip2chip_0_axi_c2c_selio_tx_diff_clk_out_n  [get_bd_pins axi_chip2chip_0/axi_c2c_selio_tx_diff_clk_out_n] \
  [get_bd_ports axi_c2c_selio_tx_diff_clk_out_n_0]
  connect_bd_net -net axi_chip2chip_0_axi_c2c_selio_tx_diff_clk_out_p  [get_bd_pins axi_chip2chip_0/axi_c2c_selio_tx_diff_clk_out_p] \
  [get_bd_ports axi_c2c_selio_tx_diff_clk_out_p_0]
  connect_bd_net -net bg0_pin0_nc_0_1  [get_bd_ports bg0_pin0_nc_0] \
  [get_bd_pins CAM_Subsystem/bg0_pin0_nc_0]
  connect_bd_net -net bg2_pin0_nc_0_1  [get_bd_ports bg2_pin0_nc_0] \
  [get_bd_pins CAM_Subsystem/bg2_pin0_nc_0]
  connect_bd_net -net microblaze_0_Clk  [get_bd_pins CAM_Subsystem/slowest_sync_clk1] \
  [get_bd_pins Resizer_BD/m_axi_s2mm_aclk] \
  [get_bd_pins axi_chip2chip_0/m_aclk] \
  [get_bd_pins axi_chip2chip_0/s_axi_lite_aclk] \
  [get_bd_pins axi_interconnect_0/ACLK] \
  [get_bd_pins axi_interconnect_0/M00_ACLK] \
  [get_bd_pins axi_interconnect_0/M01_ACLK] \
  [get_bd_pins axi_interconnect_0/S00_ACLK] \
  [get_bd_pins axi_interconnect_0/S01_ACLK] \
  [get_bd_pins axi_protocol_convert_0/aclk] \
  [get_bd_pins vio_0/clk]
  connect_bd_net -net reset_1  [get_bd_ports reset] \
  [get_bd_pins CAM_Subsystem/reset]
  connect_bd_net -net rst_clk_wiz_1_100M_peripheral_aresetn  [get_bd_pins CAM_Subsystem/peripheral_aresetn] \
  [get_bd_pins Resizer_BD/axi_resetn] \
  [get_bd_pins axi_chip2chip_0/m_aresetn] \
  [get_bd_pins axi_interconnect_0/ARESETN] \
  [get_bd_pins axi_interconnect_0/M00_ARESETN] \
  [get_bd_pins axi_interconnect_0/M01_ARESETN] \
  [get_bd_pins axi_interconnect_0/S00_ARESETN] \
  [get_bd_pins axi_interconnect_0/S01_ARESETN] \
  [get_bd_pins axi_protocol_convert_0/aresetn]
  connect_bd_net -net vio_0_probe_out0  [get_bd_pins vio_0/probe_out0] \
  [get_bd_pins CAM_Subsystem/In3]

  # Create address segments
  assign_bd_address -offset 0xA0010000 -range 0x00008000 -target_address_space [get_bd_addr_spaces axi_chip2chip_0/MAXI] [get_bd_addr_segs Resizer_BD/axi_vdma_1/S_AXI_LITE/Reg] -force
  assign_bd_address -offset 0xA0018000 -range 0x00008000 -target_address_space [get_bd_addr_spaces axi_chip2chip_0/MAXI] [get_bd_addr_segs Resizer_BD/img2axis_v4_0/s_axi_cfg_port/Reg] -force
  assign_bd_address -offset 0x40020000 -range 0x00010000 -target_address_space [get_bd_addr_spaces CAM_Subsystem/microblaze_0/Data] [get_bd_addr_segs CAM_Subsystem/axi_gpio_0/S_AXI/Reg] -force
  assign_bd_address -offset 0x40010000 -range 0x00010000 -target_address_space [get_bd_addr_spaces CAM_Subsystem/microblaze_0/Data] [get_bd_addr_segs CAM_Subsystem/MIPI_Pipeline/axi_gpio_2/S_AXI/Reg] -force
  assign_bd_address -offset 0x40800000 -range 0x00010000 -target_address_space [get_bd_addr_spaces CAM_Subsystem/microblaze_0/Data] [get_bd_addr_segs CAM_Subsystem/MIPI_Pipeline/axi_iic_0/S_AXI/Reg] -force
  assign_bd_address -offset 0x40600000 -range 0x00010000 -target_address_space [get_bd_addr_spaces CAM_Subsystem/microblaze_0/Data] [get_bd_addr_segs CAM_Subsystem/axi_uartlite_0/S_AXI/Reg] -force
  assign_bd_address -offset 0x44A00000 -range 0x00010000 -target_address_space [get_bd_addr_spaces CAM_Subsystem/microblaze_0/Data] [get_bd_addr_segs CAM_Subsystem/MIPI_Pipeline/axi_vdma_0/S_AXI_LITE/Reg] -force
  assign_bd_address -offset 0x44A20000 -range 0x00010000 -target_address_space [get_bd_addr_spaces CAM_Subsystem/microblaze_0/Data] [get_bd_addr_segs Resizer_BD/axi_vdma_1/S_AXI_LITE/Reg] -force
  assign_bd_address -offset 0x80000000 -range 0x80000000 -target_address_space [get_bd_addr_spaces CAM_Subsystem/microblaze_0/Data] [get_bd_addr_segs CAM_Subsystem/ddr4_0/C0_DDR4_MEMORY_MAP/C0_DDR4_ADDRESS_BLOCK] -force
  assign_bd_address -offset 0x00000000 -range 0x00002000 -target_address_space [get_bd_addr_spaces CAM_Subsystem/microblaze_0/Data] [get_bd_addr_segs CAM_Subsystem/microblaze_0_local_memory/dlmb_bram_if_cntlr/SLMB/Mem] -force
  assign_bd_address -offset 0x00010000 -range 0x00010000 -target_address_space [get_bd_addr_spaces CAM_Subsystem/microblaze_0/Data] [get_bd_addr_segs Resizer_BD/img2axis_v4_0/s_axi_cfg_port/Reg] -force
  assign_bd_address -offset 0x41200000 -range 0x00010000 -target_address_space [get_bd_addr_spaces CAM_Subsystem/microblaze_0/Data] [get_bd_addr_segs CAM_Subsystem/microblaze_0_axi_intc/S_AXI/Reg] -force
  assign_bd_address -offset 0x00002000 -range 0x00002000 -target_address_space [get_bd_addr_spaces CAM_Subsystem/microblaze_0/Data] [get_bd_addr_segs CAM_Subsystem/MIPI_Pipeline/mipi_csi2_rx_subsyst_0/csirxss_s_axi/Reg] -force
  assign_bd_address -offset 0x40020000 -range 0x00010000 -target_address_space [get_bd_addr_spaces CAM_Subsystem/microblaze_0/Instruction] [get_bd_addr_segs CAM_Subsystem/axi_gpio_0/S_AXI/Reg] -force
  assign_bd_address -offset 0x40010000 -range 0x00010000 -target_address_space [get_bd_addr_spaces CAM_Subsystem/microblaze_0/Instruction] [get_bd_addr_segs CAM_Subsystem/MIPI_Pipeline/axi_gpio_2/S_AXI/Reg] -force
  assign_bd_address -offset 0x40800000 -range 0x00010000 -target_address_space [get_bd_addr_spaces CAM_Subsystem/microblaze_0/Instruction] [get_bd_addr_segs CAM_Subsystem/MIPI_Pipeline/axi_iic_0/S_AXI/Reg] -force
  assign_bd_address -offset 0x40600000 -range 0x00010000 -target_address_space [get_bd_addr_spaces CAM_Subsystem/microblaze_0/Instruction] [get_bd_addr_segs CAM_Subsystem/axi_uartlite_0/S_AXI/Reg] -force
  assign_bd_address -offset 0x44A00000 -range 0x00010000 -target_address_space [get_bd_addr_spaces CAM_Subsystem/microblaze_0/Instruction] [get_bd_addr_segs CAM_Subsystem/MIPI_Pipeline/axi_vdma_0/S_AXI_LITE/Reg] -force
  assign_bd_address -offset 0x44A20000 -range 0x00010000 -target_address_space [get_bd_addr_spaces CAM_Subsystem/microblaze_0/Instruction] [get_bd_addr_segs Resizer_BD/axi_vdma_1/S_AXI_LITE/Reg] -force
  assign_bd_address -offset 0x80000000 -range 0x80000000 -target_address_space [get_bd_addr_spaces CAM_Subsystem/microblaze_0/Instruction] [get_bd_addr_segs CAM_Subsystem/ddr4_0/C0_DDR4_MEMORY_MAP/C0_DDR4_ADDRESS_BLOCK] -force
  assign_bd_address -offset 0x00000000 -range 0x00002000 -target_address_space [get_bd_addr_spaces CAM_Subsystem/microblaze_0/Instruction] [get_bd_addr_segs CAM_Subsystem/microblaze_0_local_memory/ilmb_bram_if_cntlr/SLMB/Mem] -force
  assign_bd_address -offset 0x00010000 -range 0x00010000 -target_address_space [get_bd_addr_spaces CAM_Subsystem/microblaze_0/Instruction] [get_bd_addr_segs Resizer_BD/img2axis_v4_0/s_axi_cfg_port/Reg] -force
  assign_bd_address -offset 0x41200000 -range 0x00010000 -target_address_space [get_bd_addr_spaces CAM_Subsystem/microblaze_0/Instruction] [get_bd_addr_segs CAM_Subsystem/microblaze_0_axi_intc/S_AXI/Reg] -force
  assign_bd_address -offset 0x00002000 -range 0x00002000 -target_address_space [get_bd_addr_spaces CAM_Subsystem/microblaze_0/Instruction] [get_bd_addr_segs CAM_Subsystem/MIPI_Pipeline/mipi_csi2_rx_subsyst_0/csirxss_s_axi/Reg] -force
  assign_bd_address -offset 0x00000000 -range 0x80000000 -target_address_space [get_bd_addr_spaces Resizer_BD/axi_vdma_1/Data_S2MM] [get_bd_addr_segs axi_chip2chip_0/s_axi_lite/Reg] -force
  assign_bd_address -offset 0x80000000 -range 0x80000000 -target_address_space [get_bd_addr_spaces Resizer_BD/img2axis_v4_0/Data_m_axi_data_mem] [get_bd_addr_segs CAM_Subsystem/ddr4_0/C0_DDR4_MEMORY_MAP/C0_DDR4_ADDRESS_BLOCK] -force
  assign_bd_address -offset 0x80000000 -range 0x80000000 -target_address_space [get_bd_addr_spaces CAM_Subsystem/MIPI_Pipeline/axi_vdma_0/Data_S2MM] [get_bd_addr_segs CAM_Subsystem/ddr4_0/C0_DDR4_MEMORY_MAP/C0_DDR4_ADDRESS_BLOCK] -force

  # Exclude Address Segments
  exclude_bd_addr_seg -offset 0x40020000 -range 0x00010000 -target_address_space [get_bd_addr_spaces CAM_Subsystem/MIPI_Pipeline/axi_vdma_0/Data_S2MM] [get_bd_addr_segs CAM_Subsystem/axi_gpio_0/S_AXI/Reg]
  exclude_bd_addr_seg -offset 0x40010000 -range 0x00010000 -target_address_space [get_bd_addr_spaces CAM_Subsystem/MIPI_Pipeline/axi_vdma_0/Data_S2MM] [get_bd_addr_segs CAM_Subsystem/MIPI_Pipeline/axi_gpio_2/S_AXI/Reg]
  exclude_bd_addr_seg -offset 0x40800000 -range 0x00010000 -target_address_space [get_bd_addr_spaces CAM_Subsystem/MIPI_Pipeline/axi_vdma_0/Data_S2MM] [get_bd_addr_segs CAM_Subsystem/MIPI_Pipeline/axi_iic_0/S_AXI/Reg]
  exclude_bd_addr_seg -offset 0x40600000 -range 0x00010000 -target_address_space [get_bd_addr_spaces CAM_Subsystem/MIPI_Pipeline/axi_vdma_0/Data_S2MM] [get_bd_addr_segs CAM_Subsystem/axi_uartlite_0/S_AXI/Reg]
  exclude_bd_addr_seg -offset 0x44A00000 -range 0x00010000 -target_address_space [get_bd_addr_spaces CAM_Subsystem/MIPI_Pipeline/axi_vdma_0/Data_S2MM] [get_bd_addr_segs CAM_Subsystem/MIPI_Pipeline/axi_vdma_0/S_AXI_LITE/Reg]
  exclude_bd_addr_seg -offset 0x44A20000 -range 0x00010000 -target_address_space [get_bd_addr_spaces CAM_Subsystem/MIPI_Pipeline/axi_vdma_0/Data_S2MM] [get_bd_addr_segs Resizer_BD/axi_vdma_1/S_AXI_LITE/Reg]
  exclude_bd_addr_seg -offset 0x00010000 -range 0x00010000 -target_address_space [get_bd_addr_spaces CAM_Subsystem/MIPI_Pipeline/axi_vdma_0/Data_S2MM] [get_bd_addr_segs Resizer_BD/img2axis_v4_0/s_axi_cfg_port/Reg]
  exclude_bd_addr_seg -offset 0x41200000 -range 0x00010000 -target_address_space [get_bd_addr_spaces CAM_Subsystem/MIPI_Pipeline/axi_vdma_0/Data_S2MM] [get_bd_addr_segs CAM_Subsystem/microblaze_0_axi_intc/S_AXI/Reg]
  exclude_bd_addr_seg -offset 0x00002000 -range 0x00002000 -target_address_space [get_bd_addr_spaces CAM_Subsystem/MIPI_Pipeline/axi_vdma_0/Data_S2MM] [get_bd_addr_segs CAM_Subsystem/MIPI_Pipeline/mipi_csi2_rx_subsyst_0/csirxss_s_axi/Reg]
  exclude_bd_addr_seg -offset 0x40020000 -range 0x00010000 -target_address_space [get_bd_addr_spaces Resizer_BD/img2axis_v4_0/Data_m_axi_data_mem] [get_bd_addr_segs CAM_Subsystem/axi_gpio_0/S_AXI/Reg]
  exclude_bd_addr_seg -offset 0x40010000 -range 0x00010000 -target_address_space [get_bd_addr_spaces Resizer_BD/img2axis_v4_0/Data_m_axi_data_mem] [get_bd_addr_segs CAM_Subsystem/MIPI_Pipeline/axi_gpio_2/S_AXI/Reg]
  exclude_bd_addr_seg -offset 0x40800000 -range 0x00010000 -target_address_space [get_bd_addr_spaces Resizer_BD/img2axis_v4_0/Data_m_axi_data_mem] [get_bd_addr_segs CAM_Subsystem/MIPI_Pipeline/axi_iic_0/S_AXI/Reg]
  exclude_bd_addr_seg -offset 0x40600000 -range 0x00010000 -target_address_space [get_bd_addr_spaces Resizer_BD/img2axis_v4_0/Data_m_axi_data_mem] [get_bd_addr_segs CAM_Subsystem/axi_uartlite_0/S_AXI/Reg]
  exclude_bd_addr_seg -offset 0x44A00000 -range 0x00010000 -target_address_space [get_bd_addr_spaces Resizer_BD/img2axis_v4_0/Data_m_axi_data_mem] [get_bd_addr_segs CAM_Subsystem/MIPI_Pipeline/axi_vdma_0/S_AXI_LITE/Reg]
  exclude_bd_addr_seg -offset 0x44A20000 -range 0x00010000 -target_address_space [get_bd_addr_spaces Resizer_BD/img2axis_v4_0/Data_m_axi_data_mem] [get_bd_addr_segs Resizer_BD/axi_vdma_1/S_AXI_LITE/Reg]
  exclude_bd_addr_seg -offset 0x00010000 -range 0x00010000 -target_address_space [get_bd_addr_spaces Resizer_BD/img2axis_v4_0/Data_m_axi_data_mem] [get_bd_addr_segs Resizer_BD/img2axis_v4_0/s_axi_cfg_port/Reg]
  exclude_bd_addr_seg -offset 0x41200000 -range 0x00010000 -target_address_space [get_bd_addr_spaces Resizer_BD/img2axis_v4_0/Data_m_axi_data_mem] [get_bd_addr_segs CAM_Subsystem/microblaze_0_axi_intc/S_AXI/Reg]
  exclude_bd_addr_seg -offset 0x00002000 -range 0x00002000 -target_address_space [get_bd_addr_spaces Resizer_BD/img2axis_v4_0/Data_m_axi_data_mem] [get_bd_addr_segs CAM_Subsystem/MIPI_Pipeline/mipi_csi2_rx_subsyst_0/csirxss_s_axi/Reg]

  # Perform GUI Layout
  regenerate_bd_layout -layout_string {
   "ActiveEmotionalView":"Default View",
   "Default View_ScaleFactor":"1.0",
   "Default View_TopLeft":"1296,189",
   "ExpandedHierarchyInLayout":"/CAM_Subsystem|/CAM_Subsystem/MIPI_Pipeline",
   "guistr":"# # String gsaved with Nlview 7.8.0 2024-04-26 e1825d835c VDI=44 GEI=38 GUI=JA:21.0 TLS
#  -string -flagsOSRD
preplace port GPIO_rsvd -pg 1 -lvl 4 -x 4470 -y 620 -defaultsOSRD
preplace port GPIO_sensor -pg 1 -lvl 4 -x 4470 -y 640 -defaultsOSRD
preplace port IIC_sensor -pg 1 -lvl 4 -x 4470 -y 660 -defaultsOSRD
preplace port ddr4_sdram_c1_062 -pg 1 -lvl 4 -x 4470 -y 700 -defaultsOSRD
preplace port default_250mhz_clk1_0 -pg 1 -lvl 0 -x 0 -y 670 -defaultsOSRD
preplace port led_8bits -pg 1 -lvl 4 -x 4470 -y 720 -defaultsOSRD
preplace port mipi_phy_if_0 -pg 1 -lvl 0 -x 0 -y 690 -defaultsOSRD
preplace port rs232_uart -pg 1 -lvl 4 -x 4470 -y 740 -defaultsOSRD
preplace port port-id_axi_c2c_selio_rx_diff_clk_in_n_0 -pg 1 -lvl 0 -x 0 -y 550 -defaultsOSRD
preplace port port-id_axi_c2c_selio_rx_diff_clk_in_p_0 -pg 1 -lvl 0 -x 0 -y 530 -defaultsOSRD
preplace port port-id_axi_c2c_selio_tx_diff_clk_out_n_0 -pg 1 -lvl 4 -x 4470 -y 320 -defaultsOSRD
preplace port port-id_axi_c2c_selio_tx_diff_clk_out_p_0 -pg 1 -lvl 4 -x 4470 -y 300 -defaultsOSRD
preplace port port-id_bg0_pin0_nc_0 -pg 1 -lvl 0 -x 0 -y 710 -defaultsOSRD
preplace port port-id_bg2_pin0_nc_0 -pg 1 -lvl 0 -x 0 -y 730 -defaultsOSRD
preplace port port-id_reset -pg 1 -lvl 0 -x 0 -y 750 -defaultsOSRD
preplace portBus axi_c2c_selio_rx_data_in_0 -pg 1 -lvl 0 -x 0 -y 510 -defaultsOSRD
preplace portBus axi_c2c_selio_tx_data_out_0 -pg 1 -lvl 4 -x 4470 -y 280 -defaultsOSRD
preplace inst CAM_Subsystem -pg 1 -lvl 3 -x 1120 -y 712 -defaultsOSRD
preplace inst Resizer_BD -pg 1 -lvl 2 -x 540 -y 350 -defaultsOSRD
preplace inst axi_chip2chip_0 -pg 1 -lvl 3 -x 1120 -y 300 -defaultsOSRD
preplace inst axi_interconnect_0 -pg 1 -lvl 1 -x 200 -y 330 -defaultsOSRD
preplace inst axi_protocol_convert_0 -pg 1 -lvl 2 -x 540 -y 80 -defaultsOSRD
preplace inst vio_0 -pg 1 -lvl 2 -x 540 -y 810 -defaultsOSRD
preplace inst CAM_Subsystem|Clock_Reset -pg 1 -lvl 4 -x 2350 -y 1862 -defaultsOSRD
preplace inst CAM_Subsystem|MIPI_Pipeline -pg 1 -lvl 5 -x 2960 -y 1134 -defaultsOSRD
preplace inst CAM_Subsystem|axi_gpio_0 -pg 1 -lvl 5 -x 2960 -y 2286 -defaultsOSRD
preplace inst CAM_Subsystem|axi_uartlite_0 -pg 1 -lvl 5 -x 2960 -y 1876 -defaultsOSRD
preplace inst CAM_Subsystem|ddr4_0 -pg 1 -lvl 5 -x 2960 -y 2106 -defaultsOSRD
preplace inst CAM_Subsystem|mdm_1 -pg 1 -lvl 2 -x 1410 -y 1812 -defaultsOSRD
preplace inst CAM_Subsystem|microblaze_0 -pg 1 -lvl 3 -x 1800 -y 1582 -defaultsOSRD
preplace inst CAM_Subsystem|microblaze_0_axi_intc -pg 1 -lvl 2 -x 1410 -y 1562 -defaultsOSRD
preplace inst CAM_Subsystem|microblaze_0_axi_periph -pg 1 -lvl 4 -x 2350 -y 1042 -defaultsOSRD
preplace inst CAM_Subsystem|microblaze_0_local_memory -pg 1 -lvl 4 -x 2350 -y 1572 -defaultsOSRD
preplace inst CAM_Subsystem|microblaze_0_xlconcat -pg 1 -lvl 1 -x 1120 -y 1622 -defaultsOSRD
preplace inst CAM_Subsystem|MIPI_Pipeline|axi_gpio_2 -pg 1 -lvl 3 -x 3750 -y 1074 -defaultsOSRD
preplace inst CAM_Subsystem|MIPI_Pipeline|axi_iic_0 -pg 1 -lvl 3 -x 3750 -y 1214 -defaultsOSRD
preplace inst CAM_Subsystem|MIPI_Pipeline|axi_vdma_0 -pg 1 -lvl 3 -x 3750 -y 1494 -defaultsOSRD
preplace inst CAM_Subsystem|MIPI_Pipeline|mipi_csi2_rx_subsyst_0 -pg 1 -lvl 1 -x 3070 -y 1574 -defaultsOSRD
preplace inst CAM_Subsystem|MIPI_Pipeline|int_enable_0 -pg 1 -lvl 2 -x 3350 -y 1304 -defaultsOSRD
preplace inst CAM_Subsystem|MIPI_Pipeline|axi_gpio_0 -pg 1 -lvl 1 -x 3070 -y 1304 -defaultsOSRD
preplace netloc CAM_Subsystem_clk_out2 1 2 2 810 540 4390
preplace netloc axi_c2c_selio_rx_data_in_0_1 1 0 3 20J 520 NJ 520 730J
preplace netloc axi_c2c_selio_rx_diff_clk_in_n_0_1 1 0 3 20J 540 NJ 540 790J
preplace netloc axi_c2c_selio_rx_diff_clk_in_p_0_1 1 0 3 NJ 530 NJ 530 770J
preplace netloc axi_chip2chip_0_axi_c2c_selio_tx_data_out 1 3 1 NJ 280
preplace netloc axi_chip2chip_0_axi_c2c_selio_tx_diff_clk_out_n 1 3 1 NJ 320
preplace netloc axi_chip2chip_0_axi_c2c_selio_tx_diff_clk_out_p 1 3 1 NJ 300
preplace netloc bg0_pin0_nc_0_1 1 0 3 NJ 710 NJ 710 740J
preplace netloc bg2_pin0_nc_0_1 1 0 3 NJ 730 NJ 730 730J
preplace netloc microblaze_0_Clk 1 0 4 40 510 350 430 750 2394 4370
preplace netloc reset_1 1 0 3 NJ 750 NJ 750 720J
preplace netloc rst_clk_wiz_1_100M_peripheral_aresetn 1 0 4 50 500 360 440 800 560 4370
preplace netloc vio_0_probe_out0 1 2 1 710J 810n
preplace netloc Resizer_BD_M_AXI_S2MM 1 1 2 370 170 710
preplace netloc S01_AXI_1 1 0 4 30 550 NJ 550 NJ 550 4380
preplace netloc S04_AXI_1 1 2 1 780 360n
preplace netloc axi_chip2chip_0_m_axi 1 0 4 50 160 NJ 160 NJ 160 4370
preplace netloc axi_gpio_0_GPIO 1 3 1 4440J 720n
preplace netloc axi_gpio_1_GPIO 1 3 1 4410J 640n
preplace netloc axi_gpio_2_GPIO 1 3 1 4400J 620n
preplace netloc axi_iic_0_IIC 1 3 1 4420J 660n
preplace netloc axi_interconnect_0_M00_AXI 1 1 1 N 320
preplace netloc axi_interconnect_0_M01_AXI 1 1 1 N 340
preplace netloc axi_protocol_convert_0_M_AXI 1 2 1 810 80n
preplace netloc axi_uartlite_0_UART 1 3 1 4450J 740n
preplace netloc ddr4_0_C0_DDR4 1 3 1 4430J 700n
preplace netloc default_250mhz_clk1_0_1 1 0 3 NJ 670 NJ 670 770J
preplace netloc mipi_phy_if_0_1 1 0 3 NJ 690 NJ 690 760J
preplace netloc CAM_Subsystem|axi_iic_0_iic2intc_irpt 1 0 6 1000 1532 1240J 1702 NJ 1702 2090J 1672 2560J 1776 4140
preplace netloc CAM_Subsystem|axi_uartlite_0_interrupt 1 0 6 1010 1712 NJ 1712 NJ 1712 2100J 1682 2550J 1786 4130
preplace netloc CAM_Subsystem|bg0_pin0_nc_0_1 1 0 5 NJ 1742 1230J 1732 NJ 1732 2110J 1702 2650
preplace netloc CAM_Subsystem|bg2_pin0_nc_0_1 1 0 5 NJ 1762 1260J 1742 NJ 1742 2140J 1712 2660
preplace netloc CAM_Subsystem|clk_wiz_1_clk_out2 1 4 2 2670 1796 4160J
preplace netloc CAM_Subsystem|ddr4_0_c0_ddr4_ui_clk 1 3 3 2150 1982 2560J 1986 4130
preplace netloc CAM_Subsystem|ddr4_0_c0_ddr4_ui_clk_sync_rst 1 3 3 2170 1972 2580J 1976 4140
preplace netloc CAM_Subsystem|mdm_1_debug_sys_rst 1 2 2 1540 1852 NJ
preplace netloc CAM_Subsystem|microblaze_0_Clk 1 1 5 1280 1672 1560 1682 2070 1652 2610 1966 4200J
preplace netloc CAM_Subsystem|microblaze_0_intr 1 1 1 1230 1572n
preplace netloc CAM_Subsystem|reset_1 1 0 5 NJ 1892 NJ 1892 NJ 1892 2080 1992 2540J
preplace netloc CAM_Subsystem|rst_clk_wiz_1_100M_bus_struct_reset 1 3 2 2170 1722 2530
preplace netloc CAM_Subsystem|rst_clk_wiz_1_100M_mb_reset 1 1 4 1270 1682 1550 1752 NJ 1752 2540
preplace netloc CAM_Subsystem|rst_clk_wiz_1_100M_peripheral_aresetn 1 1 5 1260 1452 NJ 1452 2130 1732 2600 1956 4190J
preplace netloc CAM_Subsystem|rst_ddr4_0_300M_peripheral_aresetn 1 3 2 2160 1742 2570
preplace netloc CAM_Subsystem|In3_1 1 0 1 990 1652n
preplace netloc CAM_Subsystem|MIPI_Pipeline_int_o 1 0 6 980 1522 1250J 1692 NJ 1692 2080J 1662 2590J 1766 4130
preplace netloc CAM_Subsystem|Conn1 1 4 2 2630 962 NJ
preplace netloc CAM_Subsystem|S04_AXI_1 1 0 4 NJ 742 NJ 742 NJ 742 N
preplace netloc CAM_Subsystem|axi_gpio_0_GPIO 1 5 1 4180 1422n
preplace netloc CAM_Subsystem|axi_gpio_1_GPIO 1 5 1 N 922
preplace netloc CAM_Subsystem|axi_gpio_2_GPIO 1 5 1 4150 902n
preplace netloc CAM_Subsystem|axi_iic_0_IIC 1 5 1 4180 942n
preplace netloc CAM_Subsystem|axi_uartlite_0_UART 1 5 1 4150 1442n
preplace netloc CAM_Subsystem|axi_vdma_0_M_AXI_S2MM 1 3 3 2170 602 NJ 602 4130
preplace netloc CAM_Subsystem|ddr4_0_C0_DDR4 1 5 1 4170 1402n
preplace netloc CAM_Subsystem|default_250mhz_clk1_0_1 1 0 5 980J 1882 NJ 1882 NJ 1882 2040J 1962 2590
preplace netloc CAM_Subsystem|microblaze_0_M_AXI_DC 1 3 1 2050 682n
preplace netloc CAM_Subsystem|microblaze_0_M_AXI_DP 1 3 1 2040 662n
preplace netloc CAM_Subsystem|microblaze_0_M_AXI_IC 1 3 1 2060 702n
preplace netloc CAM_Subsystem|microblaze_0_axi_periph_M01_AXI 1 4 1 2620 962n
preplace netloc CAM_Subsystem|microblaze_0_axi_periph_M02_AXI 1 4 1 2710 982n
preplace netloc CAM_Subsystem|microblaze_0_axi_periph_M03_AXI 1 4 1 2700 1002n
preplace netloc CAM_Subsystem|microblaze_0_axi_periph_M04_AXI 1 4 1 2690 1022n
preplace netloc CAM_Subsystem|microblaze_0_axi_periph_M05_AXI 1 4 1 2680 1042n
preplace netloc CAM_Subsystem|microblaze_0_axi_periph_M06_AXI 1 4 1 2640 1062n
preplace netloc CAM_Subsystem|microblaze_0_axi_periph_M07_AXI 1 4 1 2700 1082n
preplace netloc CAM_Subsystem|microblaze_0_axi_periph_M08_AXI 1 4 1 2690 1102n
preplace netloc CAM_Subsystem|microblaze_0_axi_periph_M09_AXI 1 4 1 2670 1122n
preplace netloc CAM_Subsystem|microblaze_0_debug 1 2 1 1540 1572n
preplace netloc CAM_Subsystem|microblaze_0_dlmb_1 1 3 1 N 1542
preplace netloc CAM_Subsystem|microblaze_0_ilmb_1 1 3 1 N 1562
preplace netloc CAM_Subsystem|microblaze_0_intc_axi 1 1 4 1240 1442 NJ 1442 2080J 1482 2550
preplace netloc CAM_Subsystem|microblaze_0_interrupt 1 2 1 1540 1552n
preplace netloc CAM_Subsystem|mipi_phy_if_0_1 1 0 5 NJ 1722 NJ 1722 NJ 1722 2120J 1692 2630
preplace netloc CAM_Subsystem|MIPI_Pipeline|axi_iic_0_iic2intc_irpt 1 3 1 3980 1214n
preplace netloc CAM_Subsystem|MIPI_Pipeline|bg0_pin0_nc_0_1 1 0 1 N 1594
preplace netloc CAM_Subsystem|MIPI_Pipeline|bg2_pin0_nc_0_1 1 0 1 N 1614
preplace netloc CAM_Subsystem|MIPI_Pipeline|clk_wiz_1_clk_out2 1 0 1 2870 1574n
preplace netloc CAM_Subsystem|MIPI_Pipeline|microblaze_0_Clk 1 0 3 2880 1394 NJ 1394 3510
preplace netloc CAM_Subsystem|MIPI_Pipeline|rst_clk_wiz_1_100M_peripheral_aresetn 1 0 3 2900 1404 NJ 1404 3520
preplace netloc CAM_Subsystem|MIPI_Pipeline|mipi_csi2_rx_subsyst_0_video_out_tdata 1 1 2 NJ 1484 3460
preplace netloc CAM_Subsystem|MIPI_Pipeline|mipi_csi2_rx_subsyst_0_video_out_tuser 1 1 1 3240 1294n
preplace netloc CAM_Subsystem|MIPI_Pipeline|axi_vdma_0_s_axis_s2mm_tready 1 1 2 NJ 1524 3470
preplace netloc CAM_Subsystem|MIPI_Pipeline|mipi_csi2_rx_subsyst_0_video_out_tlast 1 1 2 NJ 1504 3490
preplace netloc CAM_Subsystem|MIPI_Pipeline|mipi_csi2_rx_subsyst_0_video_out_tvalid 1 1 2 NJ 1564 3500
preplace netloc CAM_Subsystem|MIPI_Pipeline|int_enable_0_t_user_o 1 2 1 3480 1314n
preplace netloc CAM_Subsystem|MIPI_Pipeline|axi_gpio_0_gpio_io_o 1 1 1 N 1314
preplace netloc CAM_Subsystem|MIPI_Pipeline|int_enable_0_int_o 1 2 2 N 1294 3970J
preplace netloc CAM_Subsystem|MIPI_Pipeline|axi_gpio_2_GPIO 1 3 1 N 1074
preplace netloc CAM_Subsystem|MIPI_Pipeline|axi_iic_0_IIC 1 3 1 N 1194
preplace netloc CAM_Subsystem|MIPI_Pipeline|axi_vdma_0_M_AXI_S2MM 1 3 1 N 1474
preplace netloc CAM_Subsystem|MIPI_Pipeline|microblaze_0_axi_periph_M03_AXI 1 0 3 NJ 1054 NJ 1054 N
preplace netloc CAM_Subsystem|MIPI_Pipeline|microblaze_0_axi_periph_M04_AXI 1 0 3 NJ 1034 NJ 1034 3530
preplace netloc CAM_Subsystem|MIPI_Pipeline|microblaze_0_axi_periph_M07_AXI 1 0 3 NJ 1384 NJ 1384 N
preplace netloc CAM_Subsystem|MIPI_Pipeline|microblaze_0_axi_periph_M08_AXI 1 0 1 2890 1474n
preplace netloc CAM_Subsystem|MIPI_Pipeline|mipi_phy_if_0_1 1 0 1 N 1494
preplace netloc CAM_Subsystem|MIPI_Pipeline|S_AXI2_1 1 0 1 N 1284
levelinfo -pg 1 0 200 540 1120 4470
levelinfo -hier CAM_Subsystem * 1120 1410 1800 2350 2960 *
levelinfo -hier CAM_Subsystem|MIPI_Pipeline * 3070 3350 3750 *
pagesize -pg 1 -db -bbox -sgen -290 0 4770 2410
pagesize -hier CAM_Subsystem -db -bbox -sgen 950 592 4230 2372
pagesize -hier CAM_Subsystem|MIPI_Pipeline -db -bbox -sgen 2840 994 4010 1744
"
}

  # Restore current instance
  current_bd_instance $oldCurInst

  # Create PFM attributes
  set_property PFM_NAME {xilinx:vcu118:vcu118_mipi_uart_115200:0.0} [get_files [current_bd_design].bd]
  set_property PFM.CLOCK {clk_out1 {id "0" is_default "true" proc_sys_reset "/rst_clk_wiz_1_100M" status "fixed" freq_hz "100000000"}} [get_bd_cells /CAM_Subsystem/Clock_Reset/clk_wiz_1]


  validate_bd_design
  save_bd_design
  close_bd_design $design_name 
}
# End of cr_bd_ov2311_c2c()

cr_bd_ov2311_c2c ""
set_property PFM_NAME "xilinx:vcu118:vcu118_mipi_uart_115200:0.0" [get_files ov2311_c2c.bd ] 
set_property REGISTERED_WITH_MANAGER "1" [get_files ov2311_c2c.bd ] 
set_property SYNTH_CHECKPOINT_MODE "Hierarchical" [get_files ov2311_c2c.bd ] 

#call make_wrapper to create wrapper files
if { [get_property IS_LOCKED [ get_files -norecurse [list ov2311_c2c.bd]] ] == 1  } {
  import_files -fileset sources_1 [file normalize "${origin_dir}/vivado/ov2311_c2c/ov2311_c2c.gen/sources_1/bd/ov2311_c2c/hdl/ov2311_c2c_wrapper.v" ]
} else {
  set wrapper_path [make_wrapper -fileset sources_1 -files [ get_files -norecurse [list ov2311_c2c.bd]] -top]
  add_files -norecurse -fileset sources_1 $wrapper_path
}


set idrFlowPropertiesConstraints ""
catch {
 set idrFlowPropertiesConstraints [get_param runs.disableIDRFlowPropertyConstraints]
 set_param runs.disableIDRFlowPropertyConstraints 1
}

# Create 'synth_1' run (if not found)
if {[string equal [get_runs -quiet synth_1] ""]} {
    create_run -name synth_1 -part xcvu9p-flga2104-2L-e -flow {Vivado Synthesis 2024} -strategy "Vivado Synthesis Defaults" -report_strategy {No Reports} -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs synth_1]
  set_property flow "Vivado Synthesis 2024" [get_runs synth_1]
}
set obj [get_runs synth_1]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Synthesis Default Reports} $obj
set_property set_report_strategy_name 0 $obj
# Create 'synth_1_synth_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs synth_1] synth_1_synth_report_utilization_0] "" ] } {
  create_report_config -report_name synth_1_synth_report_utilization_0 -report_type report_utilization:1.0 -steps synth_design -runs synth_1
}
set obj [get_report_configs -of_objects [get_runs synth_1] synth_1_synth_report_utilization_0]
if { $obj != "" } {

}
set obj [get_runs synth_1]
set_property -name "auto_incremental_checkpoint" -value "1" -objects $obj
set_property -name "strategy" -value "Vivado Synthesis Defaults" -objects $obj

# set the current synth run
current_run -synthesis [get_runs synth_1]

# Create 'impl_1' run (if not found)
if {[string equal [get_runs -quiet impl_1] ""]} {
    create_run -name impl_1 -part xcvu9p-flga2104-2L-e -flow {Vivado Implementation 2024} -strategy "Vivado Implementation Defaults" -report_strategy {No Reports} -constrset constrs_1 -parent_run synth_1
} else {
  set_property strategy "Vivado Implementation Defaults" [get_runs impl_1]
  set_property flow "Vivado Implementation 2024" [get_runs impl_1]
}
set obj [get_runs impl_1]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Implementation Default Reports} $obj
set_property set_report_strategy_name 0 $obj
# Create 'impl_1_init_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_init_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_init_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps init_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_init_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_opt_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_drc_0] "" ] } {
  create_report_config -report_name impl_1_opt_report_drc_0 -report_type report_drc:1.0 -steps opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_drc_0]
if { $obj != "" } {

}
# Create 'impl_1_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps power_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_place_report_io_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_io_0] "" ] } {
  create_report_config -report_name impl_1_place_report_io_0 -report_type report_io:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_io_0]
if { $obj != "" } {

}
# Create 'impl_1_place_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_utilization_0] "" ] } {
  create_report_config -report_name impl_1_place_report_utilization_0 -report_type report_utilization:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_utilization_0]
if { $obj != "" } {

}
# Create 'impl_1_place_report_control_sets_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_control_sets_0] "" ] } {
  create_report_config -report_name impl_1_place_report_control_sets_0 -report_type report_control_sets:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_control_sets_0]
if { $obj != "" } {
set_property -name "options.verbose" -value "1" -objects $obj

}
# Create 'impl_1_place_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name impl_1_place_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_place_report_incremental_reuse_1' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_1] "" ] } {
  create_report_config -report_name impl_1_place_report_incremental_reuse_1 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_1]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_place_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_place_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_post_place_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_place_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_post_place_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_place_power_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_place_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_phys_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_route_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_drc_0] "" ] } {
  create_report_config -report_name impl_1_route_report_drc_0 -report_type report_drc:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_drc_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_methodology_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_methodology_0] "" ] } {
  create_report_config -report_name impl_1_route_report_methodology_0 -report_type report_methodology:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_methodology_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_power_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_power_0] "" ] } {
  create_report_config -report_name impl_1_route_report_power_0 -report_type report_power:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_power_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_route_status_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_route_status_0] "" ] } {
  create_report_config -report_name impl_1_route_report_route_status_0 -report_type report_route_status:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_route_status_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_route_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_timing_summary_0]
if { $obj != "" } {
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_route_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name impl_1_route_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_incremental_reuse_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_clock_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_clock_utilization_0] "" ] } {
  create_report_config -report_name impl_1_route_report_clock_utilization_0 -report_type report_clock_utilization:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_clock_utilization_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_bus_skew_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_bus_skew_0] "" ] } {
  create_report_config -report_name impl_1_route_report_bus_skew_0 -report_type report_bus_skew:1.1 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_bus_skew_0]
if { $obj != "" } {
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
# Create 'impl_1_post_route_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_post_route_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_route_phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
# Create 'impl_1_post_route_phys_opt_report_bus_skew_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_bus_skew_0] "" ] } {
  create_report_config -report_name impl_1_post_route_phys_opt_report_bus_skew_0 -report_type report_bus_skew:1.1 -steps post_route_phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_bus_skew_0]
if { $obj != "" } {
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
set obj [get_runs impl_1]
set_property -name "strategy" -value "Vivado Implementation Defaults" -objects $obj
set_property -name "steps.write_bitstream.args.readback_file" -value "0" -objects $obj
set_property -name "steps.write_bitstream.args.verbose" -value "0" -objects $obj

# set the current impl run
current_run -implementation [get_runs impl_1]
catch {
 if { $idrFlowPropertiesConstraints != {} } {
   set_param runs.disableIDRFlowPropertyConstraints $idrFlowPropertiesConstraints
 }
}

puts "INFO: Project created:${_xil_proj_name_}"
# Create 'drc_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "drc_1" ] ] ""]} {
create_dashboard_gadget -name {drc_1} -type drc
}
set obj [get_dashboard_gadgets [ list "drc_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_drc_0" -objects $obj

# Create 'methodology_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "methodology_1" ] ] ""]} {
create_dashboard_gadget -name {methodology_1} -type methodology
}
set obj [get_dashboard_gadgets [ list "methodology_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_methodology_0" -objects $obj

# Create 'power_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "power_1" ] ] ""]} {
create_dashboard_gadget -name {power_1} -type power
}
set obj [get_dashboard_gadgets [ list "power_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_power_0" -objects $obj

# Create 'timing_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "timing_1" ] ] ""]} {
create_dashboard_gadget -name {timing_1} -type timing
}
set obj [get_dashboard_gadgets [ list "timing_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_timing_summary_0" -objects $obj

# Create 'utilization_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "utilization_1" ] ] ""]} {
create_dashboard_gadget -name {utilization_1} -type utilization
}
set obj [get_dashboard_gadgets [ list "utilization_1" ] ]
set_property -name "reports" -value "synth_1#synth_1_synth_report_utilization_0" -objects $obj
set_property -name "run.step" -value "synth_design" -objects $obj
set_property -name "run.type" -value "synthesis" -objects $obj

# Create 'utilization_2' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "utilization_2" ] ] ""]} {
create_dashboard_gadget -name {utilization_2} -type utilization
}
set obj [get_dashboard_gadgets [ list "utilization_2" ] ]
set_property -name "reports" -value "impl_1#impl_1_place_report_utilization_0" -objects $obj

move_dashboard_gadget -name {utilization_1} -row 0 -col 0
move_dashboard_gadget -name {power_1} -row 1 -col 0
move_dashboard_gadget -name {drc_1} -row 2 -col 0
move_dashboard_gadget -name {timing_1} -row 0 -col 1
move_dashboard_gadget -name {utilization_2} -row 1 -col 1
move_dashboard_gadget -name {methodology_1} -row 2 -col 1
