# Generated file!! DO NOT edit!!

# 300MHZ clock
set_property PACKAGE_PIN AL8 [get_ports {CLK_IN1_D_0_clk_p}]
set_property PACKAGE_PIN AL7 [get_ports {CLK_IN1_D_0_clk_n}]
set_property IOSTANDARD DIFF_SSTL12 [get_ports {CLK_IN1_D_0_clk_p}]
set_property IOSTANDARD DIFF_SSTL12 [get_ports {CLK_IN1_D_0_clk_n}]

#GPIO LEDs (Active High)
set_property PACKAGE_PIN AG14 [get_ports {GPIO_LED_0}]
set_property PACKAGE_PIN AF13 [get_ports {GPIO_LED_1}]
set_property PACKAGE_PIN AE13 [get_ports {GPIO_LED_2}]
set_property PACKAGE_PIN AJ14 [get_ports {GPIO_LED_3}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_LED_0}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_LED_1}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_LED_2}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_LED_3}]


set_property IOSTANDARD LVCMOS18 [get_ports {axi_c2c_selio_rx_data*}]
set_property IOSTANDARD LVCMOS18 [get_ports {axi_c2c_selio_tx_data*}]

set_property IOSTANDARD DIFF_SSTL18_I [get_ports {axi_c2c_selio_tx_diff_clk_out_n_0}]
set_property IOSTANDARD DIFF_SSTL18_I [get_ports {axi_c2c_selio_tx_diff_clk_out_p_0}]
set_property IOSTANDARD DIFF_SSTL18_I [get_ports {axi_c2c_selio_rx_diff_clk_in_n_0}]
set_property IOSTANDARD DIFF_SSTL18_I [get_ports {axi_c2c_selio_rx_diff_clk_in_p_0}]


# RX pins
set_property PACKAGE_PIN AA7 [get_ports {axi_c2c_selio_rx_diff_clk_in_p_0}]
set_property PACKAGE_PIN AA6 [get_ports {axi_c2c_selio_rx_diff_clk_in_n_0}]
set_property PACKAGE_PIN V1 [get_ports {axi_c2c_selio_rx_data_in_0[0]}]
set_property PACKAGE_PIN V2 [get_ports {axi_c2c_selio_rx_data_in_0[1]}]
set_property PACKAGE_PIN Y1 [get_ports {axi_c2c_selio_rx_data_in_0[2]}]
set_property PACKAGE_PIN Y2 [get_ports {axi_c2c_selio_rx_data_in_0[3]}]
set_property PACKAGE_PIN AA1 [get_ports {axi_c2c_selio_rx_data_in_0[4]}]
set_property PACKAGE_PIN AA2 [get_ports {axi_c2c_selio_rx_data_in_0[5]}]
set_property PACKAGE_PIN AC3 [get_ports {axi_c2c_selio_rx_data_in_0[6]}]
set_property PACKAGE_PIN AB3 [get_ports {axi_c2c_selio_rx_data_in_0[7]}]
set_property PACKAGE_PIN AC1 [get_ports {axi_c2c_selio_rx_data_in_0[8]}]
set_property PACKAGE_PIN AC2 [get_ports {axi_c2c_selio_rx_data_in_0[9]}]
set_property PACKAGE_PIN U4 [get_ports {axi_c2c_selio_rx_data_in_0[10]}]
set_property PACKAGE_PIN U5 [get_ports {axi_c2c_selio_rx_data_in_0[11]}]
set_property PACKAGE_PIN V3 [get_ports {axi_c2c_selio_rx_data_in_0[12]}]
set_property PACKAGE_PIN V4 [get_ports {axi_c2c_selio_rx_data_in_0[13]}]
set_property PACKAGE_PIN W1 [get_ports {axi_c2c_selio_rx_data_in_0[14]}]
set_property PACKAGE_PIN W2 [get_ports {axi_c2c_selio_rx_data_in_0[15]}]
set_property PACKAGE_PIN W4 [get_ports {axi_c2c_selio_rx_data_in_0[16]}]
set_property PACKAGE_PIN W5 [get_ports {axi_c2c_selio_rx_data_in_0[17]}]
set_property PACKAGE_PIN AB5 [get_ports {axi_c2c_selio_rx_data_in_0[18]}]
set_property PACKAGE_PIN AB6 [get_ports {axi_c2c_selio_rx_data_in_0[19]}]
set_property PACKAGE_PIN W6 [get_ports {axi_c2c_selio_rx_data_in_0[20]}]
set_property PACKAGE_PIN W7 [get_ports {axi_c2c_selio_rx_data_in_0[21]}]


# TX pins
set_property PACKAGE_PIN T8 [get_ports {axi_c2c_selio_tx_diff_clk_out_p_0}]
set_property PACKAGE_PIN R8 [get_ports {axi_c2c_selio_tx_diff_clk_out_n_0}]
set_property PACKAGE_PIN AC8 [get_ports {axi_c2c_selio_tx_data_out_0[0]}]
set_property PACKAGE_PIN AB8 [get_ports {axi_c2c_selio_tx_data_out_0[1]}]
set_property PACKAGE_PIN AC6 [get_ports {axi_c2c_selio_tx_data_out_0[2]}]
set_property PACKAGE_PIN AC7 [get_ports {axi_c2c_selio_tx_data_out_0[3]}]
set_property PACKAGE_PIN Y9 [get_ports {axi_c2c_selio_tx_data_out_0[4]}]
set_property PACKAGE_PIN Y10 [get_ports {axi_c2c_selio_tx_data_out_0[5]}]
set_property PACKAGE_PIN AA12 [get_ports {axi_c2c_selio_tx_data_out_0[6]}]
set_property PACKAGE_PIN Y12 [get_ports {axi_c2c_selio_tx_data_out_0[7]}]
set_property PACKAGE_PIN N11 [get_ports {axi_c2c_selio_tx_data_out_0[8]}]
set_property PACKAGE_PIN P11 [get_ports {axi_c2c_selio_tx_data_out_0[9]}]
set_property PACKAGE_PIN N8 [get_ports {axi_c2c_selio_tx_data_out_0[10]}]
set_property PACKAGE_PIN N9 [get_ports {axi_c2c_selio_tx_data_out_0[11]}]
set_property PACKAGE_PIN K13 [get_ports {axi_c2c_selio_tx_data_out_0[12]}]
set_property PACKAGE_PIN L13 [get_ports {axi_c2c_selio_tx_data_out_0[13]}]
set_property PACKAGE_PIN M13 [get_ports {axi_c2c_selio_tx_data_out_0[14]}]
set_property PACKAGE_PIN N13 [get_ports {axi_c2c_selio_tx_data_out_0[15]}]
set_property PACKAGE_PIN N12 [get_ports {axi_c2c_selio_tx_data_out_0[16]}]
set_property PACKAGE_PIN P12 [get_ports {axi_c2c_selio_tx_data_out_0[17]}]
set_property PACKAGE_PIN M14 [get_ports {axi_c2c_selio_tx_data_out_0[18]}]
set_property PACKAGE_PIN M15 [get_ports {axi_c2c_selio_tx_data_out_0[19]}]
set_property PACKAGE_PIN K16 [get_ports {axi_c2c_selio_tx_data_out_0[20]}]
set_property PACKAGE_PIN L16 [get_ports {axi_c2c_selio_tx_data_out_0[21]}]
