# Generated file!! DO NOT edit!!

# 300MHZ clock
set_property PACKAGE_PIN AL8 [get_ports {CLK_IN1_D_0_clk_p}]
set_property PACKAGE_PIN AL7 [get_ports {CLK_IN1_D_0_clk_n}]
set_property IOSTANDARD DIFF_SSTL12 [get_ports {CLK_IN1_D_0_clk_p}]
set_property IOSTANDARD DIFF_SSTL12 [get_ports {CLK_IN1_D_0_clk_n}]

#GPIO LEDs (Active High)
set_property PACKAGE_PIN AG14 [get_ports {GPIO_LED_0}]
set_property PACKAGE_PIN AF13 [get_ports {GPIO_LED_1}]
set_property PACKAGE_PIN AE13 [get_ports {GPIO_LED_2}]
set_property PACKAGE_PIN AJ14 [get_ports {GPIO_LED_3}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_LED_0}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_LED_1}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_LED_2}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_LED_3}]


set_property IOSTANDARD LVCMOS18 [get_ports {axi_c2c_selio_rx_data*}]
set_property IOSTANDARD LVCMOS18 [get_ports {axi_c2c_selio_tx_data*}]

set_property IOSTANDARD DIFF_SSTL18_I [get_ports {axi_c2c_selio_tx_diff_clk_out_n_0}]
set_property IOSTANDARD DIFF_SSTL18_I [get_ports {axi_c2c_selio_tx_diff_clk_out_p_0}]
set_property IOSTANDARD DIFF_SSTL18_I [get_ports {axi_c2c_selio_rx_diff_clk_in_n_0}]
set_property IOSTANDARD DIFF_SSTL18_I [get_ports {axi_c2c_selio_rx_diff_clk_in_p_0}]


# RX pins
set_property PACKAGE_PIN AE7 [get_ports {axi_c2c_selio_rx_diff_clk_in_p_0}]
set_property PACKAGE_PIN AF7 [get_ports {axi_c2c_selio_rx_diff_clk_in_n_0}]
set_property PACKAGE_PIN AD1 [get_ports {axi_c2c_selio_rx_data_in_0[0]}]
set_property PACKAGE_PIN AD2 [get_ports {axi_c2c_selio_rx_data_in_0[1]}]
set_property PACKAGE_PIN AJ1 [get_ports {axi_c2c_selio_rx_data_in_0[2]}]
set_property PACKAGE_PIN AH1 [get_ports {axi_c2c_selio_rx_data_in_0[3]}]
set_property PACKAGE_PIN AF1 [get_ports {axi_c2c_selio_rx_data_in_0[4]}]
set_property PACKAGE_PIN AF2 [get_ports {axi_c2c_selio_rx_data_in_0[5]}]
set_property PACKAGE_PIN AH3 [get_ports {axi_c2c_selio_rx_data_in_0[6]}]
set_property PACKAGE_PIN AG3 [get_ports {axi_c2c_selio_rx_data_in_0[7]}]
set_property PACKAGE_PIN AJ2 [get_ports {axi_c2c_selio_rx_data_in_0[8]}]
set_property PACKAGE_PIN AH2 [get_ports {axi_c2c_selio_rx_data_in_0[9]}]
set_property PACKAGE_PIN AE4 [get_ports {axi_c2c_selio_rx_data_in_0[10]}]
set_property PACKAGE_PIN AD4 [get_ports {axi_c2c_selio_rx_data_in_0[11]}]
set_property PACKAGE_PIN AF3 [get_ports {axi_c2c_selio_rx_data_in_0[12]}]
set_property PACKAGE_PIN AE3 [get_ports {axi_c2c_selio_rx_data_in_0[13]}]
set_property PACKAGE_PIN AE1 [get_ports {axi_c2c_selio_rx_data_in_0[14]}]
set_property PACKAGE_PIN AE2 [get_ports {axi_c2c_selio_rx_data_in_0[15]}]
set_property PACKAGE_PIN AJ4 [get_ports {axi_c2c_selio_rx_data_in_0[16]}]
set_property PACKAGE_PIN AH4 [get_ports {axi_c2c_selio_rx_data_in_0[17]}]
set_property PACKAGE_PIN AF8 [get_ports {axi_c2c_selio_rx_data_in_0[18]}]
set_property PACKAGE_PIN AE8 [get_ports {axi_c2c_selio_rx_data_in_0[19]}]
set_property PACKAGE_PIN AD6 [get_ports {axi_c2c_selio_rx_data_in_0[20]}]
set_property PACKAGE_PIN AD7 [get_ports {axi_c2c_selio_rx_data_in_0[21]}]


# TX pins
set_property PACKAGE_PIN P10 [get_ports {axi_c2c_selio_tx_diff_clk_out_p_0}]
set_property PACKAGE_PIN P9 [get_ports {axi_c2c_selio_tx_diff_clk_out_n_0}]
set_property PACKAGE_PIN AH8 [get_ports {axi_c2c_selio_tx_data_out_0[0]}]
set_property PACKAGE_PIN AG8 [get_ports {axi_c2c_selio_tx_data_out_0[1]}]
set_property PACKAGE_PIN AH6 [get_ports {axi_c2c_selio_tx_data_out_0[2]}]
set_property PACKAGE_PIN AH7 [get_ports {axi_c2c_selio_tx_data_out_0[3]}]
set_property PACKAGE_PIN AE9 [get_ports {axi_c2c_selio_tx_data_out_0[4]}]
set_property PACKAGE_PIN AD10 [get_ports {axi_c2c_selio_tx_data_out_0[5]}]
set_property PACKAGE_PIN AG9 [get_ports {axi_c2c_selio_tx_data_out_0[6]}]
set_property PACKAGE_PIN AG10 [get_ports {axi_c2c_selio_tx_data_out_0[7]}]
set_property PACKAGE_PIN AA5 [get_ports {axi_c2c_selio_tx_data_out_0[8]}]
set_property PACKAGE_PIN Y5 [get_ports {axi_c2c_selio_tx_data_out_0[9]}]
set_property PACKAGE_PIN Y7 [get_ports {axi_c2c_selio_tx_data_out_0[10]}]
set_property PACKAGE_PIN Y8 [get_ports {axi_c2c_selio_tx_data_out_0[11]}]
set_property PACKAGE_PIN AA10 [get_ports {axi_c2c_selio_tx_data_out_0[12]}]
set_property PACKAGE_PIN AA11 [get_ports {axi_c2c_selio_tx_data_out_0[13]}]
set_property PACKAGE_PIN AB10 [get_ports {axi_c2c_selio_tx_data_out_0[14]}]
set_property PACKAGE_PIN AB11 [get_ports {axi_c2c_selio_tx_data_out_0[15]}]
set_property PACKAGE_PIN AC11 [get_ports {axi_c2c_selio_tx_data_out_0[16]}]
set_property PACKAGE_PIN AC12 [get_ports {axi_c2c_selio_tx_data_out_0[17]}]
set_property PACKAGE_PIN AG11 [get_ports {axi_c2c_selio_tx_data_out_0[18]}]
set_property PACKAGE_PIN AF11 [get_ports {axi_c2c_selio_tx_data_out_0[19]}]
set_property PACKAGE_PIN AF12 [get_ports {axi_c2c_selio_tx_data_out_0[20]}]
set_property PACKAGE_PIN AE12 [get_ports {axi_c2c_selio_tx_data_out_0[21]}]
