-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity execute_execute_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_140_1_VITIS_LOOP_143_2 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m_axi_data_mem_0_AWVALID : OUT STD_LOGIC;
    m_axi_data_mem_0_AWREADY : IN STD_LOGIC;
    m_axi_data_mem_0_AWADDR : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_data_mem_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_data_mem_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_data_mem_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_data_mem_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_data_mem_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_data_mem_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_data_mem_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_data_mem_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_data_mem_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_data_mem_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_data_mem_0_WVALID : OUT STD_LOGIC;
    m_axi_data_mem_0_WREADY : IN STD_LOGIC;
    m_axi_data_mem_0_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_data_mem_0_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_data_mem_0_WLAST : OUT STD_LOGIC;
    m_axi_data_mem_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_data_mem_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_data_mem_0_ARVALID : OUT STD_LOGIC;
    m_axi_data_mem_0_ARREADY : IN STD_LOGIC;
    m_axi_data_mem_0_ARADDR : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_data_mem_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_data_mem_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_data_mem_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_data_mem_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_data_mem_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_data_mem_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_data_mem_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_data_mem_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_data_mem_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_data_mem_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_data_mem_0_RVALID : IN STD_LOGIC;
    m_axi_data_mem_0_RREADY : OUT STD_LOGIC;
    m_axi_data_mem_0_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    m_axi_data_mem_0_RLAST : IN STD_LOGIC;
    m_axi_data_mem_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_data_mem_0_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
    m_axi_data_mem_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_data_mem_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_data_mem_0_BVALID : IN STD_LOGIC;
    m_axi_data_mem_0_BREADY : OUT STD_LOGIC;
    m_axi_data_mem_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_data_mem_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_data_mem_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    stream_o_TREADY : IN STD_LOGIC;
    mul_ln19 : IN STD_LOGIC_VECTOR (50 downto 0);
    data_port : IN STD_LOGIC_VECTOR (31 downto 0);
    stream_o_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    stream_o_TVALID : OUT STD_LOGIC;
    stream_o_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
    stream_o_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    stream_o_TUSER : OUT STD_LOGIC_VECTOR (31 downto 0);
    stream_o_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    stream_o_TID : OUT STD_LOGIC_VECTOR (0 downto 0);
    stream_o_TDEST : OUT STD_LOGIC_VECTOR (0 downto 0) );
end;


architecture behav of execute_execute_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_140_1_VITIS_LOOP_143_2 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv19_0 : STD_LOGIC_VECTOR (18 downto 0) := "0000000000000000000";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv20_0 : STD_LOGIC_VECTOR (19 downto 0) := "00000000000000000000";
    constant ap_const_lv51_0 : STD_LOGIC_VECTOR (50 downto 0) := "000000000000000000000000000000000000000000000000000";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv51_1 : STD_LOGIC_VECTOR (50 downto 0) := "000000000000000000000000000000000000000000000000001";
    constant ap_const_lv20_7EF40 : STD_LOGIC_VECTOR (19 downto 0) := "01111110111101000000";
    constant ap_const_lv9_190 : STD_LOGIC_VECTOR (8 downto 0) := "110010000";
    constant ap_const_lv11_1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    constant ap_const_lv19_1 : STD_LOGIC_VECTOR (18 downto 0) := "0000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv9_18F : STD_LOGIC_VECTOR (8 downto 0) := "110001111";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv9_1 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    constant ap_const_lv19_190 : STD_LOGIC_VECTOR (18 downto 0) := "0000000000110010000";
    constant ap_const_lv20_1 : STD_LOGIC_VECTOR (19 downto 0) := "00000000000000000001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter9 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter10 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter11 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln23_fu_232_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter1_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal data_mem_blk_n_AR : STD_LOGIC;
    signal ap_block_pp0_stage0_grp1 : BOOLEAN;
    signal data_mem_blk_n_R : STD_LOGIC;
    signal stream_o_TDATA_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal trunc_ln1_reg_563 : STD_LOGIC_VECTOR (29 downto 0);
    signal px_last_fu_390_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal px_last_reg_568 : STD_LOGIC_VECTOR (0 downto 0);
    signal px_last_reg_568_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal px_last_reg_568_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal px_last_reg_568_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal px_last_reg_568_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal px_last_reg_568_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal px_last_reg_568_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal px_last_reg_568_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal px_last_reg_568_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal px_last_reg_568_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal sof_fu_420_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sof_reg_573 : STD_LOGIC_VECTOR (0 downto 0);
    signal sof_reg_573_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal sof_reg_573_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal sof_reg_573_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal sof_reg_573_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal sof_reg_573_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal sof_reg_573_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal sof_reg_573_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal sof_reg_573_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal sof_reg_573_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_11001_grp1 : BOOLEAN;
    signal px_data_reg_584 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln145_fu_487_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal j_fu_118 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    signal j_1_fu_426_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal offset_fu_122 : STD_LOGIC_VECTOR (18 downto 0) := "0000000000000000000";
    signal add_ln145_fu_357_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal add_ln1401_fu_126 : STD_LOGIC_VECTOR (18 downto 0) := "0000000000000000000";
    signal add_ln140_fu_432_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal i_fu_130 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    signal select_ln140_3_fu_345_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal indvars_iv_i_fu_134 : STD_LOGIC_VECTOR (18 downto 0) := "0000000000000000000";
    signal select_ln140_2_fu_337_p3 : STD_LOGIC_VECTOR (18 downto 0);
    signal indvar_flatten_fu_138 : STD_LOGIC_VECTOR (19 downto 0) := "00000000000000000000";
    signal select_ln140_4_fu_444_p3 : STD_LOGIC_VECTOR (19 downto 0);
    signal indvar_flatten14_fu_142 : STD_LOGIC_VECTOR (50 downto 0) := "000000000000000000000000000000000000000000000000000";
    signal add_ln23_fu_237_p2 : STD_LOGIC_VECTOR (50 downto 0);
    signal ap_block_pp0_stage0_01001_grp1 : BOOLEAN;
    signal icmp_ln140_fu_261_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln143_fu_297_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln22_fu_291_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln22_1_fu_275_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal and_ln22_fu_303_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln22_2_fu_283_p3 : STD_LOGIC_VECTOR (18 downto 0);
    signal or_ln140_fu_323_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln22_fu_267_p3 : STD_LOGIC_VECTOR (18 downto 0);
    signal i_2_fu_309_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln140_fu_315_p3 : STD_LOGIC_VECTOR (18 downto 0);
    signal shl_ln_fu_363_p3 : STD_LOGIC_VECTOR (20 downto 0);
    signal zext_ln145_fu_371_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln145_1_fu_375_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln140_1_fu_329_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln152_fu_353_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_fu_402_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal or_ln152_fu_396_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal or_ln_fu_412_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln140_2_fu_438_p2 : STD_LOGIC_VECTOR (19 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter7_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter8_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter9_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter10_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component execute_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component execute_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter1_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter10_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter10_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter10 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter11_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter11 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter9_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter9 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
                end if; 
            end if;
        end if;
    end process;


    i_fu_130_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_130 <= ap_const_lv11_0;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln23_fu_232_p2 = ap_const_lv1_0))) then 
                    i_fu_130 <= select_ln140_3_fu_345_p3;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten14_fu_142_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten14_fu_142 <= ap_const_lv51_0;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln23_fu_232_p2 = ap_const_lv1_0))) then 
                    indvar_flatten14_fu_142 <= add_ln23_fu_237_p2;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten_fu_138_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten_fu_138 <= ap_const_lv20_0;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln23_fu_232_p2 = ap_const_lv1_0))) then 
                    indvar_flatten_fu_138 <= select_ln140_4_fu_444_p3;
                end if;
            end if; 
        end if;
    end process;

    indvars_iv_i_fu_134_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    indvars_iv_i_fu_134 <= ap_const_lv19_0;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln23_fu_232_p2 = ap_const_lv1_0))) then 
                    indvars_iv_i_fu_134 <= select_ln140_2_fu_337_p3;
                end if;
            end if; 
        end if;
    end process;

    j_fu_118_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    j_fu_118 <= ap_const_lv9_0;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln23_fu_232_p2 = ap_const_lv1_0))) then 
                    j_fu_118 <= j_1_fu_426_p2;
                end if;
            end if; 
        end if;
    end process;

    offset_fu_122_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    offset_fu_122 <= ap_const_lv19_0;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln23_fu_232_p2 = ap_const_lv1_0))) then 
                    offset_fu_122 <= add_ln145_fu_357_p2;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln23_fu_232_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                add_ln1401_fu_126 <= add_ln140_fu_432_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
                ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
                ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
                ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
                px_last_reg_568_pp0_iter10_reg <= px_last_reg_568_pp0_iter9_reg;
                px_last_reg_568_pp0_iter2_reg <= px_last_reg_568;
                px_last_reg_568_pp0_iter3_reg <= px_last_reg_568_pp0_iter2_reg;
                px_last_reg_568_pp0_iter4_reg <= px_last_reg_568_pp0_iter3_reg;
                px_last_reg_568_pp0_iter5_reg <= px_last_reg_568_pp0_iter4_reg;
                px_last_reg_568_pp0_iter6_reg <= px_last_reg_568_pp0_iter5_reg;
                px_last_reg_568_pp0_iter7_reg <= px_last_reg_568_pp0_iter6_reg;
                px_last_reg_568_pp0_iter8_reg <= px_last_reg_568_pp0_iter7_reg;
                px_last_reg_568_pp0_iter9_reg <= px_last_reg_568_pp0_iter8_reg;
                sof_reg_573_pp0_iter10_reg <= sof_reg_573_pp0_iter9_reg;
                sof_reg_573_pp0_iter2_reg <= sof_reg_573;
                sof_reg_573_pp0_iter3_reg <= sof_reg_573_pp0_iter2_reg;
                sof_reg_573_pp0_iter4_reg <= sof_reg_573_pp0_iter3_reg;
                sof_reg_573_pp0_iter5_reg <= sof_reg_573_pp0_iter4_reg;
                sof_reg_573_pp0_iter6_reg <= sof_reg_573_pp0_iter5_reg;
                sof_reg_573_pp0_iter7_reg <= sof_reg_573_pp0_iter6_reg;
                sof_reg_573_pp0_iter8_reg <= sof_reg_573_pp0_iter7_reg;
                sof_reg_573_pp0_iter9_reg <= sof_reg_573_pp0_iter8_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
                px_last_reg_568 <= px_last_fu_390_p2;
                sof_reg_573 <= sof_fu_420_p2;
                trunc_ln1_reg_563 <= add_ln145_1_fu_375_p2(31 downto 2);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then
                px_data_reg_584 <= m_axi_data_mem_0_RDATA;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln140_2_fu_438_p2 <= std_logic_vector(unsigned(indvar_flatten_fu_138) + unsigned(ap_const_lv20_1));
    add_ln140_fu_432_p2 <= std_logic_vector(unsigned(select_ln140_2_fu_337_p3) + unsigned(ap_const_lv19_190));
    add_ln145_1_fu_375_p2 <= std_logic_vector(unsigned(zext_ln145_fu_371_p1) + unsigned(data_port));
    add_ln145_fu_357_p2 <= std_logic_vector(unsigned(select_ln140_fu_315_p3) + unsigned(ap_const_lv19_1));
    add_ln23_fu_237_p2 <= std_logic_vector(unsigned(indvar_flatten14_fu_142) + unsigned(ap_const_lv51_1));
    and_ln22_fu_303_p2 <= (xor_ln22_fu_291_p2 and icmp_ln143_fu_297_p2);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_grp1_assign_proc : process(ap_enable_reg_pp0_iter10, ap_enable_reg_pp0_iter11, m_axi_data_mem_0_RVALID, stream_o_TREADY)
    begin
                ap_block_pp0_stage0_01001_grp1 <= (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (stream_o_TREADY = ap_const_logic_0)) or ((m_axi_data_mem_0_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter10 = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter10, ap_enable_reg_pp0_iter11, m_axi_data_mem_0_ARREADY, m_axi_data_mem_0_RVALID, stream_o_TREADY)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (stream_o_TREADY = ap_const_logic_0)) or ((m_axi_data_mem_0_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter10 = ap_const_logic_1)) or ((m_axi_data_mem_0_ARREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage0_11001_grp1_assign_proc : process(ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter10, ap_enable_reg_pp0_iter11, m_axi_data_mem_0_ARREADY, m_axi_data_mem_0_RVALID, stream_o_TREADY)
    begin
                ap_block_pp0_stage0_11001_grp1 <= (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (stream_o_TREADY = ap_const_logic_0)) or ((m_axi_data_mem_0_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter10 = ap_const_logic_1)) or ((m_axi_data_mem_0_ARREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)));
    end process;

        ap_block_pp0_stage0_grp1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter10, ap_enable_reg_pp0_iter11, m_axi_data_mem_0_ARREADY, m_axi_data_mem_0_RVALID, stream_o_TREADY)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (stream_o_TREADY = ap_const_logic_0)) or ((m_axi_data_mem_0_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter10 = ap_const_logic_1)) or ((m_axi_data_mem_0_ARREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)));
    end process;


    ap_condition_exit_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone, icmp_ln23_fu_232_p2)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln23_fu_232_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter10_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter10_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter10, ap_enable_reg_pp0_iter11)
    begin
        if (((ap_enable_reg_pp0_iter11 = ap_const_logic_0) and (ap_enable_reg_pp0_iter10 = ap_const_logic_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter1_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    data_mem_blk_n_AR_assign_proc : process(ap_enable_reg_pp0_iter2, m_axi_data_mem_0_ARREADY, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp1))) then 
            data_mem_blk_n_AR <= m_axi_data_mem_0_ARREADY;
        else 
            data_mem_blk_n_AR <= ap_const_logic_1;
        end if; 
    end process;


    data_mem_blk_n_R_assign_proc : process(ap_enable_reg_pp0_iter10, m_axi_data_mem_0_RVALID, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp1))) then 
            data_mem_blk_n_R <= m_axi_data_mem_0_RVALID;
        else 
            data_mem_blk_n_R <= ap_const_logic_1;
        end if; 
    end process;

    i_2_fu_309_p2 <= std_logic_vector(unsigned(select_ln22_1_fu_275_p3) + unsigned(ap_const_lv11_1));
    icmp_ln140_fu_261_p2 <= "1" when (indvar_flatten_fu_138 = ap_const_lv20_7EF40) else "0";
    icmp_ln143_fu_297_p2 <= "1" when (j_fu_118 = ap_const_lv9_190) else "0";
    icmp_ln23_fu_232_p2 <= "1" when (indvar_flatten14_fu_142 = mul_ln19) else "0";
    j_1_fu_426_p2 <= std_logic_vector(unsigned(select_ln140_1_fu_329_p3) + unsigned(ap_const_lv9_1));
    m_axi_data_mem_0_ARADDR <= sext_ln145_fu_487_p1;
    m_axi_data_mem_0_ARBURST <= ap_const_lv2_0;
    m_axi_data_mem_0_ARCACHE <= ap_const_lv4_0;
    m_axi_data_mem_0_ARID <= ap_const_lv1_0;
    m_axi_data_mem_0_ARLEN <= ap_const_lv32_1;
    m_axi_data_mem_0_ARLOCK <= ap_const_lv2_0;
    m_axi_data_mem_0_ARPROT <= ap_const_lv3_0;
    m_axi_data_mem_0_ARQOS <= ap_const_lv4_0;
    m_axi_data_mem_0_ARREGION <= ap_const_lv4_0;
    m_axi_data_mem_0_ARSIZE <= ap_const_lv3_0;
    m_axi_data_mem_0_ARUSER <= ap_const_lv1_0;

    m_axi_data_mem_0_ARVALID_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            m_axi_data_mem_0_ARVALID <= ap_const_logic_1;
        else 
            m_axi_data_mem_0_ARVALID <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_data_mem_0_AWADDR <= ap_const_lv32_0;
    m_axi_data_mem_0_AWBURST <= ap_const_lv2_0;
    m_axi_data_mem_0_AWCACHE <= ap_const_lv4_0;
    m_axi_data_mem_0_AWID <= ap_const_lv1_0;
    m_axi_data_mem_0_AWLEN <= ap_const_lv32_0;
    m_axi_data_mem_0_AWLOCK <= ap_const_lv2_0;
    m_axi_data_mem_0_AWPROT <= ap_const_lv3_0;
    m_axi_data_mem_0_AWQOS <= ap_const_lv4_0;
    m_axi_data_mem_0_AWREGION <= ap_const_lv4_0;
    m_axi_data_mem_0_AWSIZE <= ap_const_lv3_0;
    m_axi_data_mem_0_AWUSER <= ap_const_lv1_0;
    m_axi_data_mem_0_AWVALID <= ap_const_logic_0;
    m_axi_data_mem_0_BREADY <= ap_const_logic_0;

    m_axi_data_mem_0_RREADY_assign_proc : process(ap_enable_reg_pp0_iter10, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            m_axi_data_mem_0_RREADY <= ap_const_logic_1;
        else 
            m_axi_data_mem_0_RREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_data_mem_0_WDATA <= ap_const_lv32_0;
    m_axi_data_mem_0_WID <= ap_const_lv1_0;
    m_axi_data_mem_0_WLAST <= ap_const_logic_0;
    m_axi_data_mem_0_WSTRB <= ap_const_lv4_0;
    m_axi_data_mem_0_WUSER <= ap_const_lv1_0;
    m_axi_data_mem_0_WVALID <= ap_const_logic_0;
    or_ln140_fu_323_p2 <= (icmp_ln140_fu_261_p2 or and_ln22_fu_303_p2);
    or_ln152_fu_396_p2 <= (trunc_ln152_fu_353_p1 or select_ln140_1_fu_329_p3);
    or_ln_fu_412_p3 <= (tmp_fu_402_p4 & or_ln152_fu_396_p2);
    px_last_fu_390_p2 <= "1" when (select_ln140_1_fu_329_p3 = ap_const_lv9_18F) else "0";
    select_ln140_1_fu_329_p3 <= 
        ap_const_lv9_0 when (or_ln140_fu_323_p2(0) = '1') else 
        j_fu_118;
    select_ln140_2_fu_337_p3 <= 
        add_ln1401_fu_126 when (and_ln22_fu_303_p2(0) = '1') else 
        select_ln22_fu_267_p3;
    select_ln140_3_fu_345_p3 <= 
        i_2_fu_309_p2 when (and_ln22_fu_303_p2(0) = '1') else 
        select_ln22_1_fu_275_p3;
    select_ln140_4_fu_444_p3 <= 
        ap_const_lv20_1 when (icmp_ln140_fu_261_p2(0) = '1') else 
        add_ln140_2_fu_438_p2;
    select_ln140_fu_315_p3 <= 
        add_ln1401_fu_126 when (and_ln22_fu_303_p2(0) = '1') else 
        select_ln22_2_fu_283_p3;
    select_ln22_1_fu_275_p3 <= 
        ap_const_lv11_0 when (icmp_ln140_fu_261_p2(0) = '1') else 
        i_fu_130;
    select_ln22_2_fu_283_p3 <= 
        ap_const_lv19_0 when (icmp_ln140_fu_261_p2(0) = '1') else 
        offset_fu_122;
    select_ln22_fu_267_p3 <= 
        ap_const_lv19_0 when (icmp_ln140_fu_261_p2(0) = '1') else 
        indvars_iv_i_fu_134;
        sext_ln145_fu_487_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln1_reg_563),32));

    shl_ln_fu_363_p3 <= (select_ln140_fu_315_p3 & ap_const_lv2_0);
    sof_fu_420_p2 <= "1" when (or_ln_fu_412_p3 = ap_const_lv11_0) else "0";
    stream_o_TDATA <= px_data_reg_584;

    stream_o_TDATA_blk_n_assign_proc : process(ap_enable_reg_pp0_iter11, stream_o_TREADY, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp1))) then 
            stream_o_TDATA_blk_n <= stream_o_TREADY;
        else 
            stream_o_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    stream_o_TDEST <= ap_const_lv1_0;
    stream_o_TID <= ap_const_lv1_0;
    stream_o_TKEEP <= ap_const_lv4_F;
    stream_o_TLAST <= px_last_reg_568_pp0_iter10_reg;
    stream_o_TSTRB <= ap_const_lv4_F;
    stream_o_TUSER <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sof_reg_573_pp0_iter10_reg),32));

    stream_o_TVALID_assign_proc : process(ap_enable_reg_pp0_iter11, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            stream_o_TVALID <= ap_const_logic_1;
        else 
            stream_o_TVALID <= ap_const_logic_0;
        end if; 
    end process;

    tmp_fu_402_p4 <= select_ln140_3_fu_345_p3(10 downto 9);
    trunc_ln152_fu_353_p1 <= select_ln140_3_fu_345_p3(9 - 1 downto 0);
    xor_ln22_fu_291_p2 <= (icmp_ln140_fu_261_p2 xor ap_const_lv1_1);
    zext_ln145_fu_371_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln_fu_363_p3),32));
end behav;
