// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================
`timescale 1 ns / 1 ps
module execute_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_191_6_scrbkb (
    address0, ce0, q0, 
    reset, clk);

parameter DataWidth = 5;
parameter AddressWidth = 5;
parameter AddressRange = 27;
 
input[AddressWidth-1:0] address0;
input ce0;
output reg[DataWidth-1:0] q0;

input reset;
input clk;

 
reg [DataWidth-1:0] rom0[0:AddressRange-1];


initial begin
     
    $readmemh("./execute_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_191_6_scrbkb.dat", rom0);
end

  
always @(posedge clk) 
begin 
    if (ce0) 
    begin
        q0 <= rom0[address0];
    end
end


endmodule

