// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module execute_slice_tensor_2_vector_Pipeline_VITIS_LOOP_119_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        zext_ln62,
        y_start,
        offset_out,
        offset_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [1:0] zext_ln62;
input  [30:0] y_start;
output  [63:0] offset_out;
output   offset_out_ap_vld;

reg ap_idle;
reg offset_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln119_fu_112_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [30:0] zext_ln62_cast_fu_95_p1;
reg   [30:0] zext_ln62_cast_reg_231;
reg  signed [63:0] offset_fu_64;
wire   [63:0] offset_x_fu_191_p2;
wire    ap_loop_init;
wire    ap_block_pp0_stage0;
reg   [2:0] i_fu_68;
wire   [2:0] add_ln119_fu_118_p2;
wire    ap_block_pp0_stage0_01001;
wire   [10:0] mul_ln121_fu_91_p1;
wire   [7:0] tmp_fu_132_p9;
wire   [1:0] trunc_ln119_fu_128_p1;
wire   [7:0] tmp_fu_132_p11;
wire  signed [10:0] sext_ln121_fu_156_p1;
wire   [30:0] tmp_2_fu_165_p9;
wire   [30:0] tmp_2_fu_165_p11;
wire   [63:0] mul_ln121_fu_91_p2;
wire   [63:0] zext_ln121_2_fu_187_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [63:0] mul_ln121_fu_91_p10;
wire   [1:0] tmp_fu_132_p1;
wire   [1:0] tmp_fu_132_p3;
wire  signed [1:0] tmp_fu_132_p5;
wire  signed [1:0] tmp_fu_132_p7;
wire   [1:0] tmp_2_fu_165_p1;
wire   [1:0] tmp_2_fu_165_p3;
wire  signed [1:0] tmp_2_fu_165_p5;
wire  signed [1:0] tmp_2_fu_165_p7;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 offset_fu_64 = 64'd0;
#0 i_fu_68 = 3'd0;
#0 ap_done_reg = 1'b0;
end

execute_mul_64s_11ns_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 64 ))
mul_64s_11ns_64_1_1_U42(
    .din0(offset_fu_64),
    .din1(mul_ln121_fu_91_p1),
    .dout(mul_ln121_fu_91_p2)
);

(* dissolve_hierarchy = "yes" *) execute_sparsemux_9_2_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 8 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 8 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 8 ),
    .CASE3( 2'h3 ),
    .din3_WIDTH( 8 ),
    .def_WIDTH( 8 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
sparsemux_9_2_8_1_1_U43(
    .din0(8'd1),
    .din1(8'd3),
    .din2(8'd33),
    .din3(8'd128),
    .def(tmp_fu_132_p9),
    .sel(trunc_ln119_fu_128_p1),
    .dout(tmp_fu_132_p11)
);

(* dissolve_hierarchy = "yes" *) execute_sparsemux_9_2_31_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 31 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 31 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 31 ),
    .CASE3( 2'h3 ),
    .din3_WIDTH( 31 ),
    .def_WIDTH( 31 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 31 ))
sparsemux_9_2_31_1_1_U44(
    .din0(31'd0),
    .din1(zext_ln62_cast_reg_231),
    .din2(y_start),
    .din3(31'd0),
    .def(tmp_2_fu_165_p9),
    .sel(trunc_ln119_fu_128_p1),
    .dout(tmp_2_fu_165_p11)
);

execute_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            i_fu_68 <= 3'd0;
        end else if (((icmp_ln119_fu_112_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            i_fu_68 <= add_ln119_fu_118_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            offset_fu_64 <= 64'd0;
        end else if (((icmp_ln119_fu_112_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            offset_fu_64 <= offset_x_fu_191_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        zext_ln62_cast_reg_231[1 : 0] <= zext_ln62_cast_fu_95_p1[1 : 0];
    end
end

always @ (*) begin
    if (((icmp_ln119_fu_112_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln119_fu_112_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        offset_out_ap_vld = 1'b1;
    end else begin
        offset_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln119_fu_118_p2 = (i_fu_68 + 3'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign ap_ready = ap_ready_sig;

assign icmp_ln119_fu_112_p2 = ((i_fu_68 == 3'd4) ? 1'b1 : 1'b0);

assign mul_ln121_fu_91_p1 = mul_ln121_fu_91_p10;

assign mul_ln121_fu_91_p10 = $unsigned(sext_ln121_fu_156_p1);

assign offset_out = offset_fu_64;

assign offset_x_fu_191_p2 = (mul_ln121_fu_91_p2 + zext_ln121_2_fu_187_p1);

assign sext_ln121_fu_156_p1 = $signed(tmp_fu_132_p11);

assign tmp_2_fu_165_p9 = 'bx;

assign tmp_fu_132_p9 = 'bx;

assign trunc_ln119_fu_128_p1 = i_fu_68[1:0];

assign zext_ln121_2_fu_187_p1 = tmp_2_fu_165_p11;

assign zext_ln62_cast_fu_95_p1 = zext_ln62;

always @ (posedge ap_clk) begin
    zext_ln62_cast_reg_231[30:2] <= 29'b00000000000000000000000000000;
end

endmodule //execute_slice_tensor_2_vector_Pipeline_VITIS_LOOP_119_1
