// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module execute_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_168_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        empty,
        y_max_i,
        y_2_out,
        y_2_out_ap_vld,
        ap_return
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] empty;
input  [31:0] y_max_i;
output  [30:0] y_2_out;
output   y_2_out_ap_vld;
output  [0:0] ap_return;

reg ap_idle;
reg y_2_out_ap_vld;
reg[0:0] ap_return;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire   [0:0] or_ln170_fu_135_p2;
wire   [0:0] icmp_ln168_fu_88_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [0:0] ap_phi_mux_UnifiedRetVal_phi_fu_72_p4;
reg   [1:0] ky_fu_46;
wire   [1:0] ky_2_fu_94_p2;
wire    ap_loop_init;
reg   [1:0] ap_sig_allocacmp_ky_1;
wire   [31:0] zext_ln168_fu_100_p1;
wire   [31:0] y_fu_104_p2;
wire   [0:0] icmp_ln170_fu_123_p2;
wire   [0:0] tmp_2_fu_115_p3;
wire   [0:0] xor_ln170_fu_129_p2;
reg   [0:0] ap_return_preg;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ky_fu_46 = 2'd0;
#0 ap_return_preg = 1'd0;
#0 ap_done_reg = 1'b0;
end

execute_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_preg <= 1'd0;
    end else begin
        if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_preg <= ap_phi_mux_UnifiedRetVal_phi_fu_72_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        if (((icmp_ln168_fu_88_p2 == 1'd0) & (or_ln170_fu_135_p2 == 1'd1))) begin
            ky_fu_46 <= ky_2_fu_94_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            ky_fu_46 <= 2'd0;
        end
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1_pp0_stage0_iter0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & ((icmp_ln168_fu_88_p2 == 1'd1) | (or_ln170_fu_135_p2 == 1'd0)))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        if (((icmp_ln168_fu_88_p2 == 1'd0) & (or_ln170_fu_135_p2 == 1'd0))) begin
            ap_phi_mux_UnifiedRetVal_phi_fu_72_p4 = 1'd0;
        end else if ((icmp_ln168_fu_88_p2 == 1'd1)) begin
            ap_phi_mux_UnifiedRetVal_phi_fu_72_p4 = 1'd1;
        end else begin
            ap_phi_mux_UnifiedRetVal_phi_fu_72_p4 = 'bx;
        end
    end else begin
        ap_phi_mux_UnifiedRetVal_phi_fu_72_p4 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return = ap_phi_mux_UnifiedRetVal_phi_fu_72_p4;
    end else begin
        ap_return = ap_return_preg;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_ky_1 = 2'd0;
    end else begin
        ap_sig_allocacmp_ky_1 = ky_fu_46;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln168_fu_88_p2 == 1'd0) & (or_ln170_fu_135_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        y_2_out_ap_vld = 1'b1;
    end else begin
        y_2_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start_int == 1'b0);
end

assign ap_done = ap_done_sig;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign icmp_ln168_fu_88_p2 = ((ap_sig_allocacmp_ky_1 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln170_fu_123_p2 = (($signed(y_fu_104_p2) < $signed(y_max_i)) ? 1'b1 : 1'b0);

assign ky_2_fu_94_p2 = (ap_sig_allocacmp_ky_1 + 2'd1);

assign or_ln170_fu_135_p2 = (xor_ln170_fu_129_p2 | tmp_2_fu_115_p3);

assign tmp_2_fu_115_p3 = y_fu_104_p2[32'd31];

assign xor_ln170_fu_129_p2 = (icmp_ln170_fu_123_p2 ^ 1'd1);

assign y_2_out = y_fu_104_p2[30:0];

assign y_fu_104_p2 = (zext_ln168_fu_100_p1 + empty);

assign zext_ln168_fu_100_p1 = ap_sig_allocacmp_ky_1;

endmodule //execute_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_168_2
