// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="execute_execute,hls_ip_2024_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcvu9p-flga2104-2L-e,HLS_INPUT_CLOCK=15.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=10.950000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=1,HLS_SYN_DSP=0,HLS_SYN_FF=1575,HLS_SYN_LUT=2276,HLS_VERSION=2024_2}" *)

module execute (
        ap_clk,
        ap_rst_n,
        m_axi_data_mem_AWVALID,
        m_axi_data_mem_AWREADY,
        m_axi_data_mem_AWADDR,
        m_axi_data_mem_AWID,
        m_axi_data_mem_AWLEN,
        m_axi_data_mem_AWSIZE,
        m_axi_data_mem_AWBURST,
        m_axi_data_mem_AWLOCK,
        m_axi_data_mem_AWCACHE,
        m_axi_data_mem_AWPROT,
        m_axi_data_mem_AWQOS,
        m_axi_data_mem_AWREGION,
        m_axi_data_mem_AWUSER,
        m_axi_data_mem_WVALID,
        m_axi_data_mem_WREADY,
        m_axi_data_mem_WDATA,
        m_axi_data_mem_WSTRB,
        m_axi_data_mem_WLAST,
        m_axi_data_mem_WID,
        m_axi_data_mem_WUSER,
        m_axi_data_mem_ARVALID,
        m_axi_data_mem_ARREADY,
        m_axi_data_mem_ARADDR,
        m_axi_data_mem_ARID,
        m_axi_data_mem_ARLEN,
        m_axi_data_mem_ARSIZE,
        m_axi_data_mem_ARBURST,
        m_axi_data_mem_ARLOCK,
        m_axi_data_mem_ARCACHE,
        m_axi_data_mem_ARPROT,
        m_axi_data_mem_ARQOS,
        m_axi_data_mem_ARREGION,
        m_axi_data_mem_ARUSER,
        m_axi_data_mem_RVALID,
        m_axi_data_mem_RREADY,
        m_axi_data_mem_RDATA,
        m_axi_data_mem_RLAST,
        m_axi_data_mem_RID,
        m_axi_data_mem_RUSER,
        m_axi_data_mem_RRESP,
        m_axi_data_mem_BVALID,
        m_axi_data_mem_BREADY,
        m_axi_data_mem_BRESP,
        m_axi_data_mem_BID,
        m_axi_data_mem_BUSER,
        stream_o_TDATA,
        stream_o_TVALID,
        stream_o_TREADY,
        stream_o_TKEEP,
        stream_o_TSTRB,
        stream_o_TUSER,
        stream_o_TLAST,
        stream_o_TID,
        stream_o_TDEST,
        s_axi_cfg_port_AWVALID,
        s_axi_cfg_port_AWREADY,
        s_axi_cfg_port_AWADDR,
        s_axi_cfg_port_WVALID,
        s_axi_cfg_port_WREADY,
        s_axi_cfg_port_WDATA,
        s_axi_cfg_port_WSTRB,
        s_axi_cfg_port_ARVALID,
        s_axi_cfg_port_ARREADY,
        s_axi_cfg_port_ARADDR,
        s_axi_cfg_port_RVALID,
        s_axi_cfg_port_RREADY,
        s_axi_cfg_port_RDATA,
        s_axi_cfg_port_RRESP,
        s_axi_cfg_port_BVALID,
        s_axi_cfg_port_BREADY,
        s_axi_cfg_port_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;
parameter    C_S_AXI_CFG_PORT_DATA_WIDTH = 32;
parameter    C_S_AXI_CFG_PORT_ADDR_WIDTH = 6;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_DATA_MEM_ID_WIDTH = 1;
parameter    C_M_AXI_DATA_MEM_ADDR_WIDTH = 32;
parameter    C_M_AXI_DATA_MEM_DATA_WIDTH = 32;
parameter    C_M_AXI_DATA_MEM_AWUSER_WIDTH = 1;
parameter    C_M_AXI_DATA_MEM_ARUSER_WIDTH = 1;
parameter    C_M_AXI_DATA_MEM_WUSER_WIDTH = 1;
parameter    C_M_AXI_DATA_MEM_RUSER_WIDTH = 1;
parameter    C_M_AXI_DATA_MEM_BUSER_WIDTH = 1;
parameter    C_M_AXI_DATA_MEM_USER_VALUE = 0;
parameter    C_M_AXI_DATA_MEM_PROT_VALUE = 0;
parameter    C_M_AXI_DATA_MEM_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CFG_PORT_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_DATA_MEM_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
output   m_axi_data_mem_AWVALID;
input   m_axi_data_mem_AWREADY;
output  [C_M_AXI_DATA_MEM_ADDR_WIDTH - 1:0] m_axi_data_mem_AWADDR;
output  [C_M_AXI_DATA_MEM_ID_WIDTH - 1:0] m_axi_data_mem_AWID;
output  [7:0] m_axi_data_mem_AWLEN;
output  [2:0] m_axi_data_mem_AWSIZE;
output  [1:0] m_axi_data_mem_AWBURST;
output  [1:0] m_axi_data_mem_AWLOCK;
output  [3:0] m_axi_data_mem_AWCACHE;
output  [2:0] m_axi_data_mem_AWPROT;
output  [3:0] m_axi_data_mem_AWQOS;
output  [3:0] m_axi_data_mem_AWREGION;
output  [C_M_AXI_DATA_MEM_AWUSER_WIDTH - 1:0] m_axi_data_mem_AWUSER;
output   m_axi_data_mem_WVALID;
input   m_axi_data_mem_WREADY;
output  [C_M_AXI_DATA_MEM_DATA_WIDTH - 1:0] m_axi_data_mem_WDATA;
output  [C_M_AXI_DATA_MEM_WSTRB_WIDTH - 1:0] m_axi_data_mem_WSTRB;
output   m_axi_data_mem_WLAST;
output  [C_M_AXI_DATA_MEM_ID_WIDTH - 1:0] m_axi_data_mem_WID;
output  [C_M_AXI_DATA_MEM_WUSER_WIDTH - 1:0] m_axi_data_mem_WUSER;
output   m_axi_data_mem_ARVALID;
input   m_axi_data_mem_ARREADY;
output  [C_M_AXI_DATA_MEM_ADDR_WIDTH - 1:0] m_axi_data_mem_ARADDR;
output  [C_M_AXI_DATA_MEM_ID_WIDTH - 1:0] m_axi_data_mem_ARID;
output  [7:0] m_axi_data_mem_ARLEN;
output  [2:0] m_axi_data_mem_ARSIZE;
output  [1:0] m_axi_data_mem_ARBURST;
output  [1:0] m_axi_data_mem_ARLOCK;
output  [3:0] m_axi_data_mem_ARCACHE;
output  [2:0] m_axi_data_mem_ARPROT;
output  [3:0] m_axi_data_mem_ARQOS;
output  [3:0] m_axi_data_mem_ARREGION;
output  [C_M_AXI_DATA_MEM_ARUSER_WIDTH - 1:0] m_axi_data_mem_ARUSER;
input   m_axi_data_mem_RVALID;
output   m_axi_data_mem_RREADY;
input  [C_M_AXI_DATA_MEM_DATA_WIDTH - 1:0] m_axi_data_mem_RDATA;
input   m_axi_data_mem_RLAST;
input  [C_M_AXI_DATA_MEM_ID_WIDTH - 1:0] m_axi_data_mem_RID;
input  [C_M_AXI_DATA_MEM_RUSER_WIDTH - 1:0] m_axi_data_mem_RUSER;
input  [1:0] m_axi_data_mem_RRESP;
input   m_axi_data_mem_BVALID;
output   m_axi_data_mem_BREADY;
input  [1:0] m_axi_data_mem_BRESP;
input  [C_M_AXI_DATA_MEM_ID_WIDTH - 1:0] m_axi_data_mem_BID;
input  [C_M_AXI_DATA_MEM_BUSER_WIDTH - 1:0] m_axi_data_mem_BUSER;
output  [23:0] stream_o_TDATA;
output   stream_o_TVALID;
input   stream_o_TREADY;
output  [2:0] stream_o_TKEEP;
output  [2:0] stream_o_TSTRB;
output  [31:0] stream_o_TUSER;
output  [0:0] stream_o_TLAST;
output  [0:0] stream_o_TID;
output  [0:0] stream_o_TDEST;
input   s_axi_cfg_port_AWVALID;
output   s_axi_cfg_port_AWREADY;
input  [C_S_AXI_CFG_PORT_ADDR_WIDTH - 1:0] s_axi_cfg_port_AWADDR;
input   s_axi_cfg_port_WVALID;
output   s_axi_cfg_port_WREADY;
input  [C_S_AXI_CFG_PORT_DATA_WIDTH - 1:0] s_axi_cfg_port_WDATA;
input  [C_S_AXI_CFG_PORT_WSTRB_WIDTH - 1:0] s_axi_cfg_port_WSTRB;
input   s_axi_cfg_port_ARVALID;
output   s_axi_cfg_port_ARREADY;
input  [C_S_AXI_CFG_PORT_ADDR_WIDTH - 1:0] s_axi_cfg_port_ARADDR;
output   s_axi_cfg_port_RVALID;
input   s_axi_cfg_port_RREADY;
output  [C_S_AXI_CFG_PORT_DATA_WIDTH - 1:0] s_axi_cfg_port_RDATA;
output  [1:0] s_axi_cfg_port_RRESP;
output   s_axi_cfg_port_BVALID;
input   s_axi_cfg_port_BREADY;
output  [1:0] s_axi_cfg_port_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [31:0] data_port;
wire   [31:0] frame_cnt;
wire   [0:0] end_of_stream;
reg    stream_o_TDATA_blk_n;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
reg   [0:0] end_of_stream_read_reg_238;
reg   [31:0] data_port_read_reg_242;
wire   [50:0] add_ln20_1_fu_231_p2;
reg   [50:0] add_ln20_1_reg_247;
wire    grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_ap_start;
wire    grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_ap_done;
wire    grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_ap_idle;
wire    grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_ap_ready;
wire    grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_m_axi_data_mem_0_AWVALID;
wire   [31:0] grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_m_axi_data_mem_0_AWADDR;
wire   [0:0] grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_m_axi_data_mem_0_AWID;
wire   [31:0] grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_m_axi_data_mem_0_AWLEN;
wire   [2:0] grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_m_axi_data_mem_0_AWSIZE;
wire   [1:0] grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_m_axi_data_mem_0_AWBURST;
wire   [1:0] grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_m_axi_data_mem_0_AWLOCK;
wire   [3:0] grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_m_axi_data_mem_0_AWCACHE;
wire   [2:0] grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_m_axi_data_mem_0_AWPROT;
wire   [3:0] grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_m_axi_data_mem_0_AWQOS;
wire   [3:0] grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_m_axi_data_mem_0_AWREGION;
wire   [0:0] grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_m_axi_data_mem_0_AWUSER;
wire    grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_m_axi_data_mem_0_WVALID;
wire   [31:0] grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_m_axi_data_mem_0_WDATA;
wire   [3:0] grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_m_axi_data_mem_0_WSTRB;
wire    grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_m_axi_data_mem_0_WLAST;
wire   [0:0] grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_m_axi_data_mem_0_WID;
wire   [0:0] grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_m_axi_data_mem_0_WUSER;
wire    grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_m_axi_data_mem_0_ARVALID;
wire   [31:0] grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_m_axi_data_mem_0_ARADDR;
wire   [0:0] grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_m_axi_data_mem_0_ARID;
wire   [31:0] grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_m_axi_data_mem_0_ARLEN;
wire   [2:0] grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_m_axi_data_mem_0_ARSIZE;
wire   [1:0] grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_m_axi_data_mem_0_ARBURST;
wire   [1:0] grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_m_axi_data_mem_0_ARLOCK;
wire   [3:0] grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_m_axi_data_mem_0_ARCACHE;
wire   [2:0] grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_m_axi_data_mem_0_ARPROT;
wire   [3:0] grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_m_axi_data_mem_0_ARQOS;
wire   [3:0] grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_m_axi_data_mem_0_ARREGION;
wire   [0:0] grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_m_axi_data_mem_0_ARUSER;
wire    grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_m_axi_data_mem_0_RREADY;
wire    grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_m_axi_data_mem_0_BREADY;
wire    grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_stream_o_TREADY;
wire   [23:0] grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_stream_o_TDATA;
wire    grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_stream_o_TVALID;
wire   [2:0] grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_stream_o_TKEEP;
wire   [2:0] grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_stream_o_TSTRB;
wire   [31:0] grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_stream_o_TUSER;
wire   [0:0] grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_stream_o_TLAST;
wire   [0:0] grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_stream_o_TID;
wire   [0:0] grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_stream_o_TDEST;
wire    data_mem_0_AWREADY;
wire    data_mem_0_WREADY;
reg    data_mem_0_ARVALID;
wire    data_mem_0_ARREADY;
wire    data_mem_0_RVALID;
reg    data_mem_0_RREADY;
wire   [31:0] data_mem_0_RDATA;
wire   [8:0] data_mem_0_RFIFONUM;
wire    data_mem_0_BVALID;
reg    grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_ap_start_reg;
wire    ap_CS_fsm_state2;
reg   [23:0] stream_o_TDATA_reg;
reg   [2:0] stream_o_TKEEP_reg;
reg   [2:0] stream_o_TSTRB_reg;
reg   [31:0] stream_o_TUSER_reg;
reg   [0:0] stream_o_TLAST_reg;
reg   [0:0] stream_o_TID_reg;
reg   [0:0] stream_o_TDEST_reg;
wire   [44:0] tmp_fu_183_p3;
wire   [50:0] p_shl_fu_175_p3;
wire   [50:0] zext_ln20_fu_191_p1;
wire   [42:0] tmp_1_fu_201_p3;
wire   [50:0] sub_ln20_fu_195_p2;
wire   [50:0] zext_ln20_1_fu_209_p1;
wire   [39:0] tmp_2_fu_219_p3;
wire   [50:0] add_ln20_fu_213_p2;
wire   [50:0] zext_ln20_2_fu_227_p1;
wire    regslice_both_stream_o_V_data_V_U_apdone_blk;
reg    ap_block_state4;
reg   [3:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
reg   [23:0] stream_o_TDATA_int_regslice;
reg    stream_o_TVALID_int_regslice;
wire    stream_o_TREADY_int_regslice;
wire    regslice_both_stream_o_V_data_V_U_vld_out;
wire    regslice_both_stream_o_V_keep_V_U_apdone_blk;
reg   [2:0] stream_o_TKEEP_int_regslice;
wire    regslice_both_stream_o_V_keep_V_U_ack_in_dummy;
wire    regslice_both_stream_o_V_keep_V_U_vld_out;
wire    regslice_both_stream_o_V_strb_V_U_apdone_blk;
reg   [2:0] stream_o_TSTRB_int_regslice;
wire    regslice_both_stream_o_V_strb_V_U_ack_in_dummy;
wire    regslice_both_stream_o_V_strb_V_U_vld_out;
wire    regslice_both_stream_o_V_user_V_U_apdone_blk;
reg   [31:0] stream_o_TUSER_int_regslice;
wire    regslice_both_stream_o_V_user_V_U_ack_in_dummy;
wire    regslice_both_stream_o_V_user_V_U_vld_out;
wire    regslice_both_stream_o_V_last_V_U_apdone_blk;
reg   [0:0] stream_o_TLAST_int_regslice;
wire    regslice_both_stream_o_V_last_V_U_ack_in_dummy;
wire    regslice_both_stream_o_V_last_V_U_vld_out;
wire    regslice_both_stream_o_V_id_V_U_apdone_blk;
reg   [0:0] stream_o_TID_int_regslice;
wire    regslice_both_stream_o_V_id_V_U_ack_in_dummy;
wire    regslice_both_stream_o_V_id_V_U_vld_out;
wire    regslice_both_stream_o_V_dest_V_U_apdone_blk;
reg   [0:0] stream_o_TDEST_int_regslice;
wire    regslice_both_stream_o_V_dest_V_U_ack_in_dummy;
wire    regslice_both_stream_o_V_dest_V_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd1;
#0 grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_ap_start_reg = 1'b0;
end

execute_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2 grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_ap_start),
    .ap_done(grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_ap_done),
    .ap_idle(grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_ap_idle),
    .ap_ready(grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_ap_ready),
    .m_axi_data_mem_0_AWVALID(grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_m_axi_data_mem_0_AWVALID),
    .m_axi_data_mem_0_AWREADY(1'b0),
    .m_axi_data_mem_0_AWADDR(grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_m_axi_data_mem_0_AWADDR),
    .m_axi_data_mem_0_AWID(grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_m_axi_data_mem_0_AWID),
    .m_axi_data_mem_0_AWLEN(grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_m_axi_data_mem_0_AWLEN),
    .m_axi_data_mem_0_AWSIZE(grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_m_axi_data_mem_0_AWSIZE),
    .m_axi_data_mem_0_AWBURST(grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_m_axi_data_mem_0_AWBURST),
    .m_axi_data_mem_0_AWLOCK(grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_m_axi_data_mem_0_AWLOCK),
    .m_axi_data_mem_0_AWCACHE(grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_m_axi_data_mem_0_AWCACHE),
    .m_axi_data_mem_0_AWPROT(grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_m_axi_data_mem_0_AWPROT),
    .m_axi_data_mem_0_AWQOS(grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_m_axi_data_mem_0_AWQOS),
    .m_axi_data_mem_0_AWREGION(grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_m_axi_data_mem_0_AWREGION),
    .m_axi_data_mem_0_AWUSER(grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_m_axi_data_mem_0_AWUSER),
    .m_axi_data_mem_0_WVALID(grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_m_axi_data_mem_0_WVALID),
    .m_axi_data_mem_0_WREADY(1'b0),
    .m_axi_data_mem_0_WDATA(grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_m_axi_data_mem_0_WDATA),
    .m_axi_data_mem_0_WSTRB(grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_m_axi_data_mem_0_WSTRB),
    .m_axi_data_mem_0_WLAST(grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_m_axi_data_mem_0_WLAST),
    .m_axi_data_mem_0_WID(grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_m_axi_data_mem_0_WID),
    .m_axi_data_mem_0_WUSER(grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_m_axi_data_mem_0_WUSER),
    .m_axi_data_mem_0_ARVALID(grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_m_axi_data_mem_0_ARVALID),
    .m_axi_data_mem_0_ARREADY(data_mem_0_ARREADY),
    .m_axi_data_mem_0_ARADDR(grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_m_axi_data_mem_0_ARADDR),
    .m_axi_data_mem_0_ARID(grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_m_axi_data_mem_0_ARID),
    .m_axi_data_mem_0_ARLEN(grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_m_axi_data_mem_0_ARLEN),
    .m_axi_data_mem_0_ARSIZE(grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_m_axi_data_mem_0_ARSIZE),
    .m_axi_data_mem_0_ARBURST(grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_m_axi_data_mem_0_ARBURST),
    .m_axi_data_mem_0_ARLOCK(grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_m_axi_data_mem_0_ARLOCK),
    .m_axi_data_mem_0_ARCACHE(grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_m_axi_data_mem_0_ARCACHE),
    .m_axi_data_mem_0_ARPROT(grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_m_axi_data_mem_0_ARPROT),
    .m_axi_data_mem_0_ARQOS(grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_m_axi_data_mem_0_ARQOS),
    .m_axi_data_mem_0_ARREGION(grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_m_axi_data_mem_0_ARREGION),
    .m_axi_data_mem_0_ARUSER(grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_m_axi_data_mem_0_ARUSER),
    .m_axi_data_mem_0_RVALID(data_mem_0_RVALID),
    .m_axi_data_mem_0_RREADY(grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_m_axi_data_mem_0_RREADY),
    .m_axi_data_mem_0_RDATA(data_mem_0_RDATA),
    .m_axi_data_mem_0_RLAST(1'b0),
    .m_axi_data_mem_0_RID(1'd0),
    .m_axi_data_mem_0_RFIFONUM(data_mem_0_RFIFONUM),
    .m_axi_data_mem_0_RUSER(1'd0),
    .m_axi_data_mem_0_RRESP(2'd0),
    .m_axi_data_mem_0_BVALID(1'b0),
    .m_axi_data_mem_0_BREADY(grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_m_axi_data_mem_0_BREADY),
    .m_axi_data_mem_0_BRESP(2'd0),
    .m_axi_data_mem_0_BID(1'd0),
    .m_axi_data_mem_0_BUSER(1'd0),
    .stream_o_TREADY(grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_stream_o_TREADY),
    .mul_ln20(add_ln20_1_reg_247),
    .data_port(data_port_read_reg_242),
    .stream_o_TDATA(grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_stream_o_TDATA),
    .stream_o_TVALID(grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_stream_o_TVALID),
    .stream_o_TKEEP(grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_stream_o_TKEEP),
    .stream_o_TSTRB(grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_stream_o_TSTRB),
    .stream_o_TUSER(grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_stream_o_TUSER),
    .stream_o_TLAST(grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_stream_o_TLAST),
    .stream_o_TID(grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_stream_o_TID),
    .stream_o_TDEST(grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_stream_o_TDEST)
);

execute_cfg_port_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CFG_PORT_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CFG_PORT_DATA_WIDTH ))
cfg_port_s_axi_U(
    .AWVALID(s_axi_cfg_port_AWVALID),
    .AWREADY(s_axi_cfg_port_AWREADY),
    .AWADDR(s_axi_cfg_port_AWADDR),
    .WVALID(s_axi_cfg_port_WVALID),
    .WREADY(s_axi_cfg_port_WREADY),
    .WDATA(s_axi_cfg_port_WDATA),
    .WSTRB(s_axi_cfg_port_WSTRB),
    .ARVALID(s_axi_cfg_port_ARVALID),
    .ARREADY(s_axi_cfg_port_ARREADY),
    .ARADDR(s_axi_cfg_port_ARADDR),
    .RVALID(s_axi_cfg_port_RVALID),
    .RREADY(s_axi_cfg_port_RREADY),
    .RDATA(s_axi_cfg_port_RDATA),
    .RRESP(s_axi_cfg_port_RRESP),
    .BVALID(s_axi_cfg_port_BVALID),
    .BREADY(s_axi_cfg_port_BREADY),
    .BRESP(s_axi_cfg_port_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .data_port(data_port),
    .frame_cnt(frame_cnt),
    .end_of_stream(end_of_stream),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

execute_data_mem_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 7 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_DATA_MEM_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_DATA_MEM_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_DATA_MEM_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_DATA_MEM_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_DATA_MEM_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_DATA_MEM_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_DATA_MEM_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_DATA_MEM_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_DATA_MEM_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_DATA_MEM_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_DATA_MEM_CACHE_VALUE ),
    .CH0_USER_RFIFONUM_WIDTH( 9 ),
    .CH0_USER_DW( 32 ),
    .CH0_USER_AW( 32 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 0 ))
data_mem_m_axi_U(
    .AWVALID(m_axi_data_mem_AWVALID),
    .AWREADY(m_axi_data_mem_AWREADY),
    .AWADDR(m_axi_data_mem_AWADDR),
    .AWID(m_axi_data_mem_AWID),
    .AWLEN(m_axi_data_mem_AWLEN),
    .AWSIZE(m_axi_data_mem_AWSIZE),
    .AWBURST(m_axi_data_mem_AWBURST),
    .AWLOCK(m_axi_data_mem_AWLOCK),
    .AWCACHE(m_axi_data_mem_AWCACHE),
    .AWPROT(m_axi_data_mem_AWPROT),
    .AWQOS(m_axi_data_mem_AWQOS),
    .AWREGION(m_axi_data_mem_AWREGION),
    .AWUSER(m_axi_data_mem_AWUSER),
    .WVALID(m_axi_data_mem_WVALID),
    .WREADY(m_axi_data_mem_WREADY),
    .WDATA(m_axi_data_mem_WDATA),
    .WSTRB(m_axi_data_mem_WSTRB),
    .WLAST(m_axi_data_mem_WLAST),
    .WID(m_axi_data_mem_WID),
    .WUSER(m_axi_data_mem_WUSER),
    .ARVALID(m_axi_data_mem_ARVALID),
    .ARREADY(m_axi_data_mem_ARREADY),
    .ARADDR(m_axi_data_mem_ARADDR),
    .ARID(m_axi_data_mem_ARID),
    .ARLEN(m_axi_data_mem_ARLEN),
    .ARSIZE(m_axi_data_mem_ARSIZE),
    .ARBURST(m_axi_data_mem_ARBURST),
    .ARLOCK(m_axi_data_mem_ARLOCK),
    .ARCACHE(m_axi_data_mem_ARCACHE),
    .ARPROT(m_axi_data_mem_ARPROT),
    .ARQOS(m_axi_data_mem_ARQOS),
    .ARREGION(m_axi_data_mem_ARREGION),
    .ARUSER(m_axi_data_mem_ARUSER),
    .RVALID(m_axi_data_mem_RVALID),
    .RREADY(m_axi_data_mem_RREADY),
    .RDATA(m_axi_data_mem_RDATA),
    .RLAST(m_axi_data_mem_RLAST),
    .RID(m_axi_data_mem_RID),
    .RUSER(m_axi_data_mem_RUSER),
    .RRESP(m_axi_data_mem_RRESP),
    .BVALID(m_axi_data_mem_BVALID),
    .BREADY(m_axi_data_mem_BREADY),
    .BRESP(m_axi_data_mem_BRESP),
    .BID(m_axi_data_mem_BID),
    .BUSER(m_axi_data_mem_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_CH0_ARVALID(data_mem_0_ARVALID),
    .I_CH0_ARREADY(data_mem_0_ARREADY),
    .I_CH0_ARADDR(grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_m_axi_data_mem_0_ARADDR),
    .I_CH0_ARLEN(grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_m_axi_data_mem_0_ARLEN),
    .I_CH0_RVALID(data_mem_0_RVALID),
    .I_CH0_RREADY(data_mem_0_RREADY),
    .I_CH0_RDATA(data_mem_0_RDATA),
    .I_CH0_RFIFONUM(data_mem_0_RFIFONUM),
    .I_CH0_AWVALID(1'b0),
    .I_CH0_AWREADY(data_mem_0_AWREADY),
    .I_CH0_AWADDR(32'd0),
    .I_CH0_AWLEN(32'd0),
    .I_CH0_WVALID(1'b0),
    .I_CH0_WREADY(data_mem_0_WREADY),
    .I_CH0_WDATA(32'd0),
    .I_CH0_WSTRB(4'd0),
    .I_CH0_BVALID(data_mem_0_BVALID),
    .I_CH0_BREADY(1'b0)
);

execute_regslice_both #(
    .DataWidth( 24 ))
regslice_both_stream_o_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_o_TDATA_int_regslice),
    .vld_in(stream_o_TVALID_int_regslice),
    .ack_in(stream_o_TREADY_int_regslice),
    .data_out(stream_o_TDATA),
    .vld_out(regslice_both_stream_o_V_data_V_U_vld_out),
    .ack_out(stream_o_TREADY),
    .apdone_blk(regslice_both_stream_o_V_data_V_U_apdone_blk)
);

execute_regslice_both #(
    .DataWidth( 3 ))
regslice_both_stream_o_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_o_TKEEP_int_regslice),
    .vld_in(stream_o_TVALID_int_regslice),
    .ack_in(regslice_both_stream_o_V_keep_V_U_ack_in_dummy),
    .data_out(stream_o_TKEEP),
    .vld_out(regslice_both_stream_o_V_keep_V_U_vld_out),
    .ack_out(stream_o_TREADY),
    .apdone_blk(regslice_both_stream_o_V_keep_V_U_apdone_blk)
);

execute_regslice_both #(
    .DataWidth( 3 ))
regslice_both_stream_o_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_o_TSTRB_int_regslice),
    .vld_in(stream_o_TVALID_int_regslice),
    .ack_in(regslice_both_stream_o_V_strb_V_U_ack_in_dummy),
    .data_out(stream_o_TSTRB),
    .vld_out(regslice_both_stream_o_V_strb_V_U_vld_out),
    .ack_out(stream_o_TREADY),
    .apdone_blk(regslice_both_stream_o_V_strb_V_U_apdone_blk)
);

execute_regslice_both #(
    .DataWidth( 32 ))
regslice_both_stream_o_V_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_o_TUSER_int_regslice),
    .vld_in(stream_o_TVALID_int_regslice),
    .ack_in(regslice_both_stream_o_V_user_V_U_ack_in_dummy),
    .data_out(stream_o_TUSER),
    .vld_out(regslice_both_stream_o_V_user_V_U_vld_out),
    .ack_out(stream_o_TREADY),
    .apdone_blk(regslice_both_stream_o_V_user_V_U_apdone_blk)
);

execute_regslice_both #(
    .DataWidth( 1 ))
regslice_both_stream_o_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_o_TLAST_int_regslice),
    .vld_in(stream_o_TVALID_int_regslice),
    .ack_in(regslice_both_stream_o_V_last_V_U_ack_in_dummy),
    .data_out(stream_o_TLAST),
    .vld_out(regslice_both_stream_o_V_last_V_U_vld_out),
    .ack_out(stream_o_TREADY),
    .apdone_blk(regslice_both_stream_o_V_last_V_U_apdone_blk)
);

execute_regslice_both #(
    .DataWidth( 1 ))
regslice_both_stream_o_V_id_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_o_TID_int_regslice),
    .vld_in(stream_o_TVALID_int_regslice),
    .ack_in(regslice_both_stream_o_V_id_V_U_ack_in_dummy),
    .data_out(stream_o_TID),
    .vld_out(regslice_both_stream_o_V_id_V_U_vld_out),
    .ack_out(stream_o_TREADY),
    .apdone_blk(regslice_both_stream_o_V_id_V_U_apdone_blk)
);

execute_regslice_both #(
    .DataWidth( 1 ))
regslice_both_stream_o_V_dest_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_o_TDEST_int_regslice),
    .vld_in(stream_o_TVALID_int_regslice),
    .ack_in(regslice_both_stream_o_V_dest_V_U_ack_in_dummy),
    .data_out(stream_o_TDEST),
    .vld_out(regslice_both_stream_o_V_dest_V_U_vld_out),
    .ack_out(stream_o_TREADY),
    .apdone_blk(regslice_both_stream_o_V_dest_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_ap_start_reg <= 1'b1;
        end else if ((grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_ap_ready == 1'b1)) begin
            grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        add_ln20_1_reg_247[50 : 8] <= add_ln20_1_fu_231_p2[50 : 8];
        data_port_read_reg_242 <= data_port;
        end_of_stream_read_reg_238 <= end_of_stream;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_stream_o_TVALID == 1'b1))) begin
        stream_o_TDATA_reg <= grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_stream_o_TDATA;
        stream_o_TDEST_reg <= grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_stream_o_TDEST;
        stream_o_TID_reg <= grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_stream_o_TID;
        stream_o_TKEEP_reg <= grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_stream_o_TKEEP;
        stream_o_TLAST_reg <= grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_stream_o_TLAST;
        stream_o_TSTRB_reg <= grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_stream_o_TSTRB;
        stream_o_TUSER_reg <= grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_stream_o_TUSER;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if ((stream_o_TREADY_int_regslice == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state4)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state4) & (1'b1 == ap_CS_fsm_state4))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state4) & (1'b1 == ap_CS_fsm_state4))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state1))) begin
        data_mem_0_ARVALID = grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_m_axi_data_mem_0_ARVALID;
    end else begin
        data_mem_0_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state1))) begin
        data_mem_0_RREADY = grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_m_axi_data_mem_0_RREADY;
    end else begin
        data_mem_0_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | ((1'b1 == ap_CS_fsm_state4) & (end_of_stream_read_reg_238 == 1'd1)))) begin
        stream_o_TDATA_blk_n = stream_o_TREADY_int_regslice;
    end else begin
        stream_o_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((stream_o_TREADY_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        stream_o_TDATA_int_regslice = 24'd11189196;
    end else if (((1'b1 == ap_CS_fsm_state2) & (grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_stream_o_TVALID == 1'b1))) begin
        stream_o_TDATA_int_regslice = grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_stream_o_TDATA;
    end else begin
        stream_o_TDATA_int_regslice = stream_o_TDATA_reg;
    end
end

always @ (*) begin
    if (((stream_o_TREADY_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        stream_o_TDEST_int_regslice = 1'd0;
    end else if (((1'b1 == ap_CS_fsm_state2) & (grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_stream_o_TVALID == 1'b1))) begin
        stream_o_TDEST_int_regslice = grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_stream_o_TDEST;
    end else begin
        stream_o_TDEST_int_regslice = stream_o_TDEST_reg;
    end
end

always @ (*) begin
    if (((stream_o_TREADY_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        stream_o_TID_int_regslice = 1'd0;
    end else if (((1'b1 == ap_CS_fsm_state2) & (grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_stream_o_TVALID == 1'b1))) begin
        stream_o_TID_int_regslice = grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_stream_o_TID;
    end else begin
        stream_o_TID_int_regslice = stream_o_TID_reg;
    end
end

always @ (*) begin
    if (((stream_o_TREADY_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        stream_o_TKEEP_int_regslice = 3'd0;
    end else if (((1'b1 == ap_CS_fsm_state2) & (grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_stream_o_TVALID == 1'b1))) begin
        stream_o_TKEEP_int_regslice = grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_stream_o_TKEEP;
    end else begin
        stream_o_TKEEP_int_regslice = stream_o_TKEEP_reg;
    end
end

always @ (*) begin
    if (((stream_o_TREADY_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        stream_o_TLAST_int_regslice = 1'd0;
    end else if (((1'b1 == ap_CS_fsm_state2) & (grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_stream_o_TVALID == 1'b1))) begin
        stream_o_TLAST_int_regslice = grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_stream_o_TLAST;
    end else begin
        stream_o_TLAST_int_regslice = stream_o_TLAST_reg;
    end
end

always @ (*) begin
    if (((stream_o_TREADY_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        stream_o_TSTRB_int_regslice = 3'd1;
    end else if (((1'b1 == ap_CS_fsm_state2) & (grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_stream_o_TVALID == 1'b1))) begin
        stream_o_TSTRB_int_regslice = grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_stream_o_TSTRB;
    end else begin
        stream_o_TSTRB_int_regslice = stream_o_TSTRB_reg;
    end
end

always @ (*) begin
    if (((stream_o_TREADY_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        stream_o_TUSER_int_regslice = 32'd1;
    end else if (((1'b1 == ap_CS_fsm_state2) & (grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_stream_o_TVALID == 1'b1))) begin
        stream_o_TUSER_int_regslice = grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_stream_o_TUSER;
    end else begin
        stream_o_TUSER_int_regslice = stream_o_TUSER_reg;
    end
end

always @ (*) begin
    if (((stream_o_TREADY_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        stream_o_TVALID_int_regslice = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        stream_o_TVALID_int_regslice = grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_stream_o_TVALID;
    end else begin
        stream_o_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_ap_done == 1'b1) & (end_of_stream_read_reg_238 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else if (((1'b1 == ap_CS_fsm_state2) & (grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_ap_done == 1'b1) & (end_of_stream_read_reg_238 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((stream_o_TREADY_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((1'b0 == ap_block_state4) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln20_1_fu_231_p2 = (add_ln20_fu_213_p2 + zext_ln20_2_fu_227_p1);

assign add_ln20_fu_213_p2 = (sub_ln20_fu_195_p2 + zext_ln20_1_fu_209_p1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

always @ (*) begin
    ap_block_state4 = ((regslice_both_stream_o_V_data_V_U_apdone_blk == 1'b1) | ((stream_o_TREADY_int_regslice == 1'b0) & (end_of_stream_read_reg_238 == 1'd1)));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_ap_start = grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_ap_start_reg;

assign grp_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2_fu_152_stream_o_TREADY = (stream_o_TREADY_int_regslice & ap_CS_fsm_state2);

assign p_shl_fu_175_p3 = {{frame_cnt}, {19'd0}};

assign stream_o_TVALID = regslice_both_stream_o_V_data_V_U_vld_out;

assign sub_ln20_fu_195_p2 = (p_shl_fu_175_p3 - zext_ln20_fu_191_p1);

assign tmp_1_fu_201_p3 = {{frame_cnt}, {11'd0}};

assign tmp_2_fu_219_p3 = {{frame_cnt}, {8'd0}};

assign tmp_fu_183_p3 = {{frame_cnt}, {13'd0}};

assign zext_ln20_1_fu_209_p1 = tmp_1_fu_201_p3;

assign zext_ln20_2_fu_227_p1 = tmp_2_fu_219_p3;

assign zext_ln20_fu_191_p1 = tmp_fu_183_p3;

always @ (posedge ap_clk) begin
    add_ln20_1_reg_247[7:0] <= 8'b00000000;
end


reg find_kernel_block = 0;
// synthesis translate_off
`include "execute_hls_deadlock_kernel_monitor_top.vh"
// synthesis translate_on

endmodule //execute

