// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module execute_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_data_mem_0_AWVALID,
        m_axi_data_mem_0_AWREADY,
        m_axi_data_mem_0_AWADDR,
        m_axi_data_mem_0_AWID,
        m_axi_data_mem_0_AWLEN,
        m_axi_data_mem_0_AWSIZE,
        m_axi_data_mem_0_AWBURST,
        m_axi_data_mem_0_AWLOCK,
        m_axi_data_mem_0_AWCACHE,
        m_axi_data_mem_0_AWPROT,
        m_axi_data_mem_0_AWQOS,
        m_axi_data_mem_0_AWREGION,
        m_axi_data_mem_0_AWUSER,
        m_axi_data_mem_0_WVALID,
        m_axi_data_mem_0_WREADY,
        m_axi_data_mem_0_WDATA,
        m_axi_data_mem_0_WSTRB,
        m_axi_data_mem_0_WLAST,
        m_axi_data_mem_0_WID,
        m_axi_data_mem_0_WUSER,
        m_axi_data_mem_0_ARVALID,
        m_axi_data_mem_0_ARREADY,
        m_axi_data_mem_0_ARADDR,
        m_axi_data_mem_0_ARID,
        m_axi_data_mem_0_ARLEN,
        m_axi_data_mem_0_ARSIZE,
        m_axi_data_mem_0_ARBURST,
        m_axi_data_mem_0_ARLOCK,
        m_axi_data_mem_0_ARCACHE,
        m_axi_data_mem_0_ARPROT,
        m_axi_data_mem_0_ARQOS,
        m_axi_data_mem_0_ARREGION,
        m_axi_data_mem_0_ARUSER,
        m_axi_data_mem_0_RVALID,
        m_axi_data_mem_0_RREADY,
        m_axi_data_mem_0_RDATA,
        m_axi_data_mem_0_RLAST,
        m_axi_data_mem_0_RID,
        m_axi_data_mem_0_RFIFONUM,
        m_axi_data_mem_0_RUSER,
        m_axi_data_mem_0_RRESP,
        m_axi_data_mem_0_BVALID,
        m_axi_data_mem_0_BREADY,
        m_axi_data_mem_0_BRESP,
        m_axi_data_mem_0_BID,
        m_axi_data_mem_0_BUSER,
        stream_o_TREADY,
        mul_ln20,
        data_port,
        stream_o_TDATA,
        stream_o_TVALID,
        stream_o_TKEEP,
        stream_o_TSTRB,
        stream_o_TUSER,
        stream_o_TLAST,
        stream_o_TID,
        stream_o_TDEST
);

parameter    ap_ST_fsm_pp0_stage0 = 4'd1;
parameter    ap_ST_fsm_pp0_stage1 = 4'd2;
parameter    ap_ST_fsm_pp0_stage2 = 4'd4;
parameter    ap_ST_fsm_pp0_stage3 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_data_mem_0_AWVALID;
input   m_axi_data_mem_0_AWREADY;
output  [31:0] m_axi_data_mem_0_AWADDR;
output  [0:0] m_axi_data_mem_0_AWID;
output  [31:0] m_axi_data_mem_0_AWLEN;
output  [2:0] m_axi_data_mem_0_AWSIZE;
output  [1:0] m_axi_data_mem_0_AWBURST;
output  [1:0] m_axi_data_mem_0_AWLOCK;
output  [3:0] m_axi_data_mem_0_AWCACHE;
output  [2:0] m_axi_data_mem_0_AWPROT;
output  [3:0] m_axi_data_mem_0_AWQOS;
output  [3:0] m_axi_data_mem_0_AWREGION;
output  [0:0] m_axi_data_mem_0_AWUSER;
output   m_axi_data_mem_0_WVALID;
input   m_axi_data_mem_0_WREADY;
output  [31:0] m_axi_data_mem_0_WDATA;
output  [3:0] m_axi_data_mem_0_WSTRB;
output   m_axi_data_mem_0_WLAST;
output  [0:0] m_axi_data_mem_0_WID;
output  [0:0] m_axi_data_mem_0_WUSER;
output   m_axi_data_mem_0_ARVALID;
input   m_axi_data_mem_0_ARREADY;
output  [31:0] m_axi_data_mem_0_ARADDR;
output  [0:0] m_axi_data_mem_0_ARID;
output  [31:0] m_axi_data_mem_0_ARLEN;
output  [2:0] m_axi_data_mem_0_ARSIZE;
output  [1:0] m_axi_data_mem_0_ARBURST;
output  [1:0] m_axi_data_mem_0_ARLOCK;
output  [3:0] m_axi_data_mem_0_ARCACHE;
output  [2:0] m_axi_data_mem_0_ARPROT;
output  [3:0] m_axi_data_mem_0_ARQOS;
output  [3:0] m_axi_data_mem_0_ARREGION;
output  [0:0] m_axi_data_mem_0_ARUSER;
input   m_axi_data_mem_0_RVALID;
output   m_axi_data_mem_0_RREADY;
input  [31:0] m_axi_data_mem_0_RDATA;
input   m_axi_data_mem_0_RLAST;
input  [0:0] m_axi_data_mem_0_RID;
input  [8:0] m_axi_data_mem_0_RFIFONUM;
input  [0:0] m_axi_data_mem_0_RUSER;
input  [1:0] m_axi_data_mem_0_RRESP;
input   m_axi_data_mem_0_BVALID;
output   m_axi_data_mem_0_BREADY;
input  [1:0] m_axi_data_mem_0_BRESP;
input  [0:0] m_axi_data_mem_0_BID;
input  [0:0] m_axi_data_mem_0_BUSER;
input   stream_o_TREADY;
input  [50:0] mul_ln20;
input  [31:0] data_port;
output  [23:0] stream_o_TDATA;
output   stream_o_TVALID;
output  [2:0] stream_o_TKEEP;
output  [2:0] stream_o_TSTRB;
output  [31:0] stream_o_TUSER;
output  [0:0] stream_o_TLAST;
output  [0:0] stream_o_TID;
output  [0:0] stream_o_TDEST;

reg ap_idle;
reg m_axi_data_mem_0_ARVALID;
reg[31:0] m_axi_data_mem_0_ARADDR;
reg m_axi_data_mem_0_RREADY;
reg[23:0] stream_o_TDATA;
reg stream_o_TVALID;
reg[31:0] stream_o_TUSER;
reg[0:0] stream_o_TLAST;

(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage3;
reg   [0:0] icmp_ln24_reg_763;
reg    ap_block_state4_io_grp2;
reg    ap_block_pp0_stage3_subdone_grp2_done_reg;
reg    ap_block_pp0_stage3_subdone_grp2;
reg    ap_block_pp0_stage3_subdone;
reg    ap_enable_reg_pp0_iter0_reg;
reg    ap_block_pp0_stage3_subdone_grp6_done_reg;
reg    ap_block_pp0_stage3_subdone_grp6;
reg    ap_condition_exit_pp0_iter0_stage3;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    data_mem_blk_n_AR;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_pp0_stage2_grp1;
reg    ap_block_pp0_stage2_subdone_grp1_done_reg;
reg    ap_block_pp0_stage2_subdone_grp1;
reg    ap_block_pp0_stage2_subdone;
reg    data_mem_blk_n_R;
wire    ap_block_pp0_stage3_grp2;
wire    ap_block_pp0_stage0_grp3;
reg    ap_block_pp0_stage0_subdone_grp3_done_reg;
reg    ap_block_pp0_stage0_subdone_grp3;
reg    ap_block_pp0_stage0_subdone;
reg    stream_o_TDATA_blk_n;
wire    ap_block_pp0_stage3_grp6;
wire    ap_block_pp0_stage0_grp8;
reg    ap_block_pp0_stage0_subdone_grp8_done_reg;
reg    ap_block_pp0_stage0_subdone_grp8;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1_grp9;
wire    ap_block_pp0_stage2_grp10;
reg    ap_block_pp0_stage2_subdone_grp10_done_reg;
reg    ap_block_pp0_stage2_subdone_grp10;
wire    ap_block_pp0_stage0_11001_grp0;
reg    ap_block_pp0_stage0_subdone_grp0_done_reg;
wire    ap_block_pp0_stage0_subdone_grp0;
wire   [0:0] icmp_ln24_fu_282_p2;
reg    ap_block_pp0_stage1_11001;
reg   [0:0] icmp_ln24_reg_763_pp0_iter1_reg;
reg   [0:0] icmp_ln24_reg_763_pp0_iter2_reg;
wire   [0:0] icmp_ln221_fu_311_p2;
reg   [0:0] icmp_ln221_reg_767;
reg   [0:0] icmp_ln221_reg_767_pp0_iter1_reg;
reg   [0:0] icmp_ln221_reg_767_pp0_iter2_reg;
wire   [22:0] shl_ln_fu_399_p3;
reg   [22:0] shl_ln_reg_772;
reg   [29:0] trunc_ln_reg_778;
wire   [0:0] sof_fu_438_p2;
reg   [0:0] sof_reg_783;
reg   [0:0] sof_reg_783_pp0_iter1_reg;
reg   [0:0] sof_reg_783_pp0_iter2_reg;
wire   [0:0] px_last_fu_462_p2;
reg   [0:0] px_last_reg_788;
reg   [0:0] px_last_reg_788_pp0_iter1_reg;
reg   [0:0] px_last_reg_788_pp0_iter2_reg;
reg   [0:0] px_last_reg_788_pp0_iter3_reg;
reg    ap_block_state3_io_grp1;
reg    ap_block_pp0_stage2_11001_grp1;
reg   [29:0] trunc_ln1_reg_799;
wire    ap_block_pp0_stage2_11001_grp0;
reg    ap_block_pp0_stage2_subdone_grp0_done_reg;
wire    ap_block_pp0_stage2_subdone_grp0;
reg   [29:0] trunc_ln2_reg_804;
reg    ap_block_pp0_stage3_11001_grp2;
reg    ap_block_state5_io_grp3;
reg    ap_block_pp0_stage0_11001_grp3;
reg   [23:0] px_data_reg_821;
wire   [7:0] trunc_ln249_fu_617_p1;
reg   [7:0] trunc_ln249_reg_826;
wire   [31:0] px_user_fu_641_p3;
reg   [31:0] px_user_reg_831;
reg    ap_block_pp0_stage3_11001_grp6;
reg   [15:0] tmp_2_reg_836;
wire   [15:0] trunc_ln261_fu_659_p1;
reg   [15:0] trunc_ln261_reg_841;
reg   [7:0] tmp_4_reg_846;
wire   [23:0] px_data_3_fu_685_p1;
reg   [23:0] px_data_3_reg_851;
wire  signed [31:0] sext_ln230_fu_529_p1;
wire  signed [31:0] sext_ln231_fu_587_p1;
wire  signed [31:0] sext_ln232_fu_597_p1;
reg   [10:0] j_fu_134;
wire   [10:0] j_2_fu_468_p2;
wire    ap_loop_init;
wire    ap_block_pp0_stage1;
reg   [20:0] offset_fu_138;
wire   [20:0] add_ln232_fu_426_p2;
reg   [20:0] add_ln2214_fu_142;
wire   [20:0] add_ln221_fu_474_p2;
reg   [10:0] i_fu_146;
wire   [10:0] select_ln221_3_fu_391_p3;
reg   [20:0] indvars_iv_fu_150;
wire   [20:0] select_ln221_2_fu_383_p3;
reg   [19:0] indvar_flatten_fu_154;
wire   [19:0] select_ln221_4_fu_486_p3;
reg   [31:0] frame_no_fu_158;
wire   [31:0] select_ln24_fu_630_p3;
reg   [50:0] indvar_flatten17_fu_162;
wire   [50:0] add_ln24_fu_287_p2;
reg    ap_block_pp0_stage3_01001_grp6;
wire   [23:0] px_data_1_fu_668_p3;
reg    ap_block_pp0_stage0_01001_grp8;
wire   [23:0] px_data_2_fu_689_p3;
reg    ap_block_pp0_stage1_01001_grp9;
reg    ap_block_pp0_stage2_01001_grp10;
reg    ap_block_pp0_stage0_11001_grp8;
reg    ap_block_pp0_stage1_11001_grp9;
reg    ap_block_pp0_stage2_11001_grp10;
wire   [0:0] icmp_ln226_fu_349_p2;
wire   [10:0] select_ln23_1_fu_325_p3;
wire   [0:0] or_ln23_fu_355_p2;
wire   [20:0] select_ln23_2_fu_333_p3;
wire   [10:0] select_ln23_3_fu_341_p3;
wire   [20:0] select_ln23_fu_317_p3;
wire   [10:0] i_2_fu_361_p2;
wire   [20:0] select_ln221_fu_367_p3;
wire   [31:0] zext_ln230_fu_407_p1;
wire   [31:0] add_ln230_fu_411_p2;
wire   [10:0] select_ln221_1_fu_375_p3;
wire   [10:0] or_ln242_fu_432_p2;
wire   [8:0] tmp_5_fu_444_p4;
wire   [10:0] j_1_fu_454_p3;
wire   [19:0] add_ln221_2_fu_480_p2;
wire    ap_block_pp0_stage2_grp0;
wire   [22:0] add_ln231_fu_539_p2;
wire   [31:0] zext_ln231_fu_544_p1;
wire   [31:0] add_ln231_1_fu_548_p2;
wire   [22:0] add_ln232_1_fu_563_p2;
wire   [31:0] zext_ln232_fu_568_p1;
wire   [31:0] add_ln232_2_fu_572_p2;
wire   [31:0] add_ln24_1_fu_624_p2;
wire   [30:0] trunc_ln145_fu_637_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_block_pp0_stage3_11001;
reg    ap_condition_exit_pp0_iter2_stage2;
reg    ap_idle_pp0_0to1;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg   [3:0] ap_NS_fsm;
reg    ap_idle_pp0_1to3;
reg    ap_done_pending_pp0;
reg    ap_block_pp0_stage1_subdone;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
reg    ap_condition_792;
reg    ap_condition_795;
reg    ap_condition_798;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_block_pp0_stage3_subdone_grp2_done_reg = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 ap_block_pp0_stage3_subdone_grp6_done_reg = 1'b0;
#0 ap_block_pp0_stage2_subdone_grp1_done_reg = 1'b0;
#0 ap_block_pp0_stage0_subdone_grp3_done_reg = 1'b0;
#0 ap_block_pp0_stage0_subdone_grp8_done_reg = 1'b0;
#0 ap_block_pp0_stage2_subdone_grp10_done_reg = 1'b0;
#0 ap_block_pp0_stage0_subdone_grp0_done_reg = 1'b0;
#0 ap_block_pp0_stage2_subdone_grp0_done_reg = 1'b0;
#0 j_fu_134 = 11'd0;
#0 offset_fu_138 = 21'd0;
#0 add_ln2214_fu_142 = 21'd0;
#0 i_fu_146 = 11'd0;
#0 indvars_iv_fu_150 = 21'd0;
#0 indvar_flatten_fu_154 = 20'd0;
#0 frame_no_fu_158 = 32'd0;
#0 indvar_flatten17_fu_162 = 51'd0;
#0 ap_done_reg = 1'b0;
end

execute_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage3),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
                ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp0)) begin
                ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp3_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
                ap_block_pp0_stage0_subdone_grp3_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp3)) begin
                ap_block_pp0_stage0_subdone_grp3_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp8_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
                ap_block_pp0_stage0_subdone_grp8_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp8)) begin
                ap_block_pp0_stage0_subdone_grp8_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage2_subdone_grp0_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage2)) begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_block_pp0_stage2_subdone_grp0_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage2_subdone_grp0)) begin
                ap_block_pp0_stage2_subdone_grp0_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage2_subdone_grp10_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage2)) begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_block_pp0_stage2_subdone_grp10_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage2_subdone_grp10)) begin
                ap_block_pp0_stage2_subdone_grp10_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage2_subdone_grp1_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage2)) begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_block_pp0_stage2_subdone_grp1_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage2_subdone_grp1)) begin
                ap_block_pp0_stage2_subdone_grp1_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage3_subdone_grp2_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage3)) begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_block_pp0_stage3_subdone_grp2_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage3_subdone_grp2)) begin
                ap_block_pp0_stage3_subdone_grp2_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage3_subdone_grp6_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage3)) begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_block_pp0_stage3_subdone_grp6_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage3_subdone_grp6)) begin
                ap_block_pp0_stage3_subdone_grp6_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage3)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_subdone))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone))) begin
            ap_enable_reg_pp0_iter3 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_subdone))) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to1 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter2_stage2))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to1 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter2_stage2))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        frame_no_fu_158 <= 32'd0;
    end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001_grp6) & (1'b0 == ap_block_pp0_stage3_subdone_grp6_done_reg))) begin
        frame_no_fu_158 <= select_ln24_fu_630_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        i_fu_146 <= 11'd0;
    end else if (((icmp_ln24_fu_282_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        i_fu_146 <= select_ln221_3_fu_391_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        indvar_flatten17_fu_162 <= 51'd0;
    end else if (((icmp_ln24_fu_282_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        indvar_flatten17_fu_162 <= add_ln24_fu_287_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        indvar_flatten_fu_154 <= 20'd0;
    end else if (((icmp_ln24_fu_282_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        indvar_flatten_fu_154 <= select_ln221_4_fu_486_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        indvars_iv_fu_150 <= 21'd0;
    end else if (((icmp_ln24_fu_282_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        indvars_iv_fu_150 <= select_ln221_2_fu_383_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        j_fu_134 <= 11'd0;
    end else if (((icmp_ln24_fu_282_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        j_fu_134 <= j_2_fu_468_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        offset_fu_138 <= 21'd0;
    end else if (((icmp_ln24_fu_282_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        offset_fu_138 <= add_ln232_fu_426_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln24_fu_282_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        add_ln2214_fu_142 <= add_ln221_fu_474_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        icmp_ln221_reg_767 <= icmp_ln221_fu_311_p2;
        icmp_ln221_reg_767_pp0_iter1_reg <= icmp_ln221_reg_767;
        icmp_ln221_reg_767_pp0_iter2_reg <= icmp_ln221_reg_767_pp0_iter1_reg;
        icmp_ln24_reg_763 <= icmp_ln24_fu_282_p2;
        icmp_ln24_reg_763_pp0_iter1_reg <= icmp_ln24_reg_763;
        icmp_ln24_reg_763_pp0_iter2_reg <= icmp_ln24_reg_763_pp0_iter1_reg;
        px_last_reg_788 <= px_last_fu_462_p2;
        px_last_reg_788_pp0_iter1_reg <= px_last_reg_788;
        px_last_reg_788_pp0_iter2_reg <= px_last_reg_788_pp0_iter1_reg;
        px_last_reg_788_pp0_iter3_reg <= px_last_reg_788_pp0_iter2_reg;
        shl_ln_reg_772[22 : 2] <= shl_ln_fu_399_p3[22 : 2];
        sof_reg_783 <= sof_fu_438_p2;
        sof_reg_783_pp0_iter1_reg <= sof_reg_783;
        sof_reg_783_pp0_iter2_reg <= sof_reg_783_pp0_iter1_reg;
        trunc_ln_reg_778 <= {{add_ln230_fu_411_p2[31:2]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp3) & (1'b0 == ap_block_pp0_stage0_subdone_grp3_done_reg))) begin
        px_data_3_reg_851 <= px_data_3_fu_685_p1;
        tmp_4_reg_846 <= {{m_axi_data_mem_0_RDATA[31:24]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001_grp1) & (1'b0 == ap_block_pp0_stage2_subdone_grp1_done_reg))) begin
        px_data_reg_821 <= {{m_axi_data_mem_0_RDATA[31:8]}};
        trunc_ln249_reg_826 <= trunc_ln249_fu_617_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001_grp6) & (1'b0 == ap_block_pp0_stage3_subdone_grp6_done_reg))) begin
        px_user_reg_831 <= px_user_fu_641_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001_grp2) & (1'b0 == ap_block_pp0_stage3_subdone_grp2_done_reg))) begin
        tmp_2_reg_836 <= {{m_axi_data_mem_0_RDATA[31:16]}};
        trunc_ln261_reg_841 <= trunc_ln261_fu_659_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage2_11001_grp0))) begin
        trunc_ln1_reg_799 <= {{add_ln231_1_fu_548_p2[31:2]}};
        trunc_ln2_reg_804 <= {{add_ln232_2_fu_572_p2[31:2]}};
    end
end

always @ (*) begin
    if (((icmp_ln24_reg_763 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_subdone))) begin
        ap_condition_exit_pp0_iter0_stage3 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage3 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln24_reg_763_pp0_iter2_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone))) begin
        ap_condition_exit_pp0_iter2_stage2 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter2_stage2 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (~((ap_loop_exit_ready_pp0_iter2_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b0) & (ap_loop_exit_ready == 1'b0))) begin
        ap_done_pending_pp0 = 1'b1;
    end else begin
        ap_done_pending_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to1 = 1'b1;
    end else begin
        ap_idle_pp0_0to1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0_1to3 = 1'b1;
    end else begin
        ap_idle_pp0_1to3 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln24_reg_763 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_grp2) & (1'b0 == ap_block_pp0_stage3_subdone_grp2_done_reg)) | ((icmp_ln24_reg_763 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone_grp3_done_reg) & (1'b0 == ap_block_pp0_stage0_grp3)) | ((icmp_ln24_reg_763 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_subdone_grp1_done_reg) & (1'b0 == ap_block_pp0_stage2_grp1)))) begin
        data_mem_blk_n_AR = m_axi_data_mem_0_ARREADY;
    end else begin
        data_mem_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone_grp3_done_reg) & (1'b0 == ap_block_pp0_stage0_grp3)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_grp2) & (1'b0 == ap_block_pp0_stage3_subdone_grp2_done_reg)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone_grp1_done_reg) & (1'b0 == ap_block_pp0_stage2_grp1)))) begin
        data_mem_blk_n_R = m_axi_data_mem_0_RVALID;
    end else begin
        data_mem_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if ((icmp_ln24_reg_763 == 1'd0)) begin
        if ((1'b1 == ap_condition_798)) begin
            m_axi_data_mem_0_ARADDR = sext_ln232_fu_597_p1;
        end else if ((1'b1 == ap_condition_795)) begin
            m_axi_data_mem_0_ARADDR = sext_ln231_fu_587_p1;
        end else if ((1'b1 == ap_condition_792)) begin
            m_axi_data_mem_0_ARADDR = sext_ln230_fu_529_p1;
        end else begin
            m_axi_data_mem_0_ARADDR = 'bx;
        end
    end else begin
        m_axi_data_mem_0_ARADDR = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln24_reg_763 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_11001_grp2) & (1'b0 == ap_block_pp0_stage3_subdone_grp2_done_reg)) | ((icmp_ln24_reg_763 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp3) & (1'b0 == ap_block_pp0_stage0_subdone_grp3_done_reg)) | ((icmp_ln24_reg_763 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001_grp1) & (1'b0 == ap_block_pp0_stage2_subdone_grp1_done_reg)))) begin
        m_axi_data_mem_0_ARVALID = 1'b1;
    end else begin
        m_axi_data_mem_0_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp3) & (1'b0 == ap_block_pp0_stage0_subdone_grp3_done_reg)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001_grp2) & (1'b0 == ap_block_pp0_stage3_subdone_grp2_done_reg)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001_grp1) & (1'b0 == ap_block_pp0_stage2_subdone_grp1_done_reg)))) begin
        m_axi_data_mem_0_RREADY = 1'b1;
    end else begin
        m_axi_data_mem_0_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_01001_grp10) & (1'b0 == ap_block_pp0_stage2_subdone_grp10_done_reg))) begin
        stream_o_TDATA = px_data_3_reg_851;
    end else if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_01001_grp9))) begin
        stream_o_TDATA = px_data_2_fu_689_p3;
    end else if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_01001_grp8) & (1'b0 == ap_block_pp0_stage0_subdone_grp8_done_reg))) begin
        stream_o_TDATA = px_data_1_fu_668_p3;
    end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_01001_grp6) & (1'b0 == ap_block_pp0_stage3_subdone_grp6_done_reg))) begin
        stream_o_TDATA = px_data_reg_821;
    end else begin
        stream_o_TDATA = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_grp9)) | ((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone_grp8_done_reg) & (1'b0 == ap_block_pp0_stage0_grp8)) | ((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone_grp10_done_reg) & (1'b0 == ap_block_pp0_stage2_grp10)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_grp6) & (1'b0 == ap_block_pp0_stage3_subdone_grp6_done_reg)))) begin
        stream_o_TDATA_blk_n = stream_o_TREADY;
    end else begin
        stream_o_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_01001_grp10) & (1'b0 == ap_block_pp0_stage2_subdone_grp10_done_reg))) begin
        stream_o_TLAST = px_last_reg_788_pp0_iter3_reg;
    end else if ((((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_01001_grp9)) | ((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_01001_grp8) & (1'b0 == ap_block_pp0_stage0_subdone_grp8_done_reg)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_01001_grp6) & (1'b0 == ap_block_pp0_stage3_subdone_grp6_done_reg)))) begin
        stream_o_TLAST = 1'd0;
    end else begin
        stream_o_TLAST = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_01001_grp9)) | ((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_01001_grp8) & (1'b0 == ap_block_pp0_stage0_subdone_grp8_done_reg)) | ((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_01001_grp10) & (1'b0 == ap_block_pp0_stage2_subdone_grp10_done_reg)))) begin
        stream_o_TUSER = px_user_reg_831;
    end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_01001_grp6) & (1'b0 == ap_block_pp0_stage3_subdone_grp6_done_reg))) begin
        stream_o_TUSER = px_user_fu_641_p3;
    end else begin
        stream_o_TUSER = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001_grp9)) | ((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp8) & (1'b0 == ap_block_pp0_stage0_subdone_grp8_done_reg)) | ((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001_grp10) & (1'b0 == ap_block_pp0_stage2_subdone_grp10_done_reg)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001_grp6) & (1'b0 == ap_block_pp0_stage3_subdone_grp6_done_reg)))) begin
        stream_o_TVALID = 1'b1;
    end else begin
        stream_o_TVALID = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start_int == 1'b0) & (ap_done_pending_pp0 == 1'b0) & (ap_idle_pp0_1to3 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if (((ap_idle_pp0_0to1 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter2_stage2))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln221_2_fu_480_p2 = (indvar_flatten_fu_154 + 20'd1);

assign add_ln221_fu_474_p2 = (select_ln221_2_fu_383_p3 + 21'd1440);

assign add_ln230_fu_411_p2 = (zext_ln230_fu_407_p1 + data_port);

assign add_ln231_1_fu_548_p2 = (zext_ln231_fu_544_p1 + data_port);

assign add_ln231_fu_539_p2 = (shl_ln_reg_772 + 23'd4);

assign add_ln232_1_fu_563_p2 = (shl_ln_reg_772 + 23'd8);

assign add_ln232_2_fu_572_p2 = (zext_ln232_fu_568_p1 + data_port);

assign add_ln232_fu_426_p2 = (select_ln221_fu_367_p3 + 21'd3);

assign add_ln24_1_fu_624_p2 = (frame_no_fu_158 + 32'd1);

assign add_ln24_fu_287_p2 = (indvar_flatten17_fu_162 + 51'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd3];

always @ (*) begin
    ap_block_pp0_stage0_01001_grp8 = ((stream_o_TREADY == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp8_done_reg));
end

assign ap_block_pp0_stage0_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001_grp3 = (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state5_io_grp3) & (1'b0 == ap_block_pp0_stage0_subdone_grp3_done_reg)) | ((m_axi_data_mem_0_RVALID == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp3_done_reg)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp8 = ((stream_o_TREADY == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp8_done_reg));
end

assign ap_block_pp0_stage0_grp3 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_grp8 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter3 == 1'b1) & (((stream_o_TREADY == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone_grp8_done_reg)) | ((m_axi_data_mem_0_RVALID == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone_grp3_done_reg)))) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state5_io_grp3) & (1'b0 == ap_block_pp0_stage0_subdone_grp3_done_reg)));
end

assign ap_block_pp0_stage0_subdone_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone_grp3 = (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state5_io_grp3) & (1'b0 == ap_block_pp0_stage0_subdone_grp3_done_reg)) | ((m_axi_data_mem_0_RVALID == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp3_done_reg)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone_grp8 = ((stream_o_TREADY == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp8_done_reg));
end

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_01001_grp9 = ((stream_o_TREADY == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage1_11001 = ((stream_o_TREADY == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage1_11001_grp9 = ((stream_o_TREADY == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1));
end

assign ap_block_pp0_stage1_grp9 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_subdone = ((stream_o_TREADY == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage2_01001_grp10 = ((stream_o_TREADY == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage2_subdone_grp10_done_reg));
end

assign ap_block_pp0_stage2_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage2_11001_grp1 = (((1'b1 == ap_block_state3_io_grp1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_subdone_grp1_done_reg)) | ((m_axi_data_mem_0_RVALID == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage2_subdone_grp1_done_reg)));
end

always @ (*) begin
    ap_block_pp0_stage2_11001_grp10 = ((stream_o_TREADY == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage2_subdone_grp10_done_reg));
end

assign ap_block_pp0_stage2_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_grp1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_grp10 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage2_subdone = (((1'b1 == ap_block_state3_io_grp1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_subdone_grp1_done_reg)) | ((stream_o_TREADY == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage2_subdone_grp10_done_reg)) | ((m_axi_data_mem_0_RVALID == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage2_subdone_grp1_done_reg)));
end

assign ap_block_pp0_stage2_subdone_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage2_subdone_grp1 = (((1'b1 == ap_block_state3_io_grp1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_subdone_grp1_done_reg)) | ((m_axi_data_mem_0_RVALID == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage2_subdone_grp1_done_reg)));
end

always @ (*) begin
    ap_block_pp0_stage2_subdone_grp10 = ((stream_o_TREADY == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage2_subdone_grp10_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage3_01001_grp6 = ((stream_o_TREADY == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage3_subdone_grp6_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage3_11001 = (((ap_enable_reg_pp0_iter2 == 1'b1) & (((stream_o_TREADY == 1'b0) & (1'b0 == ap_block_pp0_stage3_subdone_grp6_done_reg)) | ((m_axi_data_mem_0_RVALID == 1'b0) & (1'b0 == ap_block_pp0_stage3_subdone_grp2_done_reg)))) | ((1'b1 == ap_block_state4_io_grp2) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_subdone_grp2_done_reg)));
end

always @ (*) begin
    ap_block_pp0_stage3_11001_grp2 = (((m_axi_data_mem_0_RVALID == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage3_subdone_grp2_done_reg)) | ((1'b1 == ap_block_state4_io_grp2) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_subdone_grp2_done_reg)));
end

always @ (*) begin
    ap_block_pp0_stage3_11001_grp6 = ((stream_o_TREADY == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage3_subdone_grp6_done_reg));
end

assign ap_block_pp0_stage3_grp2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_grp6 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage3_subdone = (((ap_enable_reg_pp0_iter2 == 1'b1) & (((stream_o_TREADY == 1'b0) & (1'b0 == ap_block_pp0_stage3_subdone_grp6_done_reg)) | ((m_axi_data_mem_0_RVALID == 1'b0) & (1'b0 == ap_block_pp0_stage3_subdone_grp2_done_reg)))) | ((1'b1 == ap_block_state4_io_grp2) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_subdone_grp2_done_reg)));
end

always @ (*) begin
    ap_block_pp0_stage3_subdone_grp2 = (((m_axi_data_mem_0_RVALID == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage3_subdone_grp2_done_reg)) | ((1'b1 == ap_block_state4_io_grp2) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_subdone_grp2_done_reg)));
end

always @ (*) begin
    ap_block_pp0_stage3_subdone_grp6 = ((stream_o_TREADY == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage3_subdone_grp6_done_reg));
end

always @ (*) begin
    ap_block_state3_io_grp1 = ((icmp_ln24_reg_763 == 1'd0) & (m_axi_data_mem_0_ARREADY == 1'b0));
end

always @ (*) begin
    ap_block_state4_io_grp2 = ((icmp_ln24_reg_763 == 1'd0) & (m_axi_data_mem_0_ARREADY == 1'b0));
end

always @ (*) begin
    ap_block_state5_io_grp3 = ((icmp_ln24_reg_763 == 1'd0) & (m_axi_data_mem_0_ARREADY == 1'b0));
end

always @ (*) begin
    ap_condition_792 = ((1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001_grp1) & (1'b0 == ap_block_pp0_stage2_subdone_grp1_done_reg));
end

always @ (*) begin
    ap_condition_795 = ((1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_11001_grp2) & (1'b0 == ap_block_pp0_stage3_subdone_grp2_done_reg));
end

always @ (*) begin
    ap_condition_798 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp3) & (1'b0 == ap_block_pp0_stage0_subdone_grp3_done_reg));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage3;

assign ap_ready = ap_ready_sig;

assign i_2_fu_361_p2 = (select_ln23_1_fu_325_p3 + 11'd1);

assign icmp_ln221_fu_311_p2 = ((indvar_flatten_fu_154 == 20'd518400) ? 1'b1 : 1'b0);

assign icmp_ln226_fu_349_p2 = ((j_fu_134 < 11'd1920) ? 1'b1 : 1'b0);

assign icmp_ln24_fu_282_p2 = ((indvar_flatten17_fu_162 == mul_ln20) ? 1'b1 : 1'b0);

assign j_1_fu_454_p3 = {{tmp_5_fu_444_p4}, {2'd3}};

assign j_2_fu_468_p2 = (select_ln221_1_fu_375_p3 + 11'd4);

assign m_axi_data_mem_0_ARBURST = 2'd0;

assign m_axi_data_mem_0_ARCACHE = 4'd0;

assign m_axi_data_mem_0_ARID = 1'd0;

assign m_axi_data_mem_0_ARLEN = 32'd1;

assign m_axi_data_mem_0_ARLOCK = 2'd0;

assign m_axi_data_mem_0_ARPROT = 3'd0;

assign m_axi_data_mem_0_ARQOS = 4'd0;

assign m_axi_data_mem_0_ARREGION = 4'd0;

assign m_axi_data_mem_0_ARSIZE = 3'd0;

assign m_axi_data_mem_0_ARUSER = 1'd0;

assign m_axi_data_mem_0_AWADDR = 32'd0;

assign m_axi_data_mem_0_AWBURST = 2'd0;

assign m_axi_data_mem_0_AWCACHE = 4'd0;

assign m_axi_data_mem_0_AWID = 1'd0;

assign m_axi_data_mem_0_AWLEN = 32'd0;

assign m_axi_data_mem_0_AWLOCK = 2'd0;

assign m_axi_data_mem_0_AWPROT = 3'd0;

assign m_axi_data_mem_0_AWQOS = 4'd0;

assign m_axi_data_mem_0_AWREGION = 4'd0;

assign m_axi_data_mem_0_AWSIZE = 3'd0;

assign m_axi_data_mem_0_AWUSER = 1'd0;

assign m_axi_data_mem_0_AWVALID = 1'b0;

assign m_axi_data_mem_0_BREADY = 1'b0;

assign m_axi_data_mem_0_WDATA = 32'd0;

assign m_axi_data_mem_0_WID = 1'd0;

assign m_axi_data_mem_0_WLAST = 1'b0;

assign m_axi_data_mem_0_WSTRB = 4'd0;

assign m_axi_data_mem_0_WUSER = 1'd0;

assign m_axi_data_mem_0_WVALID = 1'b0;

assign or_ln23_fu_355_p2 = (icmp_ln226_fu_349_p2 | icmp_ln221_fu_311_p2);

assign or_ln242_fu_432_p2 = (select_ln221_3_fu_391_p3 | select_ln221_1_fu_375_p3);

assign px_data_1_fu_668_p3 = {{trunc_ln249_reg_826}, {tmp_2_reg_836}};

assign px_data_2_fu_689_p3 = {{trunc_ln261_reg_841}, {tmp_4_reg_846}};

assign px_data_3_fu_685_p1 = m_axi_data_mem_0_RDATA[23:0];

assign px_last_fu_462_p2 = ((j_1_fu_454_p3 == 11'd1919) ? 1'b1 : 1'b0);

assign px_user_fu_641_p3 = {{trunc_ln145_fu_637_p1}, {sof_reg_783_pp0_iter2_reg}};

assign select_ln221_1_fu_375_p3 = ((or_ln23_fu_355_p2[0:0] == 1'b1) ? select_ln23_3_fu_341_p3 : 11'd0);

assign select_ln221_2_fu_383_p3 = ((or_ln23_fu_355_p2[0:0] == 1'b1) ? select_ln23_fu_317_p3 : add_ln2214_fu_142);

assign select_ln221_3_fu_391_p3 = ((or_ln23_fu_355_p2[0:0] == 1'b1) ? select_ln23_1_fu_325_p3 : i_2_fu_361_p2);

assign select_ln221_4_fu_486_p3 = ((icmp_ln221_fu_311_p2[0:0] == 1'b1) ? 20'd1 : add_ln221_2_fu_480_p2);

assign select_ln221_fu_367_p3 = ((or_ln23_fu_355_p2[0:0] == 1'b1) ? select_ln23_2_fu_333_p3 : add_ln2214_fu_142);

assign select_ln23_1_fu_325_p3 = ((icmp_ln221_fu_311_p2[0:0] == 1'b1) ? 11'd0 : i_fu_146);

assign select_ln23_2_fu_333_p3 = ((icmp_ln221_fu_311_p2[0:0] == 1'b1) ? 21'd0 : offset_fu_138);

assign select_ln23_3_fu_341_p3 = ((icmp_ln221_fu_311_p2[0:0] == 1'b1) ? 11'd0 : j_fu_134);

assign select_ln23_fu_317_p3 = ((icmp_ln221_fu_311_p2[0:0] == 1'b1) ? 21'd0 : indvars_iv_fu_150);

assign select_ln24_fu_630_p3 = ((icmp_ln221_reg_767_pp0_iter2_reg[0:0] == 1'b1) ? add_ln24_1_fu_624_p2 : frame_no_fu_158);

assign sext_ln230_fu_529_p1 = $signed(trunc_ln_reg_778);

assign sext_ln231_fu_587_p1 = $signed(trunc_ln1_reg_799);

assign sext_ln232_fu_597_p1 = $signed(trunc_ln2_reg_804);

assign shl_ln_fu_399_p3 = {{select_ln221_fu_367_p3}, {2'd0}};

assign sof_fu_438_p2 = ((or_ln242_fu_432_p2 == 11'd0) ? 1'b1 : 1'b0);

assign stream_o_TDEST = 1'd0;

assign stream_o_TID = 1'd0;

assign stream_o_TKEEP = 3'd7;

assign stream_o_TSTRB = 3'd7;

assign tmp_5_fu_444_p4 = {{select_ln221_1_fu_375_p3[10:2]}};

assign trunc_ln145_fu_637_p1 = select_ln24_fu_630_p3[30:0];

assign trunc_ln249_fu_617_p1 = m_axi_data_mem_0_RDATA[7:0];

assign trunc_ln261_fu_659_p1 = m_axi_data_mem_0_RDATA[15:0];

assign zext_ln230_fu_407_p1 = shl_ln_fu_399_p3;

assign zext_ln231_fu_544_p1 = add_ln231_fu_539_p2;

assign zext_ln232_fu_568_p1 = add_ln232_1_fu_563_p2;

always @ (posedge ap_clk) begin
    shl_ln_reg_772[1:0] <= 2'b00;
end

endmodule //execute_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2
