-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity execute_conv2d_unsigned_int_unsigned_int_dim_t_4u_TensorIO_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    Hlast : IN STD_LOGIC_VECTOR (31 downto 0);
    x_bram_address0 : OUT STD_LOGIC_VECTOR (18 downto 0);
    x_bram_ce0 : OUT STD_LOGIC;
    x_bram_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    y_bram_address0 : OUT STD_LOGIC_VECTOR (16 downto 0);
    y_bram_ce0 : OUT STD_LOGIC;
    y_bram_we0 : OUT STD_LOGIC;
    y_bram_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (95 downto 0) );
end;


architecture behav of execute_conv2d_unsigned_int_unsigned_int_dim_t_4u_TensorIO_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (9 downto 0) := "0000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (9 downto 0) := "0000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (9 downto 0) := "0000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (9 downto 0) := "0000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (9 downto 0) := "0000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (9 downto 0) := "0001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (9 downto 0) := "0010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (9 downto 0) := "0100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (9 downto 0) := "1000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv41_0 : STD_LOGIC_VECTOR (40 downto 0) := "00000000000000000000000000000000000000000";
    constant ap_const_lv128_lc_1 : STD_LOGIC_VECTOR (127 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv32_514 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000010100010100";
    constant ap_const_lv32_FFFFFFFE : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111111111110";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv64_100000001 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000100000000000000000000000000000001";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv32_40 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000000";
    constant ap_const_lv32_4B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001011";
    constant ap_const_lv41_320 : STD_LOGIC_VECTOR (40 downto 0) := "00000000000000000000000000000001100100000";
    constant ap_const_lv10_320 : STD_LOGIC_VECTOR (9 downto 0) := "1100100000";
    constant ap_const_lv10_1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv17_1 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000001";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal scratchpad_1_1_address0 : STD_LOGIC_VECTOR (11 downto 0);
    signal scratchpad_1_1_ce0 : STD_LOGIC;
    signal scratchpad_1_1_we0 : STD_LOGIC;
    signal scratchpad_1_1_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal y_max_i_fu_268_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal y_max_i_reg_544 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln135_fu_296_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln135_reg_550 : STD_LOGIC_VECTOR (31 downto 0);
    signal shape_y_cast_fu_302_p3 : STD_LOGIC_VECTOR (95 downto 0);
    signal shape_y_cast_reg_555 : STD_LOGIC_VECTOR (95 downto 0);
    signal oy_1_reg_559 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal oy_2_fu_333_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal oy_2_reg_567 : STD_LOGIC_VECTOR (31 downto 0);
    signal iy_fu_339_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal iy_reg_572 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_169_2_fu_226_ap_return : STD_LOGIC_VECTOR (0 downto 0);
    signal targetBlock_reg_577 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal trunc_ln146_fu_346_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal trunc_ln146_reg_581 : STD_LOGIC_VECTOR (16 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal trunc_ln168_fu_350_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal trunc_ln168_reg_586 : STD_LOGIC_VECTOR (30 downto 0);
    signal trunc_ln168_1_fu_353_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln168_1_reg_591 : STD_LOGIC_VECTOR (10 downto 0);
    signal p_cast_reg_599 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal offset_y_3_fu_390_p2 : STD_LOGIC_VECTOR (40 downto 0);
    signal offset_y_3_reg_604 : STD_LOGIC_VECTOR (40 downto 0);
    signal ox_1_fu_402_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal ox_1_reg_612 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal zext_ln146_fu_408_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln146_reg_617 : STD_LOGIC_VECTOR (63 downto 0);
    signal ix_fu_412_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal ix_reg_622 : STD_LOGIC_VECTOR (10 downto 0);
    signal offset_y_4_fu_439_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal add_ln187_fu_451_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln187_reg_635 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal or_ln_fu_468_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal or_ln_reg_640 : STD_LOGIC_VECTOR (11 downto 0);
    signal or_ln189_fu_494_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln189_reg_645 : STD_LOGIC_VECTOR (0 downto 0);
    signal shuffle_ky_fu_500_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal shuffle_ky_reg_649 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_169_2_fu_226_ap_start : STD_LOGIC;
    signal grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_169_2_fu_226_ap_done : STD_LOGIC;
    signal grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_169_2_fu_226_ap_idle : STD_LOGIC;
    signal grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_169_2_fu_226_ap_ready : STD_LOGIC;
    signal grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_169_2_fu_226_y_2_out : STD_LOGIC_VECTOR (30 downto 0);
    signal grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_169_2_fu_226_y_2_out_ap_vld : STD_LOGIC;
    signal grp_slice_tensor_2_vector_unsigned_int_unsigned_int_dim_t_4u_TensorIO_s_fu_233_ap_start : STD_LOGIC;
    signal grp_slice_tensor_2_vector_unsigned_int_unsigned_int_dim_t_4u_TensorIO_s_fu_233_ap_done : STD_LOGIC;
    signal grp_slice_tensor_2_vector_unsigned_int_unsigned_int_dim_t_4u_TensorIO_s_fu_233_ap_idle : STD_LOGIC;
    signal grp_slice_tensor_2_vector_unsigned_int_unsigned_int_dim_t_4u_TensorIO_s_fu_233_ap_ready : STD_LOGIC;
    signal grp_slice_tensor_2_vector_unsigned_int_unsigned_int_dim_t_4u_TensorIO_s_fu_233_x_bram_address0 : STD_LOGIC_VECTOR (18 downto 0);
    signal grp_slice_tensor_2_vector_unsigned_int_unsigned_int_dim_t_4u_TensorIO_s_fu_233_x_bram_ce0 : STD_LOGIC;
    signal grp_slice_tensor_2_vector_unsigned_int_unsigned_int_dim_t_4u_TensorIO_s_fu_233_scratchpad_1_1_address0 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_slice_tensor_2_vector_unsigned_int_unsigned_int_dim_t_4u_TensorIO_s_fu_233_scratchpad_1_1_ce0 : STD_LOGIC;
    signal grp_slice_tensor_2_vector_unsigned_int_unsigned_int_dim_t_4u_TensorIO_s_fu_233_scratchpad_1_1_we0 : STD_LOGIC;
    signal grp_slice_tensor_2_vector_unsigned_int_unsigned_int_dim_t_4u_TensorIO_s_fu_233_scratchpad_1_1_d0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_192_6_fu_244_ap_start : STD_LOGIC;
    signal grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_192_6_fu_244_ap_done : STD_LOGIC;
    signal grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_192_6_fu_244_ap_idle : STD_LOGIC;
    signal grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_192_6_fu_244_ap_ready : STD_LOGIC;
    signal grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_192_6_fu_244_acc_2_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_192_6_fu_244_acc_2_out_ap_vld : STD_LOGIC;
    signal grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_192_6_fu_244_scratchpad_1_1_address0 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_192_6_fu_244_scratchpad_1_1_ce0 : STD_LOGIC;
    signal offset_y_1_reg_145 : STD_LOGIC_VECTOR (16 downto 0);
    signal ap_block_state5_on_subcall_done : BOOLEAN;
    signal ap_phi_mux_ic_phi_fu_171_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ox_reg_155 : STD_LOGIC_VECTOR (9 downto 0);
    signal ic_reg_166 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln179_fu_396_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln187_fu_445_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal acc_reg_179 : STD_LOGIC_VECTOR (31 downto 0);
    signal ky_2_reg_191 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal acc_1_reg_202 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_acc_3_phi_fu_218_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_3_reg_214 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_169_2_fu_226_ap_start_reg : STD_LOGIC := '0';
    signal icmp_ln167_fu_328_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal y_2_loc_fu_122 : STD_LOGIC_VECTOR (30 downto 0);
    signal grp_slice_tensor_2_vector_unsigned_int_unsigned_int_dim_t_4u_TensorIO_s_fu_233_ap_start_reg : STD_LOGIC := '0';
    signal grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_192_6_fu_244_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal oy_fu_106 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal offset_y_fu_110 : STD_LOGIC_VECTOR (40 downto 0) := "00000000000000000000000000000000000000000";
    signal y_cpy_0_fu_114 : STD_LOGIC_VECTOR (127 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    signal zext_ln55_fu_368_p1 : STD_LOGIC_VECTOR (127 downto 0);
    signal y_bram_we0_local : STD_LOGIC;
    signal y_bram_ce0_local : STD_LOGIC;
    signal icmp_ln129_fu_262_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln134_fu_276_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal lshr_ln_fu_282_p4 : STD_LOGIC_VECTOR (30 downto 0);
    signal zext_ln134_fu_292_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_s_fu_360_p3 : STD_LOGIC_VECTOR (94 downto 0);
    signal trunc_ln188_fu_457_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal y_fu_461_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln189_fu_483_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_fu_476_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln189_fu_488_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component execute_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_169_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        empty : IN STD_LOGIC_VECTOR (31 downto 0);
        y_max_i : IN STD_LOGIC_VECTOR (31 downto 0);
        y_2_out : OUT STD_LOGIC_VECTOR (30 downto 0);
        y_2_out_ap_vld : OUT STD_LOGIC;
        ap_return : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component execute_slice_tensor_2_vector_unsigned_int_unsigned_int_dim_t_4u_TensorIO_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        y_start : IN STD_LOGIC_VECTOR (30 downto 0);
        x_bram_address0 : OUT STD_LOGIC_VECTOR (18 downto 0);
        x_bram_ce0 : OUT STD_LOGIC;
        x_bram_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        scratchpad_1_1_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
        scratchpad_1_1_ce0 : OUT STD_LOGIC;
        scratchpad_1_1_we0 : OUT STD_LOGIC;
        scratchpad_1_1_d0 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component execute_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_192_6 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        acc_1 : IN STD_LOGIC_VECTOR (31 downto 0);
        or_ln : IN STD_LOGIC_VECTOR (11 downto 0);
        p_cast : IN STD_LOGIC_VECTOR (11 downto 0);
        zext_ln182 : IN STD_LOGIC_VECTOR (10 downto 0);
        empty : IN STD_LOGIC_VECTOR (1 downto 0);
        acc_2_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        acc_2_out_ap_vld : OUT STD_LOGIC;
        scratchpad_1_1_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
        scratchpad_1_1_ce0 : OUT STD_LOGIC;
        scratchpad_1_1_q0 : IN STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component execute_conv2d_unsigned_int_unsigned_int_dim_t_4u_TensorIO_s_scratchpad_1_1_RAM_AUTO_cud IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (11 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (7 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;



begin
    scratchpad_1_1_U : component execute_conv2d_unsigned_int_unsigned_int_dim_t_4u_TensorIO_s_scratchpad_1_1_RAM_AUTO_cud
    generic map (
        DataWidth => 8,
        AddressRange => 3200,
        AddressWidth => 12)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => scratchpad_1_1_address0,
        ce0 => scratchpad_1_1_ce0,
        we0 => scratchpad_1_1_we0,
        d0 => grp_slice_tensor_2_vector_unsigned_int_unsigned_int_dim_t_4u_TensorIO_s_fu_233_scratchpad_1_1_d0,
        q0 => scratchpad_1_1_q0);

    grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_169_2_fu_226 : component execute_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_169_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_169_2_fu_226_ap_start,
        ap_done => grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_169_2_fu_226_ap_done,
        ap_idle => grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_169_2_fu_226_ap_idle,
        ap_ready => grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_169_2_fu_226_ap_ready,
        empty => iy_reg_572,
        y_max_i => y_max_i_reg_544,
        y_2_out => grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_169_2_fu_226_y_2_out,
        y_2_out_ap_vld => grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_169_2_fu_226_y_2_out_ap_vld,
        ap_return => grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_169_2_fu_226_ap_return);

    grp_slice_tensor_2_vector_unsigned_int_unsigned_int_dim_t_4u_TensorIO_s_fu_233 : component execute_slice_tensor_2_vector_unsigned_int_unsigned_int_dim_t_4u_TensorIO_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_slice_tensor_2_vector_unsigned_int_unsigned_int_dim_t_4u_TensorIO_s_fu_233_ap_start,
        ap_done => grp_slice_tensor_2_vector_unsigned_int_unsigned_int_dim_t_4u_TensorIO_s_fu_233_ap_done,
        ap_idle => grp_slice_tensor_2_vector_unsigned_int_unsigned_int_dim_t_4u_TensorIO_s_fu_233_ap_idle,
        ap_ready => grp_slice_tensor_2_vector_unsigned_int_unsigned_int_dim_t_4u_TensorIO_s_fu_233_ap_ready,
        y_start => y_2_loc_fu_122,
        x_bram_address0 => grp_slice_tensor_2_vector_unsigned_int_unsigned_int_dim_t_4u_TensorIO_s_fu_233_x_bram_address0,
        x_bram_ce0 => grp_slice_tensor_2_vector_unsigned_int_unsigned_int_dim_t_4u_TensorIO_s_fu_233_x_bram_ce0,
        x_bram_q0 => x_bram_q0,
        scratchpad_1_1_address0 => grp_slice_tensor_2_vector_unsigned_int_unsigned_int_dim_t_4u_TensorIO_s_fu_233_scratchpad_1_1_address0,
        scratchpad_1_1_ce0 => grp_slice_tensor_2_vector_unsigned_int_unsigned_int_dim_t_4u_TensorIO_s_fu_233_scratchpad_1_1_ce0,
        scratchpad_1_1_we0 => grp_slice_tensor_2_vector_unsigned_int_unsigned_int_dim_t_4u_TensorIO_s_fu_233_scratchpad_1_1_we0,
        scratchpad_1_1_d0 => grp_slice_tensor_2_vector_unsigned_int_unsigned_int_dim_t_4u_TensorIO_s_fu_233_scratchpad_1_1_d0);

    grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_192_6_fu_244 : component execute_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_192_6
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_192_6_fu_244_ap_start,
        ap_done => grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_192_6_fu_244_ap_done,
        ap_idle => grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_192_6_fu_244_ap_idle,
        ap_ready => grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_192_6_fu_244_ap_ready,
        acc_1 => acc_1_reg_202,
        or_ln => or_ln_reg_640,
        p_cast => p_cast_reg_599,
        zext_ln182 => ix_reg_622,
        empty => shuffle_ky_reg_649,
        acc_2_out => grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_192_6_fu_244_acc_2_out,
        acc_2_out_ap_vld => grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_192_6_fu_244_acc_2_out_ap_vld,
        scratchpad_1_1_address0 => grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_192_6_fu_244_scratchpad_1_1_address0,
        scratchpad_1_1_ce0 => grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_192_6_fu_244_scratchpad_1_1_ce0,
        scratchpad_1_1_q0 => scratchpad_1_1_q0);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_169_2_fu_226_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_169_2_fu_226_ap_start_reg <= ap_const_logic_0;
            else
                if (((icmp_ln167_fu_328_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_169_2_fu_226_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_169_2_fu_226_ap_ready = ap_const_logic_1)) then 
                    grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_169_2_fu_226_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_192_6_fu_244_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_192_6_fu_244_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state8) and (icmp_ln187_fu_445_p2 = ap_const_lv1_0) and (or_ln189_fu_494_p2 = ap_const_lv1_0))) then 
                    grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_192_6_fu_244_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_192_6_fu_244_ap_ready = ap_const_logic_1)) then 
                    grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_192_6_fu_244_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_slice_tensor_2_vector_unsigned_int_unsigned_int_dim_t_4u_TensorIO_s_fu_233_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_slice_tensor_2_vector_unsigned_int_unsigned_int_dim_t_4u_TensorIO_s_fu_233_ap_start_reg <= ap_const_logic_0;
            else
                if (((targetBlock_reg_577 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                    grp_slice_tensor_2_vector_unsigned_int_unsigned_int_dim_t_4u_TensorIO_s_fu_233_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_slice_tensor_2_vector_unsigned_int_unsigned_int_dim_t_4u_TensorIO_s_fu_233_ap_ready = ap_const_logic_1)) then 
                    grp_slice_tensor_2_vector_unsigned_int_unsigned_int_dim_t_4u_TensorIO_s_fu_233_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    acc_1_reg_202_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
                acc_1_reg_202 <= ap_phi_mux_acc_3_phi_fu_218_p4;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state7) and (ap_phi_mux_ic_phi_fu_171_p4 = ap_const_lv1_0))) then 
                acc_1_reg_202 <= acc_reg_179;
            end if; 
        end if;
    end process;

    acc_3_reg_214_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state10) and (or_ln189_reg_645 = ap_const_lv1_0))) then 
                acc_3_reg_214 <= grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_192_6_fu_244_acc_2_out;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state8) and (icmp_ln187_fu_445_p2 = ap_const_lv1_0) and (or_ln189_fu_494_p2 = ap_const_lv1_1))) then 
                acc_3_reg_214 <= acc_1_reg_202;
            end if; 
        end if;
    end process;

    acc_reg_179_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state8) and (icmp_ln187_fu_445_p2 = ap_const_lv1_1))) then 
                acc_reg_179 <= acc_1_reg_202;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state6) and (icmp_ln179_fu_396_p2 = ap_const_lv1_0))) then 
                acc_reg_179 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;

    ic_reg_166_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state8) and (icmp_ln187_fu_445_p2 = ap_const_lv1_1))) then 
                ic_reg_166 <= ap_const_lv1_1;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state6) and (icmp_ln179_fu_396_p2 = ap_const_lv1_0))) then 
                ic_reg_166 <= ap_const_lv1_0;
            end if; 
        end if;
    end process;

    ky_2_reg_191_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
                ky_2_reg_191 <= add_ln187_reg_635;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state7) and (ap_phi_mux_ic_phi_fu_171_p4 = ap_const_lv1_0))) then 
                ky_2_reg_191 <= ap_const_lv2_0;
            end if; 
        end if;
    end process;

    offset_y_1_reg_145_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state7) and (ap_phi_mux_ic_phi_fu_171_p4 = ap_const_lv1_1))) then 
                offset_y_1_reg_145 <= offset_y_4_fu_439_p2;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state5) and (ap_const_boolean_0 = ap_block_state5_on_subcall_done))) then 
                offset_y_1_reg_145 <= trunc_ln146_reg_581;
            end if; 
        end if;
    end process;

    offset_y_fu_110_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                offset_y_fu_110 <= ap_const_lv41_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state6) and (icmp_ln179_fu_396_p2 = ap_const_lv1_1))) then 
                offset_y_fu_110 <= offset_y_3_reg_604;
            end if; 
        end if;
    end process;

    ox_reg_155_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state7) and (ap_phi_mux_ic_phi_fu_171_p4 = ap_const_lv1_1))) then 
                ox_reg_155 <= ox_1_reg_612;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state5) and (ap_const_boolean_0 = ap_block_state5_on_subcall_done))) then 
                ox_reg_155 <= ap_const_lv10_0;
            end if; 
        end if;
    end process;

    oy_fu_106_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                oy_fu_106 <= ap_const_lv32_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state6) and (icmp_ln179_fu_396_p2 = ap_const_lv1_1))) then 
                oy_fu_106 <= oy_2_reg_567;
            end if; 
        end if;
    end process;

    y_cpy_0_fu_114_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                y_cpy_0_fu_114(64) <= '0';
                y_cpy_0_fu_114(65) <= '0';
                y_cpy_0_fu_114(66) <= '0';
                y_cpy_0_fu_114(67) <= '0';
                y_cpy_0_fu_114(68) <= '0';
                y_cpy_0_fu_114(69) <= '0';
                y_cpy_0_fu_114(70) <= '0';
                y_cpy_0_fu_114(71) <= '0';
                y_cpy_0_fu_114(72) <= '0';
                y_cpy_0_fu_114(73) <= '0';
                y_cpy_0_fu_114(74) <= '0';
                y_cpy_0_fu_114(75) <= '0';
                y_cpy_0_fu_114(76) <= '0';
                y_cpy_0_fu_114(77) <= '0';
                y_cpy_0_fu_114(78) <= '0';
                y_cpy_0_fu_114(79) <= '0';
                y_cpy_0_fu_114(80) <= '0';
                y_cpy_0_fu_114(81) <= '0';
                y_cpy_0_fu_114(82) <= '0';
                y_cpy_0_fu_114(83) <= '0';
                y_cpy_0_fu_114(84) <= '0';
                y_cpy_0_fu_114(85) <= '0';
                y_cpy_0_fu_114(86) <= '0';
                y_cpy_0_fu_114(87) <= '0';
                y_cpy_0_fu_114(88) <= '0';
                y_cpy_0_fu_114(89) <= '0';
                y_cpy_0_fu_114(90) <= '0';
                y_cpy_0_fu_114(91) <= '0';
                y_cpy_0_fu_114(92) <= '0';
                y_cpy_0_fu_114(93) <= '0';
                y_cpy_0_fu_114(94) <= '0';
            elsif (((targetBlock_reg_577 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                                y_cpy_0_fu_114(94 downto 64) <= zext_ln55_fu_368_p1(94 downto 64);
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                add_ln135_reg_550 <= add_ln135_fu_296_p2;
                    shape_y_cast_reg_555(95 downto 64) <= shape_y_cast_fu_302_p3(95 downto 64);
                y_max_i_reg_544 <= y_max_i_fu_268_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state8)) then
                add_ln187_reg_635 <= add_ln187_fu_451_p2;
                or_ln189_reg_645 <= or_ln189_fu_494_p2;
                or_ln_reg_640 <= or_ln_fu_468_p3;
                shuffle_ky_reg_649 <= shuffle_ky_fu_500_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state6)) then
                    ix_reg_622(10 downto 1) <= ix_fu_412_p3(10 downto 1);
                ox_1_reg_612 <= ox_1_fu_402_p2;
                    zext_ln146_reg_617(16 downto 0) <= zext_ln146_fu_408_p1(16 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                iy_reg_572 <= iy_fu_339_p2;
                oy_1_reg_559 <= oy_fu_106;
                oy_2_reg_567 <= oy_2_fu_333_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                offset_y_3_reg_604 <= offset_y_3_fu_390_p2;
                p_cast_reg_599 <= y_cpy_0_fu_114(75 downto 64);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                targetBlock_reg_577 <= grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_169_2_fu_226_ap_return;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                trunc_ln146_reg_581 <= trunc_ln146_fu_346_p1;
                trunc_ln168_1_reg_591 <= trunc_ln168_1_fu_353_p1;
                trunc_ln168_reg_586 <= trunc_ln168_fu_350_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_169_2_fu_226_y_2_out_ap_vld = ap_const_logic_1))) then
                y_2_loc_fu_122 <= grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_169_2_fu_226_y_2_out;
            end if;
        end if;
    end process;
    shape_y_cast_reg_555(63 downto 0) <= "0000000000000000000000000000000100000000000000000000000000000001";
    zext_ln146_reg_617(63 downto 17) <= "00000000000000000000000000000000000000000000000";
    ix_reg_622(0) <= '0';
    y_cpy_0_fu_114(63 downto 0) <= "0000000000000000000000000000000000000000000000000000000000000000";
    y_cpy_0_fu_114(127 downto 95) <= "000000000000000000000000000000000";

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state5, ap_CS_fsm_state6, ap_CS_fsm_state7, ap_CS_fsm_state8, or_ln189_fu_494_p2, grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_169_2_fu_226_ap_done, grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_192_6_fu_244_ap_done, ap_block_state5_on_subcall_done, ap_phi_mux_ic_phi_fu_171_p4, icmp_ln179_fu_396_p2, icmp_ln187_fu_445_p2, icmp_ln167_fu_328_p2, ap_CS_fsm_state9)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((icmp_ln167_fu_328_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_169_2_fu_226_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state5) and (ap_const_boolean_0 = ap_block_state5_on_subcall_done))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state6 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state6) and (icmp_ln179_fu_396_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state7;
                end if;
            when ap_ST_fsm_state7 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state7) and (ap_phi_mux_ic_phi_fu_171_p4 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_state8;
                end if;
            when ap_ST_fsm_state8 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state8) and (icmp_ln187_fu_445_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state7;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state8) and (icmp_ln187_fu_445_p2 = ap_const_lv1_0) and (or_ln189_fu_494_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state10;
                else
                    ap_NS_fsm <= ap_ST_fsm_state9;
                end if;
            when ap_ST_fsm_state9 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state9) and (grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_192_6_fu_244_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state10;
                else
                    ap_NS_fsm <= ap_ST_fsm_state9;
                end if;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXX";
        end case;
    end process;
    add_ln134_fu_276_p2 <= std_logic_vector(unsigned(y_max_i_fu_268_p3) + unsigned(ap_const_lv32_FFFFFFFE));
    add_ln135_fu_296_p2 <= std_logic_vector(unsigned(zext_ln134_fu_292_p1) + unsigned(ap_const_lv32_1));
    add_ln187_fu_451_p2 <= std_logic_vector(unsigned(ky_2_reg_191) + unsigned(ap_const_lv2_1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);
    ap_ST_fsm_state10_blk <= ap_const_logic_0;

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_fsm_state3_blk_assign_proc : process(grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_169_2_fu_226_ap_done)
    begin
        if ((grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_169_2_fu_226_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state4_blk <= ap_const_logic_0;

    ap_ST_fsm_state5_blk_assign_proc : process(ap_block_state5_on_subcall_done)
    begin
        if ((ap_const_boolean_1 = ap_block_state5_on_subcall_done)) then 
            ap_ST_fsm_state5_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state5_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state6_blk <= ap_const_logic_0;
    ap_ST_fsm_state7_blk <= ap_const_logic_0;
    ap_ST_fsm_state8_blk <= ap_const_logic_0;

    ap_ST_fsm_state9_blk_assign_proc : process(grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_192_6_fu_244_ap_done)
    begin
        if ((grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_192_6_fu_244_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state9_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state9_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state5_on_subcall_done_assign_proc : process(targetBlock_reg_577, grp_slice_tensor_2_vector_unsigned_int_unsigned_int_dim_t_4u_TensorIO_s_fu_233_ap_done)
    begin
                ap_block_state5_on_subcall_done <= ((targetBlock_reg_577 = ap_const_lv1_0) and (grp_slice_tensor_2_vector_unsigned_int_unsigned_int_dim_t_4u_TensorIO_s_fu_233_ap_done = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state2, icmp_ln167_fu_328_p2)
    begin
        if ((((icmp_ln167_fu_328_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2)) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_acc_3_phi_fu_218_p4_assign_proc : process(or_ln189_reg_645, grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_192_6_fu_244_acc_2_out, ap_CS_fsm_state10, acc_3_reg_214)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state10) and (or_ln189_reg_645 = ap_const_lv1_0))) then 
            ap_phi_mux_acc_3_phi_fu_218_p4 <= grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_192_6_fu_244_acc_2_out;
        else 
            ap_phi_mux_acc_3_phi_fu_218_p4 <= acc_3_reg_214;
        end if; 
    end process;

    ap_phi_mux_ic_phi_fu_171_p4 <= ic_reg_166;

    ap_ready_assign_proc : process(ap_CS_fsm_state2, icmp_ln167_fu_328_p2)
    begin
        if (((icmp_ln167_fu_328_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    ap_return <= shape_y_cast_reg_555;
    grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_169_2_fu_226_ap_start <= grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_169_2_fu_226_ap_start_reg;
    grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_192_6_fu_244_ap_start <= grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_192_6_fu_244_ap_start_reg;
    grp_slice_tensor_2_vector_unsigned_int_unsigned_int_dim_t_4u_TensorIO_s_fu_233_ap_start <= grp_slice_tensor_2_vector_unsigned_int_unsigned_int_dim_t_4u_TensorIO_s_fu_233_ap_start_reg;
    icmp_ln129_fu_262_p2 <= "0" when (Hlast = ap_const_lv32_0) else "1";
    icmp_ln167_fu_328_p2 <= "1" when (oy_fu_106 = add_ln135_reg_550) else "0";
    icmp_ln179_fu_396_p2 <= "1" when (ox_reg_155 = ap_const_lv10_320) else "0";
    icmp_ln187_fu_445_p2 <= "1" when (ky_2_reg_191 = ap_const_lv2_2) else "0";
    icmp_ln189_fu_483_p2 <= "1" when (signed(y_fu_461_p3) < signed(y_max_i_reg_544)) else "0";
    ix_fu_412_p3 <= (ox_reg_155 & ap_const_lv1_0);
    iy_fu_339_p2 <= std_logic_vector(shift_left(unsigned(oy_fu_106),to_integer(unsigned('0' & ap_const_lv32_1(31-1 downto 0)))));
    lshr_ln_fu_282_p4 <= add_ln134_fu_276_p2(31 downto 1);
    offset_y_3_fu_390_p2 <= std_logic_vector(unsigned(offset_y_fu_110) + unsigned(ap_const_lv41_320));
    offset_y_4_fu_439_p2 <= std_logic_vector(unsigned(offset_y_1_reg_145) + unsigned(ap_const_lv17_1));
    or_ln189_fu_494_p2 <= (xor_ln189_fu_488_p2 or tmp_fu_476_p3);
    or_ln_fu_468_p3 <= (trunc_ln168_1_reg_591 & trunc_ln188_fu_457_p1);
    ox_1_fu_402_p2 <= std_logic_vector(unsigned(ox_reg_155) + unsigned(ap_const_lv10_1));
    oy_2_fu_333_p2 <= std_logic_vector(unsigned(oy_fu_106) + unsigned(ap_const_lv32_1));

    scratchpad_1_1_address0_assign_proc : process(targetBlock_reg_577, ap_CS_fsm_state5, grp_slice_tensor_2_vector_unsigned_int_unsigned_int_dim_t_4u_TensorIO_s_fu_233_scratchpad_1_1_address0, grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_192_6_fu_244_scratchpad_1_1_address0, ap_CS_fsm_state9)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            scratchpad_1_1_address0 <= grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_192_6_fu_244_scratchpad_1_1_address0;
        elsif (((targetBlock_reg_577 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            scratchpad_1_1_address0 <= grp_slice_tensor_2_vector_unsigned_int_unsigned_int_dim_t_4u_TensorIO_s_fu_233_scratchpad_1_1_address0;
        else 
            scratchpad_1_1_address0 <= "XXXXXXXXXXXX";
        end if; 
    end process;


    scratchpad_1_1_ce0_assign_proc : process(targetBlock_reg_577, ap_CS_fsm_state5, grp_slice_tensor_2_vector_unsigned_int_unsigned_int_dim_t_4u_TensorIO_s_fu_233_scratchpad_1_1_ce0, grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_192_6_fu_244_scratchpad_1_1_ce0, ap_CS_fsm_state9)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            scratchpad_1_1_ce0 <= grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_192_6_fu_244_scratchpad_1_1_ce0;
        elsif (((targetBlock_reg_577 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            scratchpad_1_1_ce0 <= grp_slice_tensor_2_vector_unsigned_int_unsigned_int_dim_t_4u_TensorIO_s_fu_233_scratchpad_1_1_ce0;
        else 
            scratchpad_1_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    scratchpad_1_1_we0_assign_proc : process(targetBlock_reg_577, ap_CS_fsm_state5, grp_slice_tensor_2_vector_unsigned_int_unsigned_int_dim_t_4u_TensorIO_s_fu_233_scratchpad_1_1_we0)
    begin
        if (((targetBlock_reg_577 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            scratchpad_1_1_we0 <= grp_slice_tensor_2_vector_unsigned_int_unsigned_int_dim_t_4u_TensorIO_s_fu_233_scratchpad_1_1_we0;
        else 
            scratchpad_1_1_we0 <= ap_const_logic_0;
        end if; 
    end process;

    shape_y_cast_fu_302_p3 <= (add_ln135_fu_296_p2 & ap_const_lv64_100000001);
    shuffle_ky_fu_500_p2 <= std_logic_vector(shift_left(unsigned(ky_2_reg_191),to_integer(unsigned('0' & ap_const_lv2_1(2-1 downto 0)))));
    tmp_fu_476_p3 <= oy_1_reg_559(30 downto 30);
    tmp_s_fu_360_p3 <= (y_2_loc_fu_122 & ap_const_lv64_0);
    trunc_ln146_fu_346_p1 <= offset_y_fu_110(17 - 1 downto 0);
    trunc_ln168_1_fu_353_p1 <= oy_fu_106(11 - 1 downto 0);
    trunc_ln168_fu_350_p1 <= oy_fu_106(31 - 1 downto 0);
    trunc_ln188_fu_457_p1 <= ky_2_reg_191(1 - 1 downto 0);
    x_bram_address0 <= grp_slice_tensor_2_vector_unsigned_int_unsigned_int_dim_t_4u_TensorIO_s_fu_233_x_bram_address0;
    x_bram_ce0 <= grp_slice_tensor_2_vector_unsigned_int_unsigned_int_dim_t_4u_TensorIO_s_fu_233_x_bram_ce0;
    xor_ln189_fu_488_p2 <= (icmp_ln189_fu_483_p2 xor ap_const_lv1_1);
    y_bram_address0 <= zext_ln146_reg_617(17 - 1 downto 0);
    y_bram_ce0 <= y_bram_ce0_local;

    y_bram_ce0_local_assign_proc : process(ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            y_bram_ce0_local <= ap_const_logic_1;
        else 
            y_bram_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    y_bram_d0 <= acc_reg_179(15 downto 8);
    y_bram_we0 <= y_bram_we0_local;

    y_bram_we0_local_assign_proc : process(ap_CS_fsm_state7, ap_phi_mux_ic_phi_fu_171_p4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state7) and (ap_phi_mux_ic_phi_fu_171_p4 = ap_const_lv1_1))) then 
            y_bram_we0_local <= ap_const_logic_1;
        else 
            y_bram_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    y_fu_461_p3 <= (trunc_ln168_reg_586 & trunc_ln188_fu_457_p1);
    y_max_i_fu_268_p3 <= 
        Hlast when (icmp_ln129_fu_262_p2(0) = '1') else 
        ap_const_lv32_514;
    zext_ln134_fu_292_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln_fu_282_p4),32));
    zext_ln146_fu_408_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(offset_y_1_reg_145),64));
    zext_ln55_fu_368_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_s_fu_360_p3),128));
end behav;
