-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity execute_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_192_6 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    acc_1 : IN STD_LOGIC_VECTOR (31 downto 0);
    or_ln : IN STD_LOGIC_VECTOR (11 downto 0);
    p_cast : IN STD_LOGIC_VECTOR (11 downto 0);
    zext_ln182 : IN STD_LOGIC_VECTOR (10 downto 0);
    empty : IN STD_LOGIC_VECTOR (1 downto 0);
    acc_2_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    acc_2_out_ap_vld : OUT STD_LOGIC;
    scratchpad_1_1_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
    scratchpad_1_1_ce0 : OUT STD_LOGIC;
    scratchpad_1_1_q0 : IN STD_LOGIC_VECTOR (7 downto 0) );
end;


architecture behav of execute_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_192_6 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv14_0 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000000";
    constant ap_const_lv12_640 : STD_LOGIC_VECTOR (11 downto 0) := "011001000000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln192_fu_154_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal scratchpad_0_1_address0 : STD_LOGIC_VECTOR (1 downto 0);
    signal scratchpad_0_1_q0 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal zext_ln182_cast_fu_137_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln182_cast_reg_279 : STD_LOGIC_VECTOR (11 downto 0);
    signal icmp_ln192_reg_284 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln192_reg_284_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln192_reg_284_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln193_fu_166_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln193_reg_288 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln193_reg_288_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln193_reg_288_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal w_value_reg_298 : STD_LOGIC_VECTOR (0 downto 0);
    signal w_value_reg_298_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal w_value_reg_298_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln146_fu_176_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln197_fu_202_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal acc_fu_66 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal acc_2_fu_239_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal kx_fu_70 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal add_ln192_fu_160_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_sig_allocacmp_kx_1 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal scratchpad_0_1_ce0_local : STD_LOGIC;
    signal scratchpad_1_1_ce0_local : STD_LOGIC;
    signal offset_w_fu_170_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_5_fu_186_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_fu_254_p4 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_5_fu_186_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal offset_x_fu_195_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal p_shl_fu_214_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal zext_ln199_fu_210_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal sub_ln202_fu_222_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal select_ln202_fu_228_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal zext_ln202_fu_235_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_254_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_fu_254_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component execute_ama_submuladd_12ns_12ns_11ns_11ns_12_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (11 downto 0);
        din1 : IN STD_LOGIC_VECTOR (11 downto 0);
        din2 : IN STD_LOGIC_VECTOR (10 downto 0);
        din3 : IN STD_LOGIC_VECTOR (10 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (11 downto 0) );
    end component;


    component execute_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_192_6_scrbkb IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (1 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component execute_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    scratchpad_0_1_U : component execute_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_192_6_scrbkb
    generic map (
        DataWidth => 1,
        AddressRange => 4,
        AddressWidth => 2)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => scratchpad_0_1_address0,
        ce0 => scratchpad_0_1_ce0_local,
        q0 => scratchpad_0_1_q0);

    ama_submuladd_12ns_12ns_11ns_11ns_12_4_1_U77 : component execute_ama_submuladd_12ns_12ns_11ns_11ns_12_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 12,
        din1_WIDTH => 12,
        din2_WIDTH => 11,
        din3_WIDTH => 11,
        dout_WIDTH => 12)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => or_ln,
        din1 => p_cast,
        din2 => grp_fu_254_p2,
        din3 => grp_fu_254_p3,
        ce => ap_const_logic_1,
        dout => grp_fu_254_p4);

    flow_control_loop_pipe_sequential_init_U : component execute_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    acc_fu_66_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                    acc_fu_66 <= acc_1;
                elsif ((ap_enable_reg_pp0_iter4 = ap_const_logic_1)) then 
                    acc_fu_66 <= acc_2_fu_239_p2;
                end if;
            end if; 
        end if;
    end process;

    kx_fu_70_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln192_fu_154_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    kx_fu_70 <= add_ln192_fu_160_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    kx_fu_70 <= ap_const_lv2_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                icmp_ln192_reg_284 <= icmp_ln192_fu_154_p2;
                icmp_ln192_reg_284_pp0_iter1_reg <= icmp_ln192_reg_284;
                trunc_ln193_reg_288 <= trunc_ln193_fu_166_p1;
                trunc_ln193_reg_288_pp0_iter1_reg <= trunc_ln193_reg_288;
                w_value_reg_298 <= scratchpad_0_1_q0;
                    zext_ln182_cast_reg_279(10 downto 0) <= zext_ln182_cast_fu_137_p1(10 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                icmp_ln192_reg_284_pp0_iter2_reg <= icmp_ln192_reg_284_pp0_iter1_reg;
                trunc_ln193_reg_288_pp0_iter2_reg <= trunc_ln193_reg_288_pp0_iter1_reg;
                w_value_reg_298_pp0_iter2_reg <= w_value_reg_298;
                w_value_reg_298_pp0_iter3_reg <= w_value_reg_298_pp0_iter2_reg;
            end if;
        end if;
    end process;
    zext_ln182_cast_reg_279(11) <= '0';

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    acc_2_fu_239_p2 <= std_logic_vector(unsigned(zext_ln202_fu_235_p1) + unsigned(acc_fu_66));
    acc_2_out <= acc_fu_66;

    acc_2_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln192_reg_284_pp0_iter2_reg, ap_loop_exit_ready_pp0_iter3_reg)
    begin
        if (((icmp_ln192_reg_284_pp0_iter2_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_1))) then 
            acc_2_out_ap_vld <= ap_const_logic_1;
        else 
            acc_2_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    add_ln192_fu_160_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_kx_1) + unsigned(ap_const_lv2_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln192_fu_154_p2)
    begin
        if (((icmp_ln192_fu_154_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_loop_exit_ready_pp0_iter3_reg, ap_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_kx_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, kx_fu_70)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_kx_1 <= ap_const_lv2_0;
        else 
            ap_sig_allocacmp_kx_1 <= kx_fu_70;
        end if; 
    end process;

    grp_fu_254_p2 <= ap_const_lv12_640(11 - 1 downto 0);
    grp_fu_254_p3 <= zext_ln182_cast_reg_279(11 - 1 downto 0);
    icmp_ln192_fu_154_p2 <= "1" when (ap_sig_allocacmp_kx_1 = ap_const_lv2_2) else "0";
    offset_w_fu_170_p2 <= std_logic_vector(unsigned(empty) + unsigned(ap_sig_allocacmp_kx_1));
    offset_x_fu_195_p3 <= (tmp_5_fu_186_p4 & trunc_ln193_reg_288_pp0_iter2_reg);
    p_shl_fu_214_p3 <= (scratchpad_1_1_q0 & ap_const_lv6_0);
    scratchpad_0_1_address0 <= zext_ln146_fu_176_p1(2 - 1 downto 0);

    scratchpad_0_1_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            scratchpad_0_1_ce0_local <= ap_const_logic_1;
        else 
            scratchpad_0_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    scratchpad_1_1_address0 <= zext_ln197_fu_202_p1(12 - 1 downto 0);
    scratchpad_1_1_ce0 <= scratchpad_1_1_ce0_local;

    scratchpad_1_1_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            scratchpad_1_1_ce0_local <= ap_const_logic_1;
        else 
            scratchpad_1_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    select_ln202_fu_228_p3 <= 
        sub_ln202_fu_222_p2 when (w_value_reg_298_pp0_iter3_reg(0) = '1') else 
        ap_const_lv14_0;
    sub_ln202_fu_222_p2 <= std_logic_vector(unsigned(p_shl_fu_214_p3) - unsigned(zext_ln199_fu_210_p1));
    tmp_5_fu_186_p1 <= grp_fu_254_p4;
    tmp_5_fu_186_p4 <= tmp_5_fu_186_p1(11 downto 1);
    trunc_ln193_fu_166_p1 <= ap_sig_allocacmp_kx_1(1 - 1 downto 0);
    zext_ln146_fu_176_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(offset_w_fu_170_p2),64));
    zext_ln182_cast_fu_137_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln182),12));
    zext_ln197_fu_202_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(offset_x_fu_195_p3),64));
    zext_ln199_fu_210_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(scratchpad_1_1_q0),14));
    zext_ln202_fu_235_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln202_fu_228_p3),32));
end behav;
