-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity execute_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m_axi_data_mem_0_AWVALID : OUT STD_LOGIC;
    m_axi_data_mem_0_AWREADY : IN STD_LOGIC;
    m_axi_data_mem_0_AWADDR : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_data_mem_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_data_mem_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_data_mem_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_data_mem_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_data_mem_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_data_mem_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_data_mem_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_data_mem_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_data_mem_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_data_mem_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_data_mem_0_WVALID : OUT STD_LOGIC;
    m_axi_data_mem_0_WREADY : IN STD_LOGIC;
    m_axi_data_mem_0_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_data_mem_0_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_data_mem_0_WLAST : OUT STD_LOGIC;
    m_axi_data_mem_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_data_mem_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_data_mem_0_ARVALID : OUT STD_LOGIC;
    m_axi_data_mem_0_ARREADY : IN STD_LOGIC;
    m_axi_data_mem_0_ARADDR : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_data_mem_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_data_mem_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_data_mem_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_data_mem_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_data_mem_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_data_mem_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_data_mem_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_data_mem_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_data_mem_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_data_mem_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_data_mem_0_RVALID : IN STD_LOGIC;
    m_axi_data_mem_0_RREADY : OUT STD_LOGIC;
    m_axi_data_mem_0_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    m_axi_data_mem_0_RLAST : IN STD_LOGIC;
    m_axi_data_mem_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_data_mem_0_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
    m_axi_data_mem_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_data_mem_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_data_mem_0_BVALID : IN STD_LOGIC;
    m_axi_data_mem_0_BREADY : OUT STD_LOGIC;
    m_axi_data_mem_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_data_mem_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_data_mem_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    stream_o_TREADY : IN STD_LOGIC;
    mul_ln20 : IN STD_LOGIC_VECTOR (50 downto 0);
    data_port : IN STD_LOGIC_VECTOR (31 downto 0);
    stream_o_TDATA : OUT STD_LOGIC_VECTOR (23 downto 0);
    stream_o_TVALID : OUT STD_LOGIC;
    stream_o_TKEEP : OUT STD_LOGIC_VECTOR (2 downto 0);
    stream_o_TSTRB : OUT STD_LOGIC_VECTOR (2 downto 0);
    stream_o_TUSER : OUT STD_LOGIC_VECTOR (31 downto 0);
    stream_o_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    stream_o_TID : OUT STD_LOGIC_VECTOR (0 downto 0);
    stream_o_TDEST : OUT STD_LOGIC_VECTOR (0 downto 0) );
end;


architecture behav of execute_execute_Pipeline_VITIS_LOOP_24_1_VITIS_LOOP_221_1_VITIS_LOOP_226_2 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_fsm_pp0_stage2 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_fsm_pp0_stage3 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv21_0 : STD_LOGIC_VECTOR (20 downto 0) := "000000000000000000000";
    constant ap_const_lv20_0 : STD_LOGIC_VECTOR (19 downto 0) := "00000000000000000000";
    constant ap_const_lv51_0 : STD_LOGIC_VECTOR (50 downto 0) := "000000000000000000000000000000000000000000000000000";
    constant ap_const_lv3_7 : STD_LOGIC_VECTOR (2 downto 0) := "111";
    constant ap_const_lv51_1 : STD_LOGIC_VECTOR (50 downto 0) := "000000000000000000000000000000000000000000000000001";
    constant ap_const_lv20_7E900 : STD_LOGIC_VECTOR (19 downto 0) := "01111110100100000000";
    constant ap_const_lv11_780 : STD_LOGIC_VECTOR (10 downto 0) := "11110000000";
    constant ap_const_lv11_1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv21_3 : STD_LOGIC_VECTOR (20 downto 0) := "000000000000000000011";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv11_77F : STD_LOGIC_VECTOR (10 downto 0) := "11101111111";
    constant ap_const_lv11_4 : STD_LOGIC_VECTOR (10 downto 0) := "00000000100";
    constant ap_const_lv21_5A0 : STD_LOGIC_VECTOR (20 downto 0) := "000000000010110100000";
    constant ap_const_lv20_1 : STD_LOGIC_VECTOR (19 downto 0) := "00000000000000000001";
    constant ap_const_lv23_4 : STD_LOGIC_VECTOR (22 downto 0) := "00000000000000000000100";
    constant ap_const_lv23_8 : STD_LOGIC_VECTOR (22 downto 0) := "00000000000000000001000";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage3 : signal is "none";
    signal icmp_ln24_reg_763 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state4_io_grp2 : BOOLEAN;
    signal ap_block_pp0_stage3_subdone_grp2_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage3_subdone_grp2 : BOOLEAN;
    signal ap_block_pp0_stage3_subdone : BOOLEAN;
    signal ap_enable_reg_pp0_iter0_reg : STD_LOGIC := '0';
    signal ap_block_pp0_stage3_subdone_grp6_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage3_subdone_grp6 : BOOLEAN;
    signal ap_condition_exit_pp0_iter0_stage3 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal data_mem_blk_n_AR : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage2 : signal is "none";
    signal ap_block_pp0_stage2_grp1 : BOOLEAN;
    signal ap_block_pp0_stage2_subdone_grp1_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage2_subdone_grp1 : BOOLEAN;
    signal ap_block_pp0_stage2_subdone : BOOLEAN;
    signal data_mem_blk_n_R : STD_LOGIC;
    signal ap_block_pp0_stage3_grp2 : BOOLEAN;
    signal ap_block_pp0_stage0_grp3 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone_grp3_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage0_subdone_grp3 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal stream_o_TDATA_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage3_grp6 : BOOLEAN;
    signal ap_block_pp0_stage0_grp8 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone_grp8_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage0_subdone_grp8 : BOOLEAN;
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal ap_block_pp0_stage1_grp9 : BOOLEAN;
    signal ap_block_pp0_stage2_grp10 : BOOLEAN;
    signal ap_block_pp0_stage2_subdone_grp10_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage2_subdone_grp10 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_grp0 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone_grp0_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage0_subdone_grp0 : BOOLEAN;
    signal icmp_ln24_fu_282_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage1_11001 : BOOLEAN;
    signal icmp_ln24_reg_763_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln24_reg_763_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln221_fu_311_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln221_reg_767 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln221_reg_767_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln221_reg_767_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln_fu_399_p3 : STD_LOGIC_VECTOR (22 downto 0);
    signal shl_ln_reg_772 : STD_LOGIC_VECTOR (22 downto 0);
    signal trunc_ln_reg_778 : STD_LOGIC_VECTOR (29 downto 0);
    signal sof_fu_438_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sof_reg_783 : STD_LOGIC_VECTOR (0 downto 0);
    signal sof_reg_783_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal sof_reg_783_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal px_last_fu_462_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal px_last_reg_788 : STD_LOGIC_VECTOR (0 downto 0);
    signal px_last_reg_788_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal px_last_reg_788_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal px_last_reg_788_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state3_io_grp1 : BOOLEAN;
    signal ap_block_pp0_stage2_11001_grp1 : BOOLEAN;
    signal trunc_ln1_reg_799 : STD_LOGIC_VECTOR (29 downto 0);
    signal ap_block_pp0_stage2_11001_grp0 : BOOLEAN;
    signal ap_block_pp0_stage2_subdone_grp0_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage2_subdone_grp0 : BOOLEAN;
    signal trunc_ln2_reg_804 : STD_LOGIC_VECTOR (29 downto 0);
    signal ap_block_pp0_stage3_11001_grp2 : BOOLEAN;
    signal ap_block_state5_io_grp3 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_grp3 : BOOLEAN;
    signal px_data_reg_821 : STD_LOGIC_VECTOR (23 downto 0);
    signal trunc_ln249_fu_617_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln249_reg_826 : STD_LOGIC_VECTOR (7 downto 0);
    signal px_user_fu_641_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal px_user_reg_831 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage3_11001_grp6 : BOOLEAN;
    signal tmp_2_reg_836 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln261_fu_659_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln261_reg_841 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_4_reg_846 : STD_LOGIC_VECTOR (7 downto 0);
    signal px_data_3_fu_685_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal px_data_3_reg_851 : STD_LOGIC_VECTOR (23 downto 0);
    signal sext_ln230_fu_529_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln231_fu_587_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln232_fu_597_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal j_fu_134 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    signal j_2_fu_468_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_block_pp0_stage1 : BOOLEAN;
    signal offset_fu_138 : STD_LOGIC_VECTOR (20 downto 0) := "000000000000000000000";
    signal add_ln232_fu_426_p2 : STD_LOGIC_VECTOR (20 downto 0);
    signal add_ln2214_fu_142 : STD_LOGIC_VECTOR (20 downto 0) := "000000000000000000000";
    signal add_ln221_fu_474_p2 : STD_LOGIC_VECTOR (20 downto 0);
    signal i_fu_146 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    signal select_ln221_3_fu_391_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal indvars_iv_fu_150 : STD_LOGIC_VECTOR (20 downto 0) := "000000000000000000000";
    signal select_ln221_2_fu_383_p3 : STD_LOGIC_VECTOR (20 downto 0);
    signal indvar_flatten_fu_154 : STD_LOGIC_VECTOR (19 downto 0) := "00000000000000000000";
    signal select_ln221_4_fu_486_p3 : STD_LOGIC_VECTOR (19 downto 0);
    signal frame_no_fu_158 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal select_ln24_fu_630_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal indvar_flatten17_fu_162 : STD_LOGIC_VECTOR (50 downto 0) := "000000000000000000000000000000000000000000000000000";
    signal add_ln24_fu_287_p2 : STD_LOGIC_VECTOR (50 downto 0);
    signal ap_block_pp0_stage3_01001_grp6 : BOOLEAN;
    signal px_data_1_fu_668_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_block_pp0_stage0_01001_grp8 : BOOLEAN;
    signal px_data_2_fu_689_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_block_pp0_stage1_01001_grp9 : BOOLEAN;
    signal ap_block_pp0_stage2_01001_grp10 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_grp8 : BOOLEAN;
    signal ap_block_pp0_stage1_11001_grp9 : BOOLEAN;
    signal ap_block_pp0_stage2_11001_grp10 : BOOLEAN;
    signal icmp_ln226_fu_349_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln23_1_fu_325_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal or_ln23_fu_355_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln23_2_fu_333_p3 : STD_LOGIC_VECTOR (20 downto 0);
    signal select_ln23_3_fu_341_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln23_fu_317_p3 : STD_LOGIC_VECTOR (20 downto 0);
    signal i_2_fu_361_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln221_fu_367_p3 : STD_LOGIC_VECTOR (20 downto 0);
    signal zext_ln230_fu_407_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln230_fu_411_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln221_1_fu_375_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal or_ln242_fu_432_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_5_fu_444_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal j_1_fu_454_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln221_2_fu_480_p2 : STD_LOGIC_VECTOR (19 downto 0);
    signal ap_block_pp0_stage2_grp0 : BOOLEAN;
    signal add_ln231_fu_539_p2 : STD_LOGIC_VECTOR (22 downto 0);
    signal zext_ln231_fu_544_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln231_1_fu_548_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln232_1_fu_563_p2 : STD_LOGIC_VECTOR (22 downto 0);
    signal zext_ln232_fu_568_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln232_2_fu_572_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln24_1_fu_624_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln145_fu_637_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_block_pp0_stage3_11001 : BOOLEAN;
    signal ap_condition_exit_pp0_iter2_stage2 : STD_LOGIC;
    signal ap_idle_pp0_0to1 : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_idle_pp0_1to3 : STD_LOGIC;
    signal ap_done_pending_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_condition_792 : BOOLEAN;
    signal ap_condition_795 : BOOLEAN;
    signal ap_condition_798 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component execute_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component execute_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage3,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_block_pp0_stage0_subdone_grp0_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage0_subdone_grp0_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then
                    if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                        ap_block_pp0_stage0_subdone_grp0_done_reg <= ap_const_boolean_0;
                    elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0)) then 
                        ap_block_pp0_stage0_subdone_grp0_done_reg <= ap_const_boolean_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_block_pp0_stage0_subdone_grp3_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage0_subdone_grp3_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then
                    if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                        ap_block_pp0_stage0_subdone_grp3_done_reg <= ap_const_boolean_0;
                    elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp3)) then 
                        ap_block_pp0_stage0_subdone_grp3_done_reg <= ap_const_boolean_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_block_pp0_stage0_subdone_grp8_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage0_subdone_grp8_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then
                    if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                        ap_block_pp0_stage0_subdone_grp8_done_reg <= ap_const_boolean_0;
                    elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp8)) then 
                        ap_block_pp0_stage0_subdone_grp8_done_reg <= ap_const_boolean_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_block_pp0_stage2_subdone_grp0_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage2_subdone_grp0_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) then
                    if ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone)) then 
                        ap_block_pp0_stage2_subdone_grp0_done_reg <= ap_const_boolean_0;
                    elsif ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp0)) then 
                        ap_block_pp0_stage2_subdone_grp0_done_reg <= ap_const_boolean_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_block_pp0_stage2_subdone_grp10_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage2_subdone_grp10_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) then
                    if ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone)) then 
                        ap_block_pp0_stage2_subdone_grp10_done_reg <= ap_const_boolean_0;
                    elsif ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp10)) then 
                        ap_block_pp0_stage2_subdone_grp10_done_reg <= ap_const_boolean_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_block_pp0_stage2_subdone_grp1_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage2_subdone_grp1_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) then
                    if ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone)) then 
                        ap_block_pp0_stage2_subdone_grp1_done_reg <= ap_const_boolean_0;
                    elsif ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp1)) then 
                        ap_block_pp0_stage2_subdone_grp1_done_reg <= ap_const_boolean_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_block_pp0_stage3_subdone_grp2_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage3_subdone_grp2_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage3)) then
                    if ((ap_const_boolean_0 = ap_block_pp0_stage3_subdone)) then 
                        ap_block_pp0_stage3_subdone_grp2_done_reg <= ap_const_boolean_0;
                    elsif ((ap_const_boolean_0 = ap_block_pp0_stage3_subdone_grp2)) then 
                        ap_block_pp0_stage3_subdone_grp2_done_reg <= ap_const_boolean_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_block_pp0_stage3_subdone_grp6_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage3_subdone_grp6_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage3)) then
                    if ((ap_const_boolean_0 = ap_block_pp0_stage3_subdone)) then 
                        ap_block_pp0_stage3_subdone_grp6_done_reg <= ap_const_boolean_0;
                    elsif ((ap_const_boolean_0 = ap_block_pp0_stage3_subdone_grp6)) then 
                        ap_block_pp0_stage3_subdone_grp6_done_reg <= ap_const_boolean_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage3)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_const_boolean_0 = ap_block_pp0_stage3_subdone))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_const_boolean_0 = ap_block_pp0_stage3_subdone))) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone))) then 
                    ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_const_boolean_0 = ap_block_pp0_stage3_subdone))) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_loop_exit_ready_pp0_iter1_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to1 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter2_stage2))) then 
                ap_loop_exit_ready_pp0_iter1_reg <= ap_const_logic_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001))) then 
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
            end if; 
        end if;
    end process;

    ap_loop_exit_ready_pp0_iter2_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to1 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter2_stage2))) then 
                ap_loop_exit_ready_pp0_iter2_reg <= ap_const_logic_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001))) then 
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
            end if; 
        end if;
    end process;

    frame_no_fu_158_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
                frame_no_fu_158 <= ap_const_lv32_0;
            elsif (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001_grp6) and (ap_const_boolean_0 = ap_block_pp0_stage3_subdone_grp6_done_reg))) then 
                frame_no_fu_158 <= select_ln24_fu_630_p3;
            end if; 
        end if;
    end process;

    i_fu_146_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
                i_fu_146 <= ap_const_lv11_0;
            elsif (((icmp_ln24_fu_282_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then 
                i_fu_146 <= select_ln221_3_fu_391_p3;
            end if; 
        end if;
    end process;

    indvar_flatten17_fu_162_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
                indvar_flatten17_fu_162 <= ap_const_lv51_0;
            elsif (((icmp_ln24_fu_282_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then 
                indvar_flatten17_fu_162 <= add_ln24_fu_287_p2;
            end if; 
        end if;
    end process;

    indvar_flatten_fu_154_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
                indvar_flatten_fu_154 <= ap_const_lv20_0;
            elsif (((icmp_ln24_fu_282_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then 
                indvar_flatten_fu_154 <= select_ln221_4_fu_486_p3;
            end if; 
        end if;
    end process;

    indvars_iv_fu_150_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
                indvars_iv_fu_150 <= ap_const_lv21_0;
            elsif (((icmp_ln24_fu_282_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then 
                indvars_iv_fu_150 <= select_ln221_2_fu_383_p3;
            end if; 
        end if;
    end process;

    j_fu_134_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
                j_fu_134 <= ap_const_lv11_0;
            elsif (((icmp_ln24_fu_282_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then 
                j_fu_134 <= j_2_fu_468_p2;
            end if; 
        end if;
    end process;

    offset_fu_138_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
                offset_fu_138 <= ap_const_lv21_0;
            elsif (((icmp_ln24_fu_282_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then 
                offset_fu_138 <= add_ln232_fu_426_p2;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln24_fu_282_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then
                add_ln2214_fu_142 <= add_ln221_fu_474_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then
                icmp_ln221_reg_767 <= icmp_ln221_fu_311_p2;
                icmp_ln221_reg_767_pp0_iter1_reg <= icmp_ln221_reg_767;
                icmp_ln221_reg_767_pp0_iter2_reg <= icmp_ln221_reg_767_pp0_iter1_reg;
                icmp_ln24_reg_763 <= icmp_ln24_fu_282_p2;
                icmp_ln24_reg_763_pp0_iter1_reg <= icmp_ln24_reg_763;
                icmp_ln24_reg_763_pp0_iter2_reg <= icmp_ln24_reg_763_pp0_iter1_reg;
                px_last_reg_788 <= px_last_fu_462_p2;
                px_last_reg_788_pp0_iter1_reg <= px_last_reg_788;
                px_last_reg_788_pp0_iter2_reg <= px_last_reg_788_pp0_iter1_reg;
                px_last_reg_788_pp0_iter3_reg <= px_last_reg_788_pp0_iter2_reg;
                    shl_ln_reg_772(22 downto 2) <= shl_ln_fu_399_p3(22 downto 2);
                sof_reg_783 <= sof_fu_438_p2;
                sof_reg_783_pp0_iter1_reg <= sof_reg_783;
                sof_reg_783_pp0_iter2_reg <= sof_reg_783_pp0_iter1_reg;
                trunc_ln_reg_778 <= add_ln230_fu_411_p2(31 downto 2);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp3) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp3_done_reg))) then
                px_data_3_reg_851 <= px_data_3_fu_685_p1;
                tmp_4_reg_846 <= m_axi_data_mem_0_RDATA(31 downto 24);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001_grp1) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp1_done_reg))) then
                px_data_reg_821 <= m_axi_data_mem_0_RDATA(31 downto 8);
                trunc_ln249_reg_826 <= trunc_ln249_fu_617_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001_grp6) and (ap_const_boolean_0 = ap_block_pp0_stage3_subdone_grp6_done_reg))) then
                px_user_reg_831 <= px_user_fu_641_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001_grp2) and (ap_const_boolean_0 = ap_block_pp0_stage3_subdone_grp2_done_reg))) then
                tmp_2_reg_836 <= m_axi_data_mem_0_RDATA(31 downto 16);
                trunc_ln261_reg_841 <= trunc_ln261_fu_659_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001_grp0))) then
                trunc_ln1_reg_799 <= add_ln231_1_fu_548_p2(31 downto 2);
                trunc_ln2_reg_804 <= add_ln232_2_fu_572_p2(31 downto 2);
            end if;
        end if;
    end process;
    shl_ln_reg_772(1 downto 0) <= "00";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage3_subdone, ap_block_pp0_stage2_subdone, ap_block_pp0_stage0_subdone, ap_condition_exit_pp0_iter2_stage2, ap_idle_pp0_0to1, ap_idle_pp0_1to3, ap_done_pending_pp0, ap_block_pp0_stage1_subdone, ap_start_int)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((ap_start_int = ap_const_logic_0) and (ap_done_pending_pp0 = ap_const_logic_0) and (ap_idle_pp0_1to3 = ap_const_logic_1))) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when ap_ST_fsm_pp0_stage2 => 
                if (((ap_idle_pp0_0to1 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter2_stage2))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage3;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                end if;
            when ap_ST_fsm_pp0_stage3 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage3_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage3;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;
    add_ln221_2_fu_480_p2 <= std_logic_vector(unsigned(indvar_flatten_fu_154) + unsigned(ap_const_lv20_1));
    add_ln221_fu_474_p2 <= std_logic_vector(unsigned(select_ln221_2_fu_383_p3) + unsigned(ap_const_lv21_5A0));
    add_ln230_fu_411_p2 <= std_logic_vector(unsigned(zext_ln230_fu_407_p1) + unsigned(data_port));
    add_ln231_1_fu_548_p2 <= std_logic_vector(unsigned(zext_ln231_fu_544_p1) + unsigned(data_port));
    add_ln231_fu_539_p2 <= std_logic_vector(unsigned(shl_ln_reg_772) + unsigned(ap_const_lv23_4));
    add_ln232_1_fu_563_p2 <= std_logic_vector(unsigned(shl_ln_reg_772) + unsigned(ap_const_lv23_8));
    add_ln232_2_fu_572_p2 <= std_logic_vector(unsigned(zext_ln232_fu_568_p1) + unsigned(data_port));
    add_ln232_fu_426_p2 <= std_logic_vector(unsigned(select_ln221_fu_367_p3) + unsigned(ap_const_lv21_3));
    add_ln24_1_fu_624_p2 <= std_logic_vector(unsigned(frame_no_fu_158) + unsigned(ap_const_lv32_1));
    add_ln24_fu_287_p2 <= std_logic_vector(unsigned(indvar_flatten17_fu_162) + unsigned(ap_const_lv51_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(1);
    ap_CS_fsm_pp0_stage2 <= ap_CS_fsm(2);
    ap_CS_fsm_pp0_stage3 <= ap_CS_fsm(3);

    ap_block_pp0_stage0_01001_grp8_assign_proc : process(ap_enable_reg_pp0_iter3, stream_o_TREADY, ap_block_pp0_stage0_subdone_grp8_done_reg)
    begin
                ap_block_pp0_stage0_01001_grp8 <= ((stream_o_TREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp8_done_reg));
    end process;

        ap_block_pp0_stage0_11001_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_grp3_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter3, m_axi_data_mem_0_RVALID, ap_block_pp0_stage0_subdone_grp3_done_reg, ap_block_state5_io_grp3)
    begin
                ap_block_pp0_stage0_11001_grp3 <= (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state5_io_grp3) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp3_done_reg)) or ((m_axi_data_mem_0_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp3_done_reg)));
    end process;


    ap_block_pp0_stage0_11001_grp8_assign_proc : process(ap_enable_reg_pp0_iter3, stream_o_TREADY, ap_block_pp0_stage0_subdone_grp8_done_reg)
    begin
                ap_block_pp0_stage0_11001_grp8 <= ((stream_o_TREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp8_done_reg));
    end process;

        ap_block_pp0_stage0_grp3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_grp8 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter3, m_axi_data_mem_0_RVALID, stream_o_TREADY, ap_block_pp0_stage0_subdone_grp3_done_reg, ap_block_pp0_stage0_subdone_grp8_done_reg, ap_block_state5_io_grp3)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (((stream_o_TREADY = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp8_done_reg)) or ((m_axi_data_mem_0_RVALID = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp3_done_reg)))) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state5_io_grp3) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp3_done_reg)));
    end process;

        ap_block_pp0_stage0_subdone_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_grp3_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter3, m_axi_data_mem_0_RVALID, ap_block_pp0_stage0_subdone_grp3_done_reg, ap_block_state5_io_grp3)
    begin
                ap_block_pp0_stage0_subdone_grp3 <= (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state5_io_grp3) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp3_done_reg)) or ((m_axi_data_mem_0_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp3_done_reg)));
    end process;


    ap_block_pp0_stage0_subdone_grp8_assign_proc : process(ap_enable_reg_pp0_iter3, stream_o_TREADY, ap_block_pp0_stage0_subdone_grp8_done_reg)
    begin
                ap_block_pp0_stage0_subdone_grp8 <= ((stream_o_TREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp8_done_reg));
    end process;

        ap_block_pp0_stage1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage1_01001_grp9_assign_proc : process(ap_enable_reg_pp0_iter3, stream_o_TREADY)
    begin
                ap_block_pp0_stage1_01001_grp9 <= ((stream_o_TREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage1_11001_assign_proc : process(ap_enable_reg_pp0_iter3, stream_o_TREADY)
    begin
                ap_block_pp0_stage1_11001 <= ((stream_o_TREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage1_11001_grp9_assign_proc : process(ap_enable_reg_pp0_iter3, stream_o_TREADY)
    begin
                ap_block_pp0_stage1_11001_grp9 <= ((stream_o_TREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1));
    end process;

        ap_block_pp0_stage1_grp9 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage1_subdone_assign_proc : process(ap_enable_reg_pp0_iter3, stream_o_TREADY)
    begin
                ap_block_pp0_stage1_subdone <= ((stream_o_TREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage2_01001_grp10_assign_proc : process(ap_enable_reg_pp0_iter3, stream_o_TREADY, ap_block_pp0_stage2_subdone_grp10_done_reg)
    begin
                ap_block_pp0_stage2_01001_grp10 <= ((stream_o_TREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp10_done_reg));
    end process;

        ap_block_pp0_stage2_11001_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage2_11001_grp1_assign_proc : process(ap_enable_reg_pp0_iter2, m_axi_data_mem_0_RVALID, ap_enable_reg_pp0_iter0_reg, ap_block_pp0_stage2_subdone_grp1_done_reg, ap_block_state3_io_grp1)
    begin
                ap_block_pp0_stage2_11001_grp1 <= (((ap_const_boolean_1 = ap_block_state3_io_grp1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp1_done_reg)) or ((m_axi_data_mem_0_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp1_done_reg)));
    end process;


    ap_block_pp0_stage2_11001_grp10_assign_proc : process(ap_enable_reg_pp0_iter3, stream_o_TREADY, ap_block_pp0_stage2_subdone_grp10_done_reg)
    begin
                ap_block_pp0_stage2_11001_grp10 <= ((stream_o_TREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp10_done_reg));
    end process;

        ap_block_pp0_stage2_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2_grp1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2_grp10 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage2_subdone_assign_proc : process(ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, m_axi_data_mem_0_RVALID, stream_o_TREADY, ap_enable_reg_pp0_iter0_reg, ap_block_pp0_stage2_subdone_grp1_done_reg, ap_block_pp0_stage2_subdone_grp10_done_reg, ap_block_state3_io_grp1)
    begin
                ap_block_pp0_stage2_subdone <= (((ap_const_boolean_1 = ap_block_state3_io_grp1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp1_done_reg)) or ((stream_o_TREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp10_done_reg)) or ((m_axi_data_mem_0_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp1_done_reg)));
    end process;

        ap_block_pp0_stage2_subdone_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage2_subdone_grp1_assign_proc : process(ap_enable_reg_pp0_iter2, m_axi_data_mem_0_RVALID, ap_enable_reg_pp0_iter0_reg, ap_block_pp0_stage2_subdone_grp1_done_reg, ap_block_state3_io_grp1)
    begin
                ap_block_pp0_stage2_subdone_grp1 <= (((ap_const_boolean_1 = ap_block_state3_io_grp1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp1_done_reg)) or ((m_axi_data_mem_0_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp1_done_reg)));
    end process;


    ap_block_pp0_stage2_subdone_grp10_assign_proc : process(ap_enable_reg_pp0_iter3, stream_o_TREADY, ap_block_pp0_stage2_subdone_grp10_done_reg)
    begin
                ap_block_pp0_stage2_subdone_grp10 <= ((stream_o_TREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp10_done_reg));
    end process;


    ap_block_pp0_stage3_01001_grp6_assign_proc : process(ap_enable_reg_pp0_iter2, stream_o_TREADY, ap_block_pp0_stage3_subdone_grp6_done_reg)
    begin
                ap_block_pp0_stage3_01001_grp6 <= ((stream_o_TREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3_subdone_grp6_done_reg));
    end process;


    ap_block_pp0_stage3_11001_assign_proc : process(ap_enable_reg_pp0_iter2, m_axi_data_mem_0_RVALID, stream_o_TREADY, ap_block_state4_io_grp2, ap_block_pp0_stage3_subdone_grp2_done_reg, ap_enable_reg_pp0_iter0_reg, ap_block_pp0_stage3_subdone_grp6_done_reg)
    begin
                ap_block_pp0_stage3_11001 <= (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (((stream_o_TREADY = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage3_subdone_grp6_done_reg)) or ((m_axi_data_mem_0_RVALID = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage3_subdone_grp2_done_reg)))) or ((ap_const_boolean_1 = ap_block_state4_io_grp2) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3_subdone_grp2_done_reg)));
    end process;


    ap_block_pp0_stage3_11001_grp2_assign_proc : process(ap_enable_reg_pp0_iter2, m_axi_data_mem_0_RVALID, ap_block_state4_io_grp2, ap_block_pp0_stage3_subdone_grp2_done_reg, ap_enable_reg_pp0_iter0_reg)
    begin
                ap_block_pp0_stage3_11001_grp2 <= (((m_axi_data_mem_0_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3_subdone_grp2_done_reg)) or ((ap_const_boolean_1 = ap_block_state4_io_grp2) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3_subdone_grp2_done_reg)));
    end process;


    ap_block_pp0_stage3_11001_grp6_assign_proc : process(ap_enable_reg_pp0_iter2, stream_o_TREADY, ap_block_pp0_stage3_subdone_grp6_done_reg)
    begin
                ap_block_pp0_stage3_11001_grp6 <= ((stream_o_TREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3_subdone_grp6_done_reg));
    end process;

        ap_block_pp0_stage3_grp2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage3_grp6 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage3_subdone_assign_proc : process(ap_enable_reg_pp0_iter2, m_axi_data_mem_0_RVALID, stream_o_TREADY, ap_block_state4_io_grp2, ap_block_pp0_stage3_subdone_grp2_done_reg, ap_enable_reg_pp0_iter0_reg, ap_block_pp0_stage3_subdone_grp6_done_reg)
    begin
                ap_block_pp0_stage3_subdone <= (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (((stream_o_TREADY = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage3_subdone_grp6_done_reg)) or ((m_axi_data_mem_0_RVALID = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage3_subdone_grp2_done_reg)))) or ((ap_const_boolean_1 = ap_block_state4_io_grp2) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3_subdone_grp2_done_reg)));
    end process;


    ap_block_pp0_stage3_subdone_grp2_assign_proc : process(ap_enable_reg_pp0_iter2, m_axi_data_mem_0_RVALID, ap_block_state4_io_grp2, ap_block_pp0_stage3_subdone_grp2_done_reg, ap_enable_reg_pp0_iter0_reg)
    begin
                ap_block_pp0_stage3_subdone_grp2 <= (((m_axi_data_mem_0_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3_subdone_grp2_done_reg)) or ((ap_const_boolean_1 = ap_block_state4_io_grp2) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3_subdone_grp2_done_reg)));
    end process;


    ap_block_pp0_stage3_subdone_grp6_assign_proc : process(ap_enable_reg_pp0_iter2, stream_o_TREADY, ap_block_pp0_stage3_subdone_grp6_done_reg)
    begin
                ap_block_pp0_stage3_subdone_grp6 <= ((stream_o_TREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3_subdone_grp6_done_reg));
    end process;


    ap_block_state3_io_grp1_assign_proc : process(m_axi_data_mem_0_ARREADY, icmp_ln24_reg_763)
    begin
                ap_block_state3_io_grp1 <= ((icmp_ln24_reg_763 = ap_const_lv1_0) and (m_axi_data_mem_0_ARREADY = ap_const_logic_0));
    end process;


    ap_block_state4_io_grp2_assign_proc : process(m_axi_data_mem_0_ARREADY, icmp_ln24_reg_763)
    begin
                ap_block_state4_io_grp2 <= ((icmp_ln24_reg_763 = ap_const_lv1_0) and (m_axi_data_mem_0_ARREADY = ap_const_logic_0));
    end process;


    ap_block_state5_io_grp3_assign_proc : process(m_axi_data_mem_0_ARREADY, icmp_ln24_reg_763)
    begin
                ap_block_state5_io_grp3 <= ((icmp_ln24_reg_763 = ap_const_lv1_0) and (m_axi_data_mem_0_ARREADY = ap_const_logic_0));
    end process;


    ap_condition_792_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_subdone_grp1_done_reg, ap_block_pp0_stage2_11001_grp1)
    begin
                ap_condition_792 <= ((ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001_grp1) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp1_done_reg));
    end process;


    ap_condition_795_assign_proc : process(ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3_subdone_grp2_done_reg, ap_enable_reg_pp0_iter0_reg, ap_block_pp0_stage3_11001_grp2)
    begin
                ap_condition_795 <= ((ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001_grp2) and (ap_const_boolean_0 = ap_block_pp0_stage3_subdone_grp2_done_reg));
    end process;


    ap_condition_798_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone_grp3_done_reg, ap_block_pp0_stage0_11001_grp3)
    begin
                ap_condition_798 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp3) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp3_done_reg));
    end process;


    ap_condition_exit_pp0_iter0_stage3_assign_proc : process(ap_CS_fsm_pp0_stage3, icmp_ln24_reg_763, ap_block_pp0_stage3_subdone, ap_enable_reg_pp0_iter0_reg)
    begin
        if (((icmp_ln24_reg_763 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3_subdone))) then 
            ap_condition_exit_pp0_iter0_stage3 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage3 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_exit_pp0_iter2_stage2_assign_proc : process(ap_enable_reg_pp0_iter2, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_subdone, icmp_ln24_reg_763_pp0_iter2_reg)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln24_reg_763_pp0_iter2_reg = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone))) then 
            ap_condition_exit_pp0_iter2_stage2 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter2_stage2 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter2_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;


    ap_done_pending_pp0_assign_proc : process(ap_loop_exit_ready, ap_loop_exit_ready_pp0_iter1_reg, ap_loop_exit_ready_pp0_iter2_reg)
    begin
        if (not(((ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_0) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_0) and (ap_loop_exit_ready = ap_const_logic_0)))) then 
            ap_done_pending_pp0 <= ap_const_logic_1;
        else 
            ap_done_pending_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_enable_reg_pp0_iter0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0_reg, ap_start_int)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
            ap_enable_reg_pp0_iter0 <= ap_start_int;
        else 
            ap_enable_reg_pp0_iter0 <= ap_enable_reg_pp0_iter0_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_0to1_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0_0to1 <= ap_const_logic_1;
        else 
            ap_idle_pp0_0to1 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_1to3_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))) then 
            ap_idle_pp0_1to3 <= ap_const_logic_1;
        else 
            ap_idle_pp0_1to3 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage3;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3_subdone, ap_enable_reg_pp0_iter0_reg)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3_subdone))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    data_mem_blk_n_AR_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage3, m_axi_data_mem_0_ARREADY, icmp_ln24_reg_763, ap_block_pp0_stage3_subdone_grp2_done_reg, ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_grp1, ap_block_pp0_stage2_subdone_grp1_done_reg, ap_block_pp0_stage3_grp2, ap_block_pp0_stage0_grp3, ap_block_pp0_stage0_subdone_grp3_done_reg)
    begin
        if ((((icmp_ln24_reg_763 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3_grp2) and (ap_const_boolean_0 = ap_block_pp0_stage3_subdone_grp2_done_reg)) or ((icmp_ln24_reg_763 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp3_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp3)) or ((icmp_ln24_reg_763 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp1_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage2_grp1)))) then 
            data_mem_blk_n_AR <= m_axi_data_mem_0_ARREADY;
        else 
            data_mem_blk_n_AR <= ap_const_logic_1;
        end if; 
    end process;


    data_mem_blk_n_R_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_CS_fsm_pp0_stage3, m_axi_data_mem_0_RVALID, ap_block_pp0_stage3_subdone_grp2_done_reg, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_grp1, ap_block_pp0_stage2_subdone_grp1_done_reg, ap_block_pp0_stage3_grp2, ap_block_pp0_stage0_grp3, ap_block_pp0_stage0_subdone_grp3_done_reg)
    begin
        if ((((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp3_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp3)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_const_boolean_0 = ap_block_pp0_stage3_grp2) and (ap_const_boolean_0 = ap_block_pp0_stage3_subdone_grp2_done_reg)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp1_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage2_grp1)))) then 
            data_mem_blk_n_R <= m_axi_data_mem_0_RVALID;
        else 
            data_mem_blk_n_R <= ap_const_logic_1;
        end if; 
    end process;

    i_2_fu_361_p2 <= std_logic_vector(unsigned(select_ln23_1_fu_325_p3) + unsigned(ap_const_lv11_1));
    icmp_ln221_fu_311_p2 <= "1" when (indvar_flatten_fu_154 = ap_const_lv20_7E900) else "0";
    icmp_ln226_fu_349_p2 <= "1" when (unsigned(j_fu_134) < unsigned(ap_const_lv11_780)) else "0";
    icmp_ln24_fu_282_p2 <= "1" when (indvar_flatten17_fu_162 = mul_ln20) else "0";
    j_1_fu_454_p3 <= (tmp_5_fu_444_p4 & ap_const_lv2_3);
    j_2_fu_468_p2 <= std_logic_vector(unsigned(select_ln221_1_fu_375_p3) + unsigned(ap_const_lv11_4));

    m_axi_data_mem_0_ARADDR_assign_proc : process(icmp_ln24_reg_763, sext_ln230_fu_529_p1, sext_ln231_fu_587_p1, sext_ln232_fu_597_p1, ap_condition_792, ap_condition_795, ap_condition_798)
    begin
        if ((icmp_ln24_reg_763 = ap_const_lv1_0)) then
            if ((ap_const_boolean_1 = ap_condition_798)) then 
                m_axi_data_mem_0_ARADDR <= sext_ln232_fu_597_p1;
            elsif ((ap_const_boolean_1 = ap_condition_795)) then 
                m_axi_data_mem_0_ARADDR <= sext_ln231_fu_587_p1;
            elsif ((ap_const_boolean_1 = ap_condition_792)) then 
                m_axi_data_mem_0_ARADDR <= sext_ln230_fu_529_p1;
            else 
                m_axi_data_mem_0_ARADDR <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            m_axi_data_mem_0_ARADDR <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    m_axi_data_mem_0_ARBURST <= ap_const_lv2_0;
    m_axi_data_mem_0_ARCACHE <= ap_const_lv4_0;
    m_axi_data_mem_0_ARID <= ap_const_lv1_0;
    m_axi_data_mem_0_ARLEN <= ap_const_lv32_1;
    m_axi_data_mem_0_ARLOCK <= ap_const_lv2_0;
    m_axi_data_mem_0_ARPROT <= ap_const_lv3_0;
    m_axi_data_mem_0_ARQOS <= ap_const_lv4_0;
    m_axi_data_mem_0_ARREGION <= ap_const_lv4_0;
    m_axi_data_mem_0_ARSIZE <= ap_const_lv3_0;
    m_axi_data_mem_0_ARUSER <= ap_const_lv1_0;

    m_axi_data_mem_0_ARVALID_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage3, icmp_ln24_reg_763, ap_block_pp0_stage3_subdone_grp2_done_reg, ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_subdone_grp1_done_reg, ap_block_pp0_stage0_subdone_grp3_done_reg, ap_block_pp0_stage2_11001_grp1, ap_block_pp0_stage3_11001_grp2, ap_block_pp0_stage0_11001_grp3)
    begin
        if ((((icmp_ln24_reg_763 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001_grp2) and (ap_const_boolean_0 = ap_block_pp0_stage3_subdone_grp2_done_reg)) or ((icmp_ln24_reg_763 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp3) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp3_done_reg)) or ((icmp_ln24_reg_763 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001_grp1) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp1_done_reg)))) then 
            m_axi_data_mem_0_ARVALID <= ap_const_logic_1;
        else 
            m_axi_data_mem_0_ARVALID <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_data_mem_0_AWADDR <= ap_const_lv32_0;
    m_axi_data_mem_0_AWBURST <= ap_const_lv2_0;
    m_axi_data_mem_0_AWCACHE <= ap_const_lv4_0;
    m_axi_data_mem_0_AWID <= ap_const_lv1_0;
    m_axi_data_mem_0_AWLEN <= ap_const_lv32_0;
    m_axi_data_mem_0_AWLOCK <= ap_const_lv2_0;
    m_axi_data_mem_0_AWPROT <= ap_const_lv3_0;
    m_axi_data_mem_0_AWQOS <= ap_const_lv4_0;
    m_axi_data_mem_0_AWREGION <= ap_const_lv4_0;
    m_axi_data_mem_0_AWSIZE <= ap_const_lv3_0;
    m_axi_data_mem_0_AWUSER <= ap_const_lv1_0;
    m_axi_data_mem_0_AWVALID <= ap_const_logic_0;
    m_axi_data_mem_0_BREADY <= ap_const_logic_0;

    m_axi_data_mem_0_RREADY_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3_subdone_grp2_done_reg, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_subdone_grp1_done_reg, ap_block_pp0_stage0_subdone_grp3_done_reg, ap_block_pp0_stage2_11001_grp1, ap_block_pp0_stage3_11001_grp2, ap_block_pp0_stage0_11001_grp3)
    begin
        if ((((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp3) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp3_done_reg)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001_grp2) and (ap_const_boolean_0 = ap_block_pp0_stage3_subdone_grp2_done_reg)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001_grp1) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp1_done_reg)))) then 
            m_axi_data_mem_0_RREADY <= ap_const_logic_1;
        else 
            m_axi_data_mem_0_RREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_data_mem_0_WDATA <= ap_const_lv32_0;
    m_axi_data_mem_0_WID <= ap_const_lv1_0;
    m_axi_data_mem_0_WLAST <= ap_const_logic_0;
    m_axi_data_mem_0_WSTRB <= ap_const_lv4_0;
    m_axi_data_mem_0_WUSER <= ap_const_lv1_0;
    m_axi_data_mem_0_WVALID <= ap_const_logic_0;
    or_ln23_fu_355_p2 <= (icmp_ln226_fu_349_p2 or icmp_ln221_fu_311_p2);
    or_ln242_fu_432_p2 <= (select_ln221_3_fu_391_p3 or select_ln221_1_fu_375_p3);
    px_data_1_fu_668_p3 <= (trunc_ln249_reg_826 & tmp_2_reg_836);
    px_data_2_fu_689_p3 <= (trunc_ln261_reg_841 & tmp_4_reg_846);
    px_data_3_fu_685_p1 <= m_axi_data_mem_0_RDATA(24 - 1 downto 0);
    px_last_fu_462_p2 <= "1" when (j_1_fu_454_p3 = ap_const_lv11_77F) else "0";
    px_user_fu_641_p3 <= (trunc_ln145_fu_637_p1 & sof_reg_783_pp0_iter2_reg);
    select_ln221_1_fu_375_p3 <= 
        select_ln23_3_fu_341_p3 when (or_ln23_fu_355_p2(0) = '1') else 
        ap_const_lv11_0;
    select_ln221_2_fu_383_p3 <= 
        select_ln23_fu_317_p3 when (or_ln23_fu_355_p2(0) = '1') else 
        add_ln2214_fu_142;
    select_ln221_3_fu_391_p3 <= 
        select_ln23_1_fu_325_p3 when (or_ln23_fu_355_p2(0) = '1') else 
        i_2_fu_361_p2;
    select_ln221_4_fu_486_p3 <= 
        ap_const_lv20_1 when (icmp_ln221_fu_311_p2(0) = '1') else 
        add_ln221_2_fu_480_p2;
    select_ln221_fu_367_p3 <= 
        select_ln23_2_fu_333_p3 when (or_ln23_fu_355_p2(0) = '1') else 
        add_ln2214_fu_142;
    select_ln23_1_fu_325_p3 <= 
        ap_const_lv11_0 when (icmp_ln221_fu_311_p2(0) = '1') else 
        i_fu_146;
    select_ln23_2_fu_333_p3 <= 
        ap_const_lv21_0 when (icmp_ln221_fu_311_p2(0) = '1') else 
        offset_fu_138;
    select_ln23_3_fu_341_p3 <= 
        ap_const_lv11_0 when (icmp_ln221_fu_311_p2(0) = '1') else 
        j_fu_134;
    select_ln23_fu_317_p3 <= 
        ap_const_lv21_0 when (icmp_ln221_fu_311_p2(0) = '1') else 
        indvars_iv_fu_150;
    select_ln24_fu_630_p3 <= 
        add_ln24_1_fu_624_p2 when (icmp_ln221_reg_767_pp0_iter2_reg(0) = '1') else 
        frame_no_fu_158;
        sext_ln230_fu_529_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln_reg_778),32));

        sext_ln231_fu_587_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln1_reg_799),32));

        sext_ln232_fu_597_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln2_reg_804),32));

    shl_ln_fu_399_p3 <= (select_ln221_fu_367_p3 & ap_const_lv2_0);
    sof_fu_438_p2 <= "1" when (or_ln242_fu_432_p2 = ap_const_lv11_0) else "0";

    stream_o_TDATA_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3_subdone_grp6_done_reg, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage0_subdone_grp8_done_reg, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage2_subdone_grp10_done_reg, px_data_reg_821, px_data_3_reg_851, ap_block_pp0_stage3_01001_grp6, px_data_1_fu_668_p3, ap_block_pp0_stage0_01001_grp8, px_data_2_fu_689_p3, ap_block_pp0_stage1_01001_grp9, ap_block_pp0_stage2_01001_grp10)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_const_boolean_0 = ap_block_pp0_stage2_01001_grp10) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp10_done_reg))) then 
            stream_o_TDATA <= px_data_3_reg_851;
        elsif (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_01001_grp9))) then 
            stream_o_TDATA <= px_data_2_fu_689_p3;
        elsif (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_01001_grp8) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp8_done_reg))) then 
            stream_o_TDATA <= px_data_1_fu_668_p3;
        elsif (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_const_boolean_0 = ap_block_pp0_stage3_01001_grp6) and (ap_const_boolean_0 = ap_block_pp0_stage3_subdone_grp6_done_reg))) then 
            stream_o_TDATA <= px_data_reg_821;
        else 
            stream_o_TDATA <= "XXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    stream_o_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_CS_fsm_pp0_stage3, stream_o_TREADY, ap_block_pp0_stage3_subdone_grp6_done_reg, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage3_grp6, ap_block_pp0_stage0_grp8, ap_block_pp0_stage0_subdone_grp8_done_reg, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_grp9, ap_block_pp0_stage2_grp10, ap_block_pp0_stage2_subdone_grp10_done_reg)
    begin
        if ((((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_grp9)) or ((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp8_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp8)) or ((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp10_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage2_grp10)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_const_boolean_0 = ap_block_pp0_stage3_grp6) and (ap_const_boolean_0 = ap_block_pp0_stage3_subdone_grp6_done_reg)))) then 
            stream_o_TDATA_blk_n <= stream_o_TREADY;
        else 
            stream_o_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    stream_o_TDEST <= ap_const_lv1_0;
    stream_o_TID <= ap_const_lv1_0;
    stream_o_TKEEP <= ap_const_lv3_7;

    stream_o_TLAST_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3_subdone_grp6_done_reg, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage0_subdone_grp8_done_reg, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage2_subdone_grp10_done_reg, px_last_reg_788_pp0_iter3_reg, ap_block_pp0_stage3_01001_grp6, ap_block_pp0_stage0_01001_grp8, ap_block_pp0_stage1_01001_grp9, ap_block_pp0_stage2_01001_grp10)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_const_boolean_0 = ap_block_pp0_stage2_01001_grp10) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp10_done_reg))) then 
            stream_o_TLAST <= px_last_reg_788_pp0_iter3_reg;
        elsif ((((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_01001_grp9)) or ((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_01001_grp8) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp8_done_reg)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_const_boolean_0 = ap_block_pp0_stage3_01001_grp6) and (ap_const_boolean_0 = ap_block_pp0_stage3_subdone_grp6_done_reg)))) then 
            stream_o_TLAST <= ap_const_lv1_0;
        else 
            stream_o_TLAST <= "X";
        end if; 
    end process;

    stream_o_TSTRB <= ap_const_lv3_7;

    stream_o_TUSER_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3_subdone_grp6_done_reg, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage0_subdone_grp8_done_reg, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage2_subdone_grp10_done_reg, px_user_fu_641_p3, px_user_reg_831, ap_block_pp0_stage3_01001_grp6, ap_block_pp0_stage0_01001_grp8, ap_block_pp0_stage1_01001_grp9, ap_block_pp0_stage2_01001_grp10)
    begin
        if ((((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_01001_grp9)) or ((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_01001_grp8) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp8_done_reg)) or ((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_const_boolean_0 = ap_block_pp0_stage2_01001_grp10) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp10_done_reg)))) then 
            stream_o_TUSER <= px_user_reg_831;
        elsif (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_const_boolean_0 = ap_block_pp0_stage3_01001_grp6) and (ap_const_boolean_0 = ap_block_pp0_stage3_subdone_grp6_done_reg))) then 
            stream_o_TUSER <= px_user_fu_641_p3;
        else 
            stream_o_TUSER <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    stream_o_TVALID_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3_subdone_grp6_done_reg, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage0_subdone_grp8_done_reg, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage2_subdone_grp10_done_reg, ap_block_pp0_stage3_11001_grp6, ap_block_pp0_stage0_11001_grp8, ap_block_pp0_stage1_11001_grp9, ap_block_pp0_stage2_11001_grp10)
    begin
        if ((((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001_grp9)) or ((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp8) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp8_done_reg)) or ((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001_grp10) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp10_done_reg)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001_grp6) and (ap_const_boolean_0 = ap_block_pp0_stage3_subdone_grp6_done_reg)))) then 
            stream_o_TVALID <= ap_const_logic_1;
        else 
            stream_o_TVALID <= ap_const_logic_0;
        end if; 
    end process;

    tmp_5_fu_444_p4 <= select_ln221_1_fu_375_p3(10 downto 2);
    trunc_ln145_fu_637_p1 <= select_ln24_fu_630_p3(31 - 1 downto 0);
    trunc_ln249_fu_617_p1 <= m_axi_data_mem_0_RDATA(8 - 1 downto 0);
    trunc_ln261_fu_659_p1 <= m_axi_data_mem_0_RDATA(16 - 1 downto 0);
    zext_ln230_fu_407_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln_fu_399_p3),32));
    zext_ln231_fu_544_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln231_fu_539_p2),32));
    zext_ln232_fu_568_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln232_1_fu_563_p2),32));
end behav;
