// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module execute_conv2d_unsigned_int_unsigned_int_dim_t_4u_TensorIO_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        Hlast,
        x_bram_address0,
        x_bram_ce0,
        x_bram_q0,
        y_bram_address0,
        y_bram_ce0,
        y_bram_we0,
        y_bram_d0,
        ap_return
);

parameter    ap_ST_fsm_state1 = 10'd1;
parameter    ap_ST_fsm_state2 = 10'd2;
parameter    ap_ST_fsm_state3 = 10'd4;
parameter    ap_ST_fsm_state4 = 10'd8;
parameter    ap_ST_fsm_state5 = 10'd16;
parameter    ap_ST_fsm_state6 = 10'd32;
parameter    ap_ST_fsm_state7 = 10'd64;
parameter    ap_ST_fsm_state8 = 10'd128;
parameter    ap_ST_fsm_state9 = 10'd256;
parameter    ap_ST_fsm_state10 = 10'd512;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] Hlast;
output  [18:0] x_bram_address0;
output   x_bram_ce0;
input  [7:0] x_bram_q0;
output  [16:0] y_bram_address0;
output   y_bram_ce0;
output   y_bram_we0;
output  [7:0] y_bram_d0;
output  [95:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [9:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [11:0] scratchpad_1_1_address0;
reg    scratchpad_1_1_ce0;
reg    scratchpad_1_1_we0;
wire   [7:0] scratchpad_1_1_q0;
wire   [31:0] y_max_i_fu_268_p3;
reg   [31:0] y_max_i_reg_544;
wire   [31:0] add_ln135_fu_296_p2;
reg   [31:0] add_ln135_reg_550;
wire   [95:0] shape_y_cast_fu_302_p3;
reg   [95:0] shape_y_cast_reg_555;
reg   [31:0] oy_1_reg_559;
wire    ap_CS_fsm_state2;
wire   [31:0] oy_2_fu_333_p2;
reg   [31:0] oy_2_reg_567;
wire   [31:0] iy_fu_339_p2;
reg   [31:0] iy_reg_572;
wire   [0:0] grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_169_2_fu_226_ap_return;
reg   [0:0] targetBlock_reg_577;
wire    ap_CS_fsm_state3;
wire   [16:0] trunc_ln146_fu_346_p1;
reg   [16:0] trunc_ln146_reg_581;
wire    ap_CS_fsm_state4;
wire   [30:0] trunc_ln168_fu_350_p1;
reg   [30:0] trunc_ln168_reg_586;
wire   [10:0] trunc_ln168_1_fu_353_p1;
reg   [10:0] trunc_ln168_1_reg_591;
reg   [11:0] p_cast_reg_599;
wire    ap_CS_fsm_state5;
wire   [40:0] offset_y_3_fu_390_p2;
reg   [40:0] offset_y_3_reg_604;
wire   [9:0] ox_1_fu_402_p2;
reg   [9:0] ox_1_reg_612;
wire    ap_CS_fsm_state6;
wire   [63:0] zext_ln146_fu_408_p1;
reg   [63:0] zext_ln146_reg_617;
wire   [10:0] ix_fu_412_p3;
reg   [10:0] ix_reg_622;
wire   [16:0] offset_y_4_fu_439_p2;
wire    ap_CS_fsm_state7;
wire   [1:0] add_ln187_fu_451_p2;
reg   [1:0] add_ln187_reg_635;
wire    ap_CS_fsm_state8;
wire   [11:0] or_ln_fu_468_p3;
reg   [11:0] or_ln_reg_640;
wire   [0:0] or_ln189_fu_494_p2;
reg   [0:0] or_ln189_reg_645;
wire   [1:0] shuffle_ky_fu_500_p2;
reg   [1:0] shuffle_ky_reg_649;
wire    grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_169_2_fu_226_ap_start;
wire    grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_169_2_fu_226_ap_done;
wire    grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_169_2_fu_226_ap_idle;
wire    grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_169_2_fu_226_ap_ready;
wire   [30:0] grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_169_2_fu_226_y_2_out;
wire    grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_169_2_fu_226_y_2_out_ap_vld;
wire    grp_slice_tensor_2_vector_unsigned_int_unsigned_int_dim_t_4u_TensorIO_s_fu_233_ap_start;
wire    grp_slice_tensor_2_vector_unsigned_int_unsigned_int_dim_t_4u_TensorIO_s_fu_233_ap_done;
wire    grp_slice_tensor_2_vector_unsigned_int_unsigned_int_dim_t_4u_TensorIO_s_fu_233_ap_idle;
wire    grp_slice_tensor_2_vector_unsigned_int_unsigned_int_dim_t_4u_TensorIO_s_fu_233_ap_ready;
wire   [18:0] grp_slice_tensor_2_vector_unsigned_int_unsigned_int_dim_t_4u_TensorIO_s_fu_233_x_bram_address0;
wire    grp_slice_tensor_2_vector_unsigned_int_unsigned_int_dim_t_4u_TensorIO_s_fu_233_x_bram_ce0;
wire   [11:0] grp_slice_tensor_2_vector_unsigned_int_unsigned_int_dim_t_4u_TensorIO_s_fu_233_scratchpad_1_1_address0;
wire    grp_slice_tensor_2_vector_unsigned_int_unsigned_int_dim_t_4u_TensorIO_s_fu_233_scratchpad_1_1_ce0;
wire    grp_slice_tensor_2_vector_unsigned_int_unsigned_int_dim_t_4u_TensorIO_s_fu_233_scratchpad_1_1_we0;
wire   [7:0] grp_slice_tensor_2_vector_unsigned_int_unsigned_int_dim_t_4u_TensorIO_s_fu_233_scratchpad_1_1_d0;
wire    grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_192_6_fu_244_ap_start;
wire    grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_192_6_fu_244_ap_done;
wire    grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_192_6_fu_244_ap_idle;
wire    grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_192_6_fu_244_ap_ready;
wire   [31:0] grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_192_6_fu_244_acc_2_out;
wire    grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_192_6_fu_244_acc_2_out_ap_vld;
wire   [11:0] grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_192_6_fu_244_scratchpad_1_1_address0;
wire    grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_192_6_fu_244_scratchpad_1_1_ce0;
reg   [16:0] offset_y_1_reg_145;
reg    ap_block_state5_on_subcall_done;
wire   [0:0] ap_phi_mux_ic_phi_fu_171_p4;
reg   [9:0] ox_reg_155;
reg   [0:0] ic_reg_166;
wire   [0:0] icmp_ln179_fu_396_p2;
wire   [0:0] icmp_ln187_fu_445_p2;
reg   [31:0] acc_reg_179;
reg   [1:0] ky_2_reg_191;
wire    ap_CS_fsm_state10;
reg   [31:0] acc_1_reg_202;
reg   [31:0] ap_phi_mux_acc_3_phi_fu_218_p4;
reg   [31:0] acc_3_reg_214;
reg    grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_169_2_fu_226_ap_start_reg;
wire   [0:0] icmp_ln167_fu_328_p2;
reg   [30:0] y_2_loc_fu_122;
reg    grp_slice_tensor_2_vector_unsigned_int_unsigned_int_dim_t_4u_TensorIO_s_fu_233_ap_start_reg;
reg    grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_192_6_fu_244_ap_start_reg;
wire    ap_CS_fsm_state9;
reg   [31:0] oy_fu_106;
reg   [40:0] offset_y_fu_110;
reg   [127:0] y_cpy_0_fu_114;
wire   [127:0] zext_ln55_fu_368_p1;
reg    y_bram_we0_local;
reg    y_bram_ce0_local;
wire   [0:0] icmp_ln129_fu_262_p2;
wire   [31:0] add_ln134_fu_276_p2;
wire   [30:0] lshr_ln_fu_282_p4;
wire   [31:0] zext_ln134_fu_292_p1;
wire   [94:0] tmp_s_fu_360_p3;
wire   [0:0] trunc_ln188_fu_457_p1;
wire   [31:0] y_fu_461_p3;
wire   [0:0] icmp_ln189_fu_483_p2;
wire   [0:0] tmp_fu_476_p3;
wire   [0:0] xor_ln189_fu_488_p2;
reg   [9:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
reg    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 10'd1;
#0 grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_169_2_fu_226_ap_start_reg = 1'b0;
#0 grp_slice_tensor_2_vector_unsigned_int_unsigned_int_dim_t_4u_TensorIO_s_fu_233_ap_start_reg = 1'b0;
#0 grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_192_6_fu_244_ap_start_reg = 1'b0;
#0 oy_fu_106 = 32'd0;
#0 offset_y_fu_110 = 41'd0;
#0 y_cpy_0_fu_114 = 128'd0;
end

execute_conv2d_unsigned_int_unsigned_int_dim_t_4u_TensorIO_s_scratchpad_1_1_RAM_AUTO_cud #(
    .DataWidth( 8 ),
    .AddressRange( 3200 ),
    .AddressWidth( 12 ))
scratchpad_1_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(scratchpad_1_1_address0),
    .ce0(scratchpad_1_1_ce0),
    .we0(scratchpad_1_1_we0),
    .d0(grp_slice_tensor_2_vector_unsigned_int_unsigned_int_dim_t_4u_TensorIO_s_fu_233_scratchpad_1_1_d0),
    .q0(scratchpad_1_1_q0)
);

execute_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_169_2 grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_169_2_fu_226(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_169_2_fu_226_ap_start),
    .ap_done(grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_169_2_fu_226_ap_done),
    .ap_idle(grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_169_2_fu_226_ap_idle),
    .ap_ready(grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_169_2_fu_226_ap_ready),
    .empty(iy_reg_572),
    .y_max_i(y_max_i_reg_544),
    .y_2_out(grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_169_2_fu_226_y_2_out),
    .y_2_out_ap_vld(grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_169_2_fu_226_y_2_out_ap_vld),
    .ap_return(grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_169_2_fu_226_ap_return)
);

execute_slice_tensor_2_vector_unsigned_int_unsigned_int_dim_t_4u_TensorIO_s grp_slice_tensor_2_vector_unsigned_int_unsigned_int_dim_t_4u_TensorIO_s_fu_233(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_slice_tensor_2_vector_unsigned_int_unsigned_int_dim_t_4u_TensorIO_s_fu_233_ap_start),
    .ap_done(grp_slice_tensor_2_vector_unsigned_int_unsigned_int_dim_t_4u_TensorIO_s_fu_233_ap_done),
    .ap_idle(grp_slice_tensor_2_vector_unsigned_int_unsigned_int_dim_t_4u_TensorIO_s_fu_233_ap_idle),
    .ap_ready(grp_slice_tensor_2_vector_unsigned_int_unsigned_int_dim_t_4u_TensorIO_s_fu_233_ap_ready),
    .y_start(y_2_loc_fu_122),
    .x_bram_address0(grp_slice_tensor_2_vector_unsigned_int_unsigned_int_dim_t_4u_TensorIO_s_fu_233_x_bram_address0),
    .x_bram_ce0(grp_slice_tensor_2_vector_unsigned_int_unsigned_int_dim_t_4u_TensorIO_s_fu_233_x_bram_ce0),
    .x_bram_q0(x_bram_q0),
    .scratchpad_1_1_address0(grp_slice_tensor_2_vector_unsigned_int_unsigned_int_dim_t_4u_TensorIO_s_fu_233_scratchpad_1_1_address0),
    .scratchpad_1_1_ce0(grp_slice_tensor_2_vector_unsigned_int_unsigned_int_dim_t_4u_TensorIO_s_fu_233_scratchpad_1_1_ce0),
    .scratchpad_1_1_we0(grp_slice_tensor_2_vector_unsigned_int_unsigned_int_dim_t_4u_TensorIO_s_fu_233_scratchpad_1_1_we0),
    .scratchpad_1_1_d0(grp_slice_tensor_2_vector_unsigned_int_unsigned_int_dim_t_4u_TensorIO_s_fu_233_scratchpad_1_1_d0)
);

execute_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_192_6 grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_192_6_fu_244(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_192_6_fu_244_ap_start),
    .ap_done(grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_192_6_fu_244_ap_done),
    .ap_idle(grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_192_6_fu_244_ap_idle),
    .ap_ready(grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_192_6_fu_244_ap_ready),
    .acc_1(acc_1_reg_202),
    .or_ln(or_ln_reg_640),
    .p_cast(p_cast_reg_599),
    .zext_ln182(ix_reg_622),
    .empty(shuffle_ky_reg_649),
    .acc_2_out(grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_192_6_fu_244_acc_2_out),
    .acc_2_out_ap_vld(grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_192_6_fu_244_acc_2_out_ap_vld),
    .scratchpad_1_1_address0(grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_192_6_fu_244_scratchpad_1_1_address0),
    .scratchpad_1_1_ce0(grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_192_6_fu_244_scratchpad_1_1_ce0),
    .scratchpad_1_1_q0(scratchpad_1_1_q0)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_169_2_fu_226_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln167_fu_328_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
            grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_169_2_fu_226_ap_start_reg <= 1'b1;
        end else if ((grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_169_2_fu_226_ap_ready == 1'b1)) begin
            grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_169_2_fu_226_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_192_6_fu_244_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state8) & (icmp_ln187_fu_445_p2 == 1'd0) & (or_ln189_fu_494_p2 == 1'd0))) begin
            grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_192_6_fu_244_ap_start_reg <= 1'b1;
        end else if ((grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_192_6_fu_244_ap_ready == 1'b1)) begin
            grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_192_6_fu_244_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_slice_tensor_2_vector_unsigned_int_unsigned_int_dim_t_4u_TensorIO_s_fu_233_ap_start_reg <= 1'b0;
    end else begin
        if (((targetBlock_reg_577 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
            grp_slice_tensor_2_vector_unsigned_int_unsigned_int_dim_t_4u_TensorIO_s_fu_233_ap_start_reg <= 1'b1;
        end else if ((grp_slice_tensor_2_vector_unsigned_int_unsigned_int_dim_t_4u_TensorIO_s_fu_233_ap_ready == 1'b1)) begin
            grp_slice_tensor_2_vector_unsigned_int_unsigned_int_dim_t_4u_TensorIO_s_fu_233_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        acc_1_reg_202 <= ap_phi_mux_acc_3_phi_fu_218_p4;
    end else if (((1'b1 == ap_CS_fsm_state7) & (ap_phi_mux_ic_phi_fu_171_p4 == 1'd0))) begin
        acc_1_reg_202 <= acc_reg_179;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state10) & (or_ln189_reg_645 == 1'd0))) begin
        acc_3_reg_214 <= grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_192_6_fu_244_acc_2_out;
    end else if (((1'b1 == ap_CS_fsm_state8) & (icmp_ln187_fu_445_p2 == 1'd0) & (or_ln189_fu_494_p2 == 1'd1))) begin
        acc_3_reg_214 <= acc_1_reg_202;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state8) & (icmp_ln187_fu_445_p2 == 1'd1))) begin
        acc_reg_179 <= acc_1_reg_202;
    end else if (((1'b1 == ap_CS_fsm_state6) & (icmp_ln179_fu_396_p2 == 1'd0))) begin
        acc_reg_179 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state8) & (icmp_ln187_fu_445_p2 == 1'd1))) begin
        ic_reg_166 <= 1'd1;
    end else if (((1'b1 == ap_CS_fsm_state6) & (icmp_ln179_fu_396_p2 == 1'd0))) begin
        ic_reg_166 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        ky_2_reg_191 <= add_ln187_reg_635;
    end else if (((1'b1 == ap_CS_fsm_state7) & (ap_phi_mux_ic_phi_fu_171_p4 == 1'd0))) begin
        ky_2_reg_191 <= 2'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state7) & (ap_phi_mux_ic_phi_fu_171_p4 == 1'd1))) begin
        offset_y_1_reg_145 <= offset_y_4_fu_439_p2;
    end else if (((1'b1 == ap_CS_fsm_state5) & (1'b0 == ap_block_state5_on_subcall_done))) begin
        offset_y_1_reg_145 <= trunc_ln146_reg_581;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        offset_y_fu_110 <= 41'd0;
    end else if (((1'b1 == ap_CS_fsm_state6) & (icmp_ln179_fu_396_p2 == 1'd1))) begin
        offset_y_fu_110 <= offset_y_3_reg_604;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state7) & (ap_phi_mux_ic_phi_fu_171_p4 == 1'd1))) begin
        ox_reg_155 <= ox_1_reg_612;
    end else if (((1'b1 == ap_CS_fsm_state5) & (1'b0 == ap_block_state5_on_subcall_done))) begin
        ox_reg_155 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        oy_fu_106 <= 32'd0;
    end else if (((1'b1 == ap_CS_fsm_state6) & (icmp_ln179_fu_396_p2 == 1'd1))) begin
        oy_fu_106 <= oy_2_reg_567;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                y_cpy_0_fu_114[64] <= 1'b0;
        y_cpy_0_fu_114[65] <= 1'b0;
        y_cpy_0_fu_114[66] <= 1'b0;
        y_cpy_0_fu_114[67] <= 1'b0;
        y_cpy_0_fu_114[68] <= 1'b0;
        y_cpy_0_fu_114[69] <= 1'b0;
        y_cpy_0_fu_114[70] <= 1'b0;
        y_cpy_0_fu_114[71] <= 1'b0;
        y_cpy_0_fu_114[72] <= 1'b0;
        y_cpy_0_fu_114[73] <= 1'b0;
        y_cpy_0_fu_114[74] <= 1'b0;
        y_cpy_0_fu_114[75] <= 1'b0;
        y_cpy_0_fu_114[76] <= 1'b0;
        y_cpy_0_fu_114[77] <= 1'b0;
        y_cpy_0_fu_114[78] <= 1'b0;
        y_cpy_0_fu_114[79] <= 1'b0;
        y_cpy_0_fu_114[80] <= 1'b0;
        y_cpy_0_fu_114[81] <= 1'b0;
        y_cpy_0_fu_114[82] <= 1'b0;
        y_cpy_0_fu_114[83] <= 1'b0;
        y_cpy_0_fu_114[84] <= 1'b0;
        y_cpy_0_fu_114[85] <= 1'b0;
        y_cpy_0_fu_114[86] <= 1'b0;
        y_cpy_0_fu_114[87] <= 1'b0;
        y_cpy_0_fu_114[88] <= 1'b0;
        y_cpy_0_fu_114[89] <= 1'b0;
        y_cpy_0_fu_114[90] <= 1'b0;
        y_cpy_0_fu_114[91] <= 1'b0;
        y_cpy_0_fu_114[92] <= 1'b0;
        y_cpy_0_fu_114[93] <= 1'b0;
        y_cpy_0_fu_114[94] <= 1'b0;
    end else if (((targetBlock_reg_577 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
                y_cpy_0_fu_114[94 : 64] <= zext_ln55_fu_368_p1[94 : 64];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        add_ln135_reg_550 <= add_ln135_fu_296_p2;
        shape_y_cast_reg_555[95 : 64] <= shape_y_cast_fu_302_p3[95 : 64];
        y_max_i_reg_544 <= y_max_i_fu_268_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        add_ln187_reg_635 <= add_ln187_fu_451_p2;
        or_ln189_reg_645 <= or_ln189_fu_494_p2;
        or_ln_reg_640 <= or_ln_fu_468_p3;
        shuffle_ky_reg_649 <= shuffle_ky_fu_500_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        ix_reg_622[10 : 1] <= ix_fu_412_p3[10 : 1];
        ox_1_reg_612 <= ox_1_fu_402_p2;
        zext_ln146_reg_617[16 : 0] <= zext_ln146_fu_408_p1[16 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        iy_reg_572 <= iy_fu_339_p2;
        oy_1_reg_559 <= oy_fu_106;
        oy_2_reg_567 <= oy_2_fu_333_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        offset_y_3_reg_604 <= offset_y_3_fu_390_p2;
        p_cast_reg_599 <= {{y_cpy_0_fu_114[75:64]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        targetBlock_reg_577 <= grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_169_2_fu_226_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        trunc_ln146_reg_581 <= trunc_ln146_fu_346_p1;
        trunc_ln168_1_reg_591 <= trunc_ln168_1_fu_353_p1;
        trunc_ln168_reg_586 <= trunc_ln168_fu_350_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_169_2_fu_226_y_2_out_ap_vld == 1'b1))) begin
        y_2_loc_fu_122 <= grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_169_2_fu_226_y_2_out;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_169_2_fu_226_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state5_on_subcall_done)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

always @ (*) begin
    if ((grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_192_6_fu_244_ap_done == 1'b0)) begin
        ap_ST_fsm_state9_blk = 1'b1;
    end else begin
        ap_ST_fsm_state9_blk = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln167_fu_328_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2)) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) & (or_ln189_reg_645 == 1'd0))) begin
        ap_phi_mux_acc_3_phi_fu_218_p4 = grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_192_6_fu_244_acc_2_out;
    end else begin
        ap_phi_mux_acc_3_phi_fu_218_p4 = acc_3_reg_214;
    end
end

always @ (*) begin
    if (((icmp_ln167_fu_328_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        scratchpad_1_1_address0 = grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_192_6_fu_244_scratchpad_1_1_address0;
    end else if (((targetBlock_reg_577 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        scratchpad_1_1_address0 = grp_slice_tensor_2_vector_unsigned_int_unsigned_int_dim_t_4u_TensorIO_s_fu_233_scratchpad_1_1_address0;
    end else begin
        scratchpad_1_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        scratchpad_1_1_ce0 = grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_192_6_fu_244_scratchpad_1_1_ce0;
    end else if (((targetBlock_reg_577 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        scratchpad_1_1_ce0 = grp_slice_tensor_2_vector_unsigned_int_unsigned_int_dim_t_4u_TensorIO_s_fu_233_scratchpad_1_1_ce0;
    end else begin
        scratchpad_1_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((targetBlock_reg_577 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        scratchpad_1_1_we0 = grp_slice_tensor_2_vector_unsigned_int_unsigned_int_dim_t_4u_TensorIO_s_fu_233_scratchpad_1_1_we0;
    end else begin
        scratchpad_1_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        y_bram_ce0_local = 1'b1;
    end else begin
        y_bram_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) & (ap_phi_mux_ic_phi_fu_171_p4 == 1'd1))) begin
        y_bram_we0_local = 1'b1;
    end else begin
        y_bram_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln167_fu_328_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_169_2_fu_226_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((1'b1 == ap_CS_fsm_state5) & (1'b0 == ap_block_state5_on_subcall_done))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            if (((1'b1 == ap_CS_fsm_state6) & (icmp_ln179_fu_396_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state7 : begin
            if (((1'b1 == ap_CS_fsm_state7) & (ap_phi_mux_ic_phi_fu_171_p4 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state8 : begin
            if (((1'b1 == ap_CS_fsm_state8) & (icmp_ln187_fu_445_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else if (((1'b1 == ap_CS_fsm_state8) & (icmp_ln187_fu_445_p2 == 1'd0) & (or_ln189_fu_494_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state9 : begin
            if (((1'b1 == ap_CS_fsm_state9) & (grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_192_6_fu_244_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln134_fu_276_p2 = ($signed(y_max_i_fu_268_p3) + $signed(32'd4294967294));

assign add_ln135_fu_296_p2 = (zext_ln134_fu_292_p1 + 32'd1);

assign add_ln187_fu_451_p2 = (ky_2_reg_191 + 2'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state5_on_subcall_done = ((targetBlock_reg_577 == 1'd0) & (grp_slice_tensor_2_vector_unsigned_int_unsigned_int_dim_t_4u_TensorIO_s_fu_233_ap_done == 1'b0));
end

assign ap_phi_mux_ic_phi_fu_171_p4 = ic_reg_166;

assign ap_return = shape_y_cast_reg_555;

assign grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_169_2_fu_226_ap_start = grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_169_2_fu_226_ap_start_reg;

assign grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_192_6_fu_244_ap_start = grp_conv2d_unsigned_int_unsigned_int_dim_t_TensorIO_Pipeline_VITIS_LOOP_192_6_fu_244_ap_start_reg;

assign grp_slice_tensor_2_vector_unsigned_int_unsigned_int_dim_t_4u_TensorIO_s_fu_233_ap_start = grp_slice_tensor_2_vector_unsigned_int_unsigned_int_dim_t_4u_TensorIO_s_fu_233_ap_start_reg;

assign icmp_ln129_fu_262_p2 = ((Hlast != 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln167_fu_328_p2 = ((oy_fu_106 == add_ln135_reg_550) ? 1'b1 : 1'b0);

assign icmp_ln179_fu_396_p2 = ((ox_reg_155 == 10'd800) ? 1'b1 : 1'b0);

assign icmp_ln187_fu_445_p2 = ((ky_2_reg_191 == 2'd2) ? 1'b1 : 1'b0);

assign icmp_ln189_fu_483_p2 = (($signed(y_fu_461_p3) < $signed(y_max_i_reg_544)) ? 1'b1 : 1'b0);

assign ix_fu_412_p3 = {{ox_reg_155}, {1'd0}};

assign iy_fu_339_p2 = oy_fu_106 << 32'd1;

assign lshr_ln_fu_282_p4 = {{add_ln134_fu_276_p2[31:1]}};

assign offset_y_3_fu_390_p2 = (offset_y_fu_110 + 41'd800);

assign offset_y_4_fu_439_p2 = (offset_y_1_reg_145 + 17'd1);

assign or_ln189_fu_494_p2 = (xor_ln189_fu_488_p2 | tmp_fu_476_p3);

assign or_ln_fu_468_p3 = {{trunc_ln168_1_reg_591}, {trunc_ln188_fu_457_p1}};

assign ox_1_fu_402_p2 = (ox_reg_155 + 10'd1);

assign oy_2_fu_333_p2 = (oy_fu_106 + 32'd1);

assign shape_y_cast_fu_302_p3 = {{add_ln135_fu_296_p2}, {64'd4294967297}};

assign shuffle_ky_fu_500_p2 = ky_2_reg_191 << 2'd1;

assign tmp_fu_476_p3 = oy_1_reg_559[32'd30];

assign tmp_s_fu_360_p3 = {{y_2_loc_fu_122}, {64'd0}};

assign trunc_ln146_fu_346_p1 = offset_y_fu_110[16:0];

assign trunc_ln168_1_fu_353_p1 = oy_fu_106[10:0];

assign trunc_ln168_fu_350_p1 = oy_fu_106[30:0];

assign trunc_ln188_fu_457_p1 = ky_2_reg_191[0:0];

assign x_bram_address0 = grp_slice_tensor_2_vector_unsigned_int_unsigned_int_dim_t_4u_TensorIO_s_fu_233_x_bram_address0;

assign x_bram_ce0 = grp_slice_tensor_2_vector_unsigned_int_unsigned_int_dim_t_4u_TensorIO_s_fu_233_x_bram_ce0;

assign xor_ln189_fu_488_p2 = (icmp_ln189_fu_483_p2 ^ 1'd1);

assign y_bram_address0 = zext_ln146_reg_617;

assign y_bram_ce0 = y_bram_ce0_local;

assign y_bram_d0 = {{acc_reg_179[15:8]}};

assign y_bram_we0 = y_bram_we0_local;

assign y_fu_461_p3 = {{trunc_ln168_reg_586}, {trunc_ln188_fu_457_p1}};

assign y_max_i_fu_268_p3 = ((icmp_ln129_fu_262_p2[0:0] == 1'b1) ? Hlast : 32'd1300);

assign zext_ln134_fu_292_p1 = lshr_ln_fu_282_p4;

assign zext_ln146_fu_408_p1 = offset_y_1_reg_145;

assign zext_ln55_fu_368_p1 = tmp_s_fu_360_p3;

always @ (posedge ap_clk) begin
    shape_y_cast_reg_555[63:0] <= 64'b0000000000000000000000000000000100000000000000000000000000000001;
    zext_ln146_reg_617[63:17] <= 47'b00000000000000000000000000000000000000000000000;
    ix_reg_622[0] <= 1'b0;
    y_cpy_0_fu_114[63:0] <= 64'b0000000000000000000000000000000000000000000000000000000000000000;
    y_cpy_0_fu_114[127:95] <= 33'b000000000000000000000000000000000;
end

endmodule //execute_conv2d_unsigned_int_unsigned_int_dim_t_4u_TensorIO_s
